- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigration.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/AuthTokenConverter.java
- store/src/java/com/zimbra/qa/unittest/TestModifyDynamicEphemeralAttrs.java
- store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
Updated _LdapProvisioning::modifyEphemeralAttrs_ to support dynamic ephemeral attributes. This is done by leveraging existing AttributeConverter classes to try to parse the provided as LDAP-formatted strings. If the provided value cannot be parsed with the appropriate AttributeConverter, or if the AttributeConverter does not exist for the ephemeral attribute, then a warning is logged and the  operation is skipped.
> ZMS-603: Modify dynamic ephemeral attributes via Provisioning::modifyAttrs

- store/src/java/com/zimbra/qa/unittest/TestFolders.java
Removed TestCase subclass from TestFolder; added @BeforeClass/@AfterClass-annotated methods to create/destroy a test account.
> ZMS-573: TestFolder unit test fix

- store/src/java/com/zimbra/cs/dav/service/DavServlet.java
Added code to URLDecode calendar path string before comparison. This was a regression. 
The regression caused value: /dav/test1@domain.com/Calendar to be compared to  value: /dav/test1%40domain.com/Calendar/39e4bcf0-c3e7-4603-b202-8b521ca29c64.ics. This resulted in long URL being returned in calendar-query
Checked by installing zm-store jar with the fix on 8.7.5 installation. Configured an account with shared calendar in iCal on Mac and verified that appts  in shared and own calendar are shown and do not disappear. Verified with both recurring and non recurring appts.
> ZCS-1001 CalDav shared calendar fix

- client/src/java/com/zimbra/client/ZMailbox.java
- store/src/java/com/zimbra/cs/service/mail/ItemAction.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/qa/unittest/TestZClient.java
Implemented _ZMailbox::setTags_ method, with corresponding unit test. This was a little more tricky than alterTag, since the ItemAction SOAP handler used to require the folderId to be included in the request in order to perform a tag update operation, while _MailboxStore.setTags_ does not include it. I updated the server code as follows:
1. ItemAction::handleCommon allows for iidFolder to remain null.
2. ItemActionHelper::schedule does not set targeted=true if the operation is UPDATE but the folder id is null.
The SOAP docs do not state that the folder ID is required for the "update tags" operation, so this change actually makes the ItemActionRequest API consistent with the documentation:
> For op="update", caller can specify any or all of: l="{folder}", name="{name}", color="{color}",
> …
> ZMS-226: ZMailbox::setTags implementation

- store/src/java/com/zimbra/cs/filter/FilterUtil.java
Issue:
When notify ":from" options is specified using a variable that the value has a backslash and is set with :quotewildcard, From in the notification message is different from Return-Path
Fix:
Added escape sequnce in the value set in mailSender.setEnvelopeFrom()
> ZCS-870 : Escaping backslash in From header different from Envelope From

- store/src/java-test/com/zimbra/cs/ephemeral/EphemeralStoreTest.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/ephemeral/EphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/FallbackEphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/InMemoryEphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/LdapEphemeralStore.java
Added a new _deleteData_ method to the EphemeralStore interface that is meant to delete all ephemeral data for a given EphemeralLocation instance. This is called from LdapProvisioning::deleteAccount. If the ephemeral backend is LDAP, this step is skipped, since the data will be deleted anyways.
> ZMS-607: Deleting ephemeral data on account deletion

- store/src/java/com/zimbra/cs/imap/RemoteImapMailboxStore.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapMailboxStore.java
Implemented _RemoteImapMailboxStore::addressMatchesAccountOrSendAs_, as well as a corresponding unit test. The method uses the same underlying call as _LocalImapMailboxStore_, except it gets the account instance using the _RemoteImapMailboxStore.getAccount()_ method.
> ZMS-194: RemoteImapMailboxStore::addressMatchesAccountOrSendAs

- store/src/java/com/zimbra/cs/zimlet/ZimletUtil.java
Fix for https://bugzilla.zimbra.com/show_bug.cgi?id=107843
Check zimlet files path against symlink-resolved /opt/zimbra/zimlets-deployed.
> account for symbolic links when checking paths in zimlet archives

- client/src/java/com/zimbra/client/ZMailbox.java
- store/src/java/com/zimbra/qa/unittest/TestZClient.java
ZMailbox will always have the value of lastChangeId that reflects lastChangeId of Mailbox object at the time of last SOAP request sent by ZMailbox to mailstore. IMAP uses last change ID to create an ID string for a serialized session cache.
> implement getLastChangeId

- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/soap/MailConstants.java
- soap/src/java/com/zimbra/soap/mail/message/ConvActionResponse.java
- soap/src/java/com/zimbra/soap/mail/message/DocumentActionResponse.java
- soap/src/java/com/zimbra/soap/mail/message/ItemActionResponse.java
- soap/src/java/com/zimbra/soap/mail/message/MsgActionResponse.java
- soap/src/java/com/zimbra/soap/mail/message/NoteActionResponse.java
- soap/src/java/com/zimbra/soap/mail/type/ActionResult.java
- soap/src/java/com/zimbra/soap/mail/type/ActionSelector.java
- soap/src/java/com/zimbra/soap/mail/type/FolderActionResult.java
- soap/src/java/com/zimbra/soap/mail/type/IdAndOperation.java
- store/src/java-test/com/zimbra/cs/service/mail/ItemActionTest.java
- store/src/java/com/zimbra/cs/service/mail/ContactAction.java
- store/src/java/com/zimbra/cs/service/mail/ContactActionHelper.java
- store/src/java/com/zimbra/cs/service/mail/ConvAction.java
- store/src/java/com/zimbra/cs/service/mail/CopyActionResult.java
- store/src/java/com/zimbra/cs/service/mail/DeleteActionResult.java
- store/src/java/com/zimbra/cs/service/mail/FolderAction.java
- store/src/java/com/zimbra/cs/service/mail/ItemAction.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionResult.java
- store/src/java/com/zimbra/cs/service/mail/MsgAction.java
- store/src/java/com/zimbra/cs/service/mail/NoteAction.java
- store/src/java/com/zimbra/cs/service/mail/TagAction.java
- store/src/java/com/zimbra/qa/unittest/TestZClient.java
Note: This contains a lot of commits.
The original return type was a comma-separated string of integers.
This needed to be expanded to include the ability to return more than one set of data depending on the operation.
Currently only the 'delete' operation was expanded in order to return the non-existent ids which were attempted to be deleted but not present.
Optimizations are still needed but this is a first pass at getting this working.
> Implement ZMailbox.delete - ZMS-624 & ZMS-198

- store/src/java/com/zimbra/qa/unittest/TestGetMsg.java
- store/src/java/com/zimbra/qa/unittest/TestStoreManager.java
zimbra@mail130:/root$ zmsoap -z
RunUnitTestsRequest/test=com.zimbra.qa.unittest.TestGetMsg
<RunUnitTestsResponse numFailed="0" numSkipped="0" numExecuted="3"
xmlns="urn:zimbraAdmin">
<results>
<completed name="testPlainMessageContent"
class="com.zimbra.qa.unittest.TestGetMsg" execSeconds="18.57"/>
<completed name="testHtmlMessageContent"
class="com.zimbra.qa.unittest.TestGetMsg" execSeconds="1.19"/>
<completed name="testEnrichedMessageContent"
class="com.zimbra.qa.unittest.TestGetMsg" execSeconds="0.63"/>
</results>
</RunUnitTestsResponse>
zimbra@mail130:/root$
> bugfix/ZCS-1128 TestGetMsg

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/filter/EnvelopeTest.java
- store/src/java-test/com/zimbra/cs/filter/EscapeSequencesTest.java
- store/src/java-test/com/zimbra/cs/filter/HeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/NotifyMailtoTest.java
- store/src/java-test/com/zimbra/cs/filter/NotifyTest.java
- store/src/java-test/com/zimbra/cs/filter/RejectTest.java
- store/src/java-test/com/zimbra/cs/filter/RuleManagerAdminFilterTest.java
- store/src/java-test/com/zimbra/cs/service/mail/ModifyFilterRulesTest.java
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
- store/src/java/com/zimbra/cs/filter/JsieveConfigMapHandler.java
- store/src/java/com/zimbra/cs/filter/RuleManager.java
- store/src/java/com/zimbra/cs/filter/SoapToSieve.java
- store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
- store/src/java/com/zimbra/cs/filter/jsieve/NotifyMailto.java
- store/src/java/com/zimbra/cs/filter/jsieve/Reject.java
- store/src/java/com/zimbra/qa/unittest/TestFilter.java
- store/src/java/com/zimbra/qa/unittest/TestFilterRFCCompliantNotify.java
1. Deprecated old sieve attributes with id 2090, 2091, 2091, 2093, 2094, 2095
2. Added new attributes which can be used in place of the above deprecated attributes. All the attributes are defined at account, cos and domain level.
3. Since there is confusion about the release version, right now I have kept as 8.7.8. Please let me know if that needs to be changed
Testing - 
ant test
Will send a separate pull request for automation
> ZCS-1291 Deprecate old sieve ldap attributes and add new

- client/src/java/com/zimbra/client/ZIdHit.java
- client/src/java/com/zimbra/client/ZMailbox.java
- client/src/java/com/zimbra/client/ZSearchParams.java
- client/src/java/com/zimbra/client/ZSearchResult.java
- common/src/java/com/zimbra/common/soap/MailConstants.java
- soap/src/java/com/zimbra/soap/type/SearchSortBy.java
- store/src/java/com/zimbra/cs/service/mail/SearchResponse.java
- store/src/java/com/zimbra/qa/unittest/TestZClient.java
Support for five search parameters in ZSearchParams:
- ZMS-229: ZSearchParams::getIncludeTagDeleted/setIncludeTagDeleted
- implemented the ZSearchParams methods and added support in ZMailbox
- added TestZClient::testZSearchParamsIncludeTagDeleted unit test
- ZMS-230: ZSearchParams::getMailItemTypes/setMailItemTypes
- implemented the ZSearchParams methods
- added TestZClient::testZSearchParamsMailItemTypes unit test
- ZMS-231: ZSearchParams::setZimbraSortBy / getZimbraSortBy
- implemented the ZSearchParams methods
- added a mapping between SearchSortBy and ZimbraSortBy enums
- added TestZClient::testZSearchParamsZimbraSortBy unit test
- ZMS-232: ZSearchParams::setZimbraFetchMode/getZimbraFetchMode
- implemented the ZSearchParams methods
- added an E_HIT="hit" constant in MailConstants …
> ZMS-228: Various ZSearchParams Methods

- build.xml
Adding clean-ant target without using make for windows users
> Adding clean-ant target without using make for windows users

- client/src/java/com/zimbra/client/ZContactHit.java
- client/src/java/com/zimbra/client/ZIdHit.java
- client/src/java/com/zimbra/client/ZImapSearchHit.java
- client/src/java/com/zimbra/client/ZMailbox.java
- client/src/java/com/zimbra/client/ZMessageHit.java
- client/src/java/com/zimbra/client/ZRemoteQueryHitResults.java
- client/src/java/com/zimbra/client/ZSearchResult.java
- common/src/java/com/zimbra/common/mailbox/MailboxStore.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/imap/ImapSessionManager.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/service/mail/SearchResponse.java
- store/src/java/com/zimbra/cs/service/mail/ToXML.java
- store/src/java/com/zimbra/cs/session/PendingModifications.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapShared.java
- store/src/java/com/zimbra/qa/unittest/TestZClient.java
For clarity, I renamed this interface method from "search" to "searchImap" since it is only used by the IMAP server and only returns IMAP-compatible results.
- A new interface _ZImapSearchHit_ is introduced. This interface combines _ZSearchHit_ (the base for all client-side search results) and _ZimbraQueryHit_ (returned by _ZimbraQueryHitResults_). Three search hit classes now implement _ZImapSearchHit_:
- _ZMessageHit_ has new _imapUid_ and _modSeq_ fields that default to -1 unless _resultMode_ is set IMAP or MODSEQ.
- _ZContactHit_ has new _imapUid_ and _modSeq_ fields like _ZMessageHit_, but always returns -1 for the parent ID. To get the _getFlagBitmask_ method to work, the _ZContact.Flag_ enum had to be updated with a method to convert the string to a bitmask, similar to the Flag …
> ZMS-227: ZMailbox::searchImap

- store/src/java/com/zimbra/cs/imap/AppendMessage.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapShared.java
The only thing missing from AppendMessage::store behavior when using remote IMAP is proper handling of message tags. This PR fixes this.
It should be noted that although the current ZMailbox behavior requires message tags to be specified by ID, they are returned in the fetch response by name.
The _testAppend_ unit test in SharedImapTests has been updated to set a custom tag on the message, as well as verify that the flags and tags are set on the fetched message. To facilitate this, the _fetchBody_ utility method in SharedImapTests have been split into _fetchMessage_ and _getBody_.
> ZMS-212: Fixed AppendMessage::store behavior with RemoteImapMailboxStore

- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
The bug is already fixed and is tested as part of "testRenameNonExistentFolder". Just added a test to verify this specific behavior without trying to rename.
> add an explicit test for non existent folder

- client/src/java/com/zimbra/client/ZMailbox.java
- store/src/java/com/zimbra/cs/imap/ImapFolder.java
- store/src/java/com/zimbra/cs/imap/RemoteImapMailboxStore.java
- store/src/java/com/zimbra/cs/service/mail/WaitSetRequest.java
- store/src/java/com/zimbra/cs/session/ModificationItem.java
- store/src/java/com/zimbra/cs/session/PendingLocalModifications.java
- store/src/java/com/zimbra/cs/session/PendingModifications.java
- store/src/java/com/zimbra/cs/session/SoapSession.java
- store/src/java/com/zimbra/cs/session/WaitSetSession.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapNotifications.java
When a tag is renamed, two types of notifications are triggered on the server:
- the renamed tag is notified
- all non-empty folders are notified
Some changes had to be made in order for these changes to trigger a waitset:
Prior to this change, a waitset was triggered on a folder when an action was taken on an item in the folder. When a tag is renamed, however, the folders themselves should be notified, as opposed to their parents. In order for this to be recognized by the waitset, the _folderInterest_ mechanism had to be updated to be triggered when a change occurs on the folder itself. To this end, the _PendingModifications_ now contains two integer sets:
- _changedParentFolders_ replaced what used to be called _changedFolders_
- _changedFolders_ now tracks IDs of folders in the …
> ZMS-366: Remote IMAP Tag Rename Handling

- client/src/java/com/zimbra/client/ZMailbox.java
- store/src/java/com/zimbra/cs/imap/AppendMessage.java
- store/src/java/com/zimbra/cs/imap/ImapMessage.java
- store/src/java/com/zimbra/cs/imap/RemoteImapMailboxStore.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
- store/src/java/com/zimbra/qa/unittest/TestLocalImap.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapShared.java
This is a continuation of the work started in ZMS-212.
Changes to SharedImapTests:
- _testAppend_ has been split into _testAppend_ and _testAppendFlags_
- new _getImapZMailbox_ method lets remote IMAP tests access the _ZMailbox_ instance used by the IMAP server. This is necessary for _testAppendTags_ unit test, as folders created using a non-IMAP client are not reflected on the IMAP server in certain scenarios (ZCS-1488 addresses this).
- all append-related remote unit tests have been activated
- _fetchMessage_ method has been updated to fetch flags
Other changes:
- _ZMailbox_ has a new static inner class _TagSpecifier_ that can be used by a new _addMessage_ method signature to specify tags either by name or ID
- _AppendMessage_ uses a _TagSpecifier_ to set the tags by name (other parts …
> ZCS-1429: Append-related unit tests

- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/mailbox/MailboxStore.java
- store/src/java/com/zimbra/cs/imap/ImapPath.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
- store/src/java/com/zimbra/qa/unittest/TestLocalImap.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapShared.java
If a folder is created by a non-IMAP client and an IMAP client attempts to select it, the error is thrown from the _ImapPath_ class as it attempts to retrieve the _ZFolder_ instance from the _ZMailbox_. Since this does not yet exist in the _ZMailbox_ cache, a NO_SUCH_FOLDER exception is thrown.
The easiest way to resolve this is to issue a noOp request in the _ImapPath.getFolder()_ method in the event that the specified folder cannot be found, and trying again. If the folder cannot be found a second time, then the exception can be thrown as before.
In order to avoid checking whether the server is remote, a _noOp()_ method has been added to the MailboxStore interface.
This fix allows us to remove the _SharedImapTests.getImapZMailbox()_ method added as part of ZCS-1429, as that was a …
> ZCS-1488: IMAP selecting folders created by non-IMAP clients

- store/src/java/com/zimbra/qa/unittest/TestRemoteImapShared.java
All remote IMAP tests should be passing now
> remove 'ignore' annotations from remote imap tests

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
ZCS-1572: Add global and server level attribute for enabling zimbraNetworkModulesNGEnabled.
> ZCS-1572:attribute for enabling zimbraNetworkModules. 

- store/src/java-test/com/zimbra/cs/imap/ImapHandlerTest.java
Found that ImapHandlerTest was hanging if mailboxd was running when
one ran this unit test.  Issue was in EhcacheManager/1.  When it
initializes the cache it was using the same persistence file that
mailboxd uses.  By setting the LC value `imap_use_ehcache` to
false, the ImapSessionManager uses DiskImapCache and there is no
conflict.
> ImapHandlerTest - do not use Ehcache

- store/src/java-test/com/zimbra/cs/imap/ImapHandlerTest.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigrationUtil.java
- store/src/java/com/zimbra/cs/extension/ExtensionUtil.java
- store/src/java/com/zimbra/cs/imap/ImapDaemon.java
Update the ImapDaemon to initialize the configured ephemeral
backend extension, based on the setting of
`zimbraEphemeralBackendURL`, if `ldap` is not the configured
backend.
* Implemented Gren's suggestion
* **Note:** This updated branch is based on top of [pull request 166](https://github.com/Zimbra/zm-mailbox/pull/166)
> ZCS-1515 ImapDaemon init ephemeral extension

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
The in-memory cache should ALWAYS be updated even if the operation is
a permanent operation. Otherwise the two views get out of sync.
Allows the zmsoap test to complete succesfully:
`zimbra@zcs-dev-one:/home/zimbra/git/zm-mailbox/store$ zmsoap -z RunUnitTestsRequest test=TestImapClient#testDelete`
<RunUnitTestsResponse numFailed="0" numSkipped="0" numExecuted="1" xmlns="urn:zimbraAdmin">
<results>
<completed name="testDelete" class="com.zimbra.qa.unittest.TestImapClient" execSeconds="0.95"/>
</results>
</RunUnitTestsResponse>
> ZMS-675 ensure session cache is updated

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java-test/com/zimbra/cs/store/external/ImapTransientStoreManagerTest.java
- store/src/java/com/zimbra/cs/imap/ImapDaemon.java
- store/src/java/com/zimbra/cs/imap/NioImapRequest.java
- store/src/java/com/zimbra/cs/store/StoreManager.java
- store/src/java/com/zimbra/cs/store/external/ImapTransientStoreManager.java
Updates to enable `APPEND` command to function properly with both embedded and remote IMAP(S)
In the parsing of the `APPEND` command...
NioImapRequest.parseCommand/1 ->
Literal.newInstance/2 ->
BlobLiteral/1 ->
StoreManager.getInstance().getBlobBuilder()
...we end up initializing the `StoreManager`.
`StoreManager.getInstance/0` was using the `zimbra_class_store` LC value.  It will still use that now, if not running from the `zimbra-imapd` process.  If it is, is uses a new LC value `imapd_class_store`.  The interesting part is that, at least for the `APPEND` command, it doesn't actually store anything on disk.
The new `ImapTransientStoreManager` is now what is being initialized for the remote IMAP(S) servers to use.  As the name implies, it really is for transient blobs that do not need to …
> ZCS-1580 - Append command does not work with Remote IMAP/IMAPS

- store/src/java-test/com/zimbra/cs/imap/ImapLoadBalancingMechanismTest.java
- store/src/java/com/zimbra/cs/imap/ImapLoadBalancingMechanism.java
- store/src/java/com/zimbra/cs/imap/TcpImapHandler.java
Add similar exception handling code as was added previously to NioImapHandler.java in 
https://github.com/Zimbra/zm-mailbox/pull/59/commits/4da976e98e503d7441caf6ee4b3de20975ef2054
> ZMS-339 catch exceptions and return 'BAD' response to client

- build-ivysettings.xml
Currently building the master branch of this repository is broken. Because the zm-mailbox dependency `xerces#xmlParserAPIs;2.6.2` is 404ing (https://maven.repository.redhat.com/ga/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar). It does not exist in the Redhat Maven repo being used to resolve xerces JARs. I narrowed the build configuration so that only the `xerces#xercesImpl;2.9.1-patch-01` dependency is resolved to the Redhat maven repository.
Redhat Maven repo was added in https://github.com/Zimbra/zm-mailbox/pull/189/files#diff-34e3400bfbe00e937202f79eff0c6b33L30
```
[ivy:resolve]
[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve] 		module not found: xerces#xmlParserAPIs;2.6.2
[ivy:resolve] 	==== maven-redhat: tried
[ivy:resolve] 	  -- artifact …
```
> resolve only the xerces#xercesImpl;2.9.1-patch-01 dependency form redhat repository

- build-ivysettings.xml
Fix the xerces resolver to use redhat repo only for xerces#xercesImpl;2.9.1-patch-01 dependency
> ZCS-1726 Resolve only xercesImpl from red hat

- store/src/java-test/com/zimbra/cs/service/mail/ItemActionTest.java
**Note:** This test was not failing on the `develop` branch because it was added in `feature/imap`.
Problem was that the test was looking in the wrong place to fetch the copied item.
> ZCS-1529 ItemActionTest::copyMessageFromDraftsToSent is failing on feature/imap branch

- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/soap/HeaderConstants.java
- common/src/java/com/zimbra/common/soap/SoapHttpTransport.java
- common/src/java/com/zimbra/common/soap/SoapTransport.java
- common/src/java/com/zimbra/common/soap/SoapUtil.java
- store/src/java/com/zimbra/cs/imap/ImapServerListener.java
- store/src/java/com/zimbra/cs/mailclient/imap/ImapResponse.java
- store/src/java/com/zimbra/cs/service/mail/WaitSetRequest.java
- store/src/java/com/zimbra/cs/session/PendingModifications.java
- store/src/java/com/zimbra/cs/session/SoapSession.java
- store/src/java/com/zimbra/cs/session/WaitSetSession.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapNotifications.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapNotificationsViaMailbox.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapNotificationsViaWaitsets.java
- store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
- store/src/java/com/zimbra/soap/DocumentHandler.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
The current remote IMAP notification mechanism introduces race conditions that result in bugs. The race condition occurs when an IMAP operation potentially returns before the corresponding changes are propagated back to the originating IMAP server via waitsets; this causes problems when a subsequent IMAP operation sees a stale view of the IMAP data. [ZCS-1482](https://jira.corp.synacor.com/browse/ZCS-1482) is an example of this type of bug.
This PR introduces two changes to IMAP notifications:
1. All IMAP notifications are returned in the SOAP response headers.
_WaitSetRequest_ and _SoapSession_ now encode pending modifications in an identical way, using common logic. This code is now contained in the new _PendingModifications::encodeFolderModifications_ method. This method accepts an …
> ZCS-1670: IMAP notifications in response headers

- store/src/java/com/zimbra/qa/unittest/TestRemoteImapNotifications.java
Opening a new PR for this issue since the original one (https://github.com/Zimbra/zm-mailbox/pull/202) was inadvertently closed.
> ZMS-358: updated tag deletion IMAP tests

- store/src/java/com/zimbra/qa/unittest/ImapTestBase.java
- store/src/java/com/zimbra/qa/unittest/SharedImapNotificationTests.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
- store/src/java/com/zimbra/qa/unittest/TestEmbeddedRemoteImapNotificationsViaMailbox.java
- store/src/java/com/zimbra/qa/unittest/TestEmbeddedRemoteImapNotificationsViaWaitsets.java
- store/src/java/com/zimbra/qa/unittest/TestImapDaemonNotificationsViaMailbox.java
- store/src/java/com/zimbra/qa/unittest/TestImapDaemonNotificationsViaWaitsets.java
- store/src/java/com/zimbra/qa/unittest/TestImapNotificationsViaMailbox.java
- store/src/java/com/zimbra/qa/unittest/TestImapNotificationsViaWaitsets.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaEmbeddedLocal.java
- store/src/java/com/zimbra/qa/unittest/TestLocalImapNotifications.java
- store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
While tests exist for checking remote IMAP notifications of deleted folders, this PR moves all IMAP notification tests into a framework similar to SharedImapTests where test are defined in an abstract class and server configuration is moved to subclasses. This way, we can test IMAP notifications for the local, embedded remote, and IMAP daemon modes of operation. Since there is a lot of common code between this and SharedImapTests, a new class ImapTestBase has been introduced as a base class for both SharedImapTests and the new SharedImapNotificationTests class.
This results with the following notification test classes:
- TestLocalImapNotifications
- TestEmbeddedRemoteImapNotificationsViaMailbox
- TestEmbeddedRemoteImapNotificationsViaWaitsets
- TestImapDaemonNotificationsViaMailbox
- …
> ZMS-357: local/embedded/remote IMAP notification tests

- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
The mechanism that runs *NoLiteralPlus tests used to set _useLiteralPlus_ to false on the wrong instance of ImapConfig, since the tests would re-instantiate the connection with the original value of _useLiteralPlus_. This fix adds private methods for test that have _NoLiteralPlus_ versions. These methods perform the actual tests with a provided _ImapConnection_ instance, so that the _NoLiteralPlus_ test variations can pass in the modified connection.
This resolves the failing _testCatenateNoLiteralPlus_ issue.
> ZCS-1774: Fixed *NoLiteralPlus IMAP tests

- common/src/java/com/zimbra/common/soap/SoapHttpTransport.java
Reinstated a method signature for _SoapHttpTransport::invoke_ that existed prior to the introduction of _nFormat_ and _curWaitSetID_ arguments. This signature is used by the _CrossMailboxSearch_ class in zm-network-store.
> ZCS-1787: 'invoke' method signature without nFormat and curWaitSetID args

- client/src/java/com/zimbra/client/ZMailbox.java
When _ZMailbox::getMessageById_ receives a "no such message" SOAP exception, it was erroneously throwing _ZClientException.NO_SUCH_CONTACT_, resulting in misleading log entries. This fix changes that to throw _NO_SUCH_MSG_ instead.
No unit test is provided, as this is a trivial change.
> ZCS-1482: NO_SUCH_CONTACT -> NO_SUCH_MSG error fix

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
New IMAP code will be released as a preview in 8.8.1_BETA1 out-of-band and before 8.8.0_GA becomes available. After that, we will merge new IMAP code and zExtras-related changes on "develop" and release both as 8.8.1_BETA2 or 8.8.1_GA.
> change "since" to 8.8.1 for new IMAP-related attrs

- client/src/java/com/zimbra/client/ZFolder.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
added a test that appends a message to Sent folder and checks message count right after. This is how Apple Mail behaves. The test fails before the fix and passes after the fix on all 3 IMAP services (local, remote embedded, remote daemon).
The code change makes ZFolder handle SOAP with notifications similar to how it handles initial SOAP.
> pick up changes in message counts in folders

- client/src/java/com/zimbra/client/ZFolder.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
This bug was caused by the _ZMailbox_ not updating subfolder paths in its folder cache when receiving a _ZModifyFolderEvent_. More specifically, _ZFolder.getPath()_ returns the _mAbsolutePath_ field if it is set, falling back to determining the path based on the parent folder otherwise. To fix this, I added a method _ZFolder.refreshAbsolutePath()_ that recalculates the absolute path based on the parent folder; this also happens recursively for all subfolders. This method is called in _ZFolder.modifyNotification()_, only if the folder name is modified.
A new test method _testRenameParentFolder_ has been added to _SharedImapTests_. The test creates a parent folder with two layers of children, renames the parent folder, and verifies that the children have been renamed accordingly.
EDIT: …
> ZCS-1597: child folder path updated after parent rename

- store/build.xml
Small change to fix a minor annoyance...
Currently the `deploy` target will restart the mailbox so it will
pick up changes; however, the imapd service is not automatically
restarted.  This small change will cause zmimapdctl to be invoked
with the proper option when restarting the mailbox if the
zimbra-imapd service is installed on the developer's machine.
> ant deploy restart imapd

- store/src/java-test/com/zimbra/cs/filter/RequireTest.java
- store/src/java-test/com/zimbra/cs/filter/RuleManagerAdminFilterTest.java
- store/src/java/com/zimbra/cs/filter/JsieveConfigMapHandler.java
- store/src/java/com/zimbra/cs/filter/RuleManager.java
- store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
- store/src/java/com/zimbra/cs/filter/jsieve/ActionExplicitKeep.java
- store/src/java/com/zimbra/cs/filter/jsieve/FileInto.java
- store/src/java/com/zimbra/cs/filter/jsieve/HeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/Keep.java
- store/src/java/com/zimbra/cs/filter/jsieve/Notify.java
- store/src/java/com/zimbra/cs/filter/jsieve/Redirect.java
- store/src/java/com/zimbra/cs/filter/jsieve/Reject.java
- store/src/java/com/zimbra/cs/filter/jsieve/Require.java
- store/src/java/com/zimbra/cs/filter/jsieve/Stop.java
- store/src/java/com/zimbra/cs/filter/jsieve/ZimbraVariablesCtrl.java
[bug]
Any Sieve extension command or test must be declared in
the "require" control before it is called in the rule.
Currently a Sieve rule can call any extension command or
test without the declaration of the "require" control.
[fix]
This ticket (zcs-168) covers to fix the behaviour of
"require" control, and introduces a list of capability
strings which each extension command and test can refer
to during the execution.
previously the admin-defined filters and user-defined
filter were combined into one script and evaluated.
Now each filter script is evaluated separately.
If an action is evaluated as executable, such action’s
executeBasic() method stacks the Action object into the
ZimbraMailAdapter.actions list.  If the currently processing
filter ends up to “stop” action, stop further …
> ZCS-168:Sieve:mandatory require control

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/filter/AddHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/EnvelopeTest.java
- store/src/java-test/com/zimbra/cs/filter/FileIntoCopyTest.java
- store/src/java-test/com/zimbra/cs/filter/FilterUtilTest.java
- store/src/java-test/com/zimbra/cs/filter/GetFilterRulesTest.java
- store/src/java-test/com/zimbra/cs/filter/HeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/NotifyMailtoTest.java
- store/src/java-test/com/zimbra/cs/filter/RedirectCopyTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplyTest.java
- store/src/java-test/com/zimbra/cs/filter/RequireTest.java
- store/src/java-test/com/zimbra/cs/filter/RuleManagerAdminFilterTest.java
- store/src/java-test/com/zimbra/cs/filter/RuleManagerTest.java
- store/src/java-test/com/zimbra/cs/filter/SetVariableTest.java
- store/src/java-test/com/zimbra/cs/filter/TagTest.java
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/filter/FilterUtil.java
- store/src/java/com/zimbra/cs/filter/JsieveConfigMapHandler.java
- store/src/java/com/zimbra/cs/filter/SoapToSieve.java
- store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
- store/src/java/com/zimbra/cs/filter/jsieve/FileInto.java
- store/src/java/com/zimbra/cs/filter/jsieve/NotifyMailto.java
- store/src/java/com/zimbra/cs/filter/jsieve/NotifyMethodCapabilityTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/Redirect.java
- store/src/java/com/zimbra/cs/filter/jsieve/Require.java
- store/src/java/com/zimbra/cs/filter/jsieve/SetVariable.java
[Related issue]
ZCS-168
[Fix]
* Before executing the Sieve extension test or action, ZCS will check whether the corresponding capability string is declared in the "require" control.  If it is declared, such Sieve extension will be executed.  If it is not declared, the entire sieve filter will be failed and no filter will be applied to the message (message will be stored in the default folder (Inbox or Sent)).
* This ticket covers the following Sieve extension:
- "fileinto" (RFC 5228) : "fileinto" action
- "copy" (RFC 3894) : "fileinto" and "redirect" actions
- "variables" (RFC 5229) : "set" action, ":encodeurl" argument for the notify action.
(note: if "variables" is not declared, ${n} will be appeared as is)
- "enotify" (RFC 5435) : "notify" action, "notify_method_capability" test, and …
> ZCS-1169:mandate "require" for Sieve extension

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java-test/com/zimbra/cs/filter/AddHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
- store/src/java/com/zimbra/cs/filter/jsieve/AddHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/DeleteHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/EditHeaderExtension.java
- store/src/java/com/zimbra/cs/filter/jsieve/ReplaceHeader.java
SIEVE: editheader throws ParseException exception if original mail's mime header violates RFC.
[Bug]
When the triggering (original) message contains any MIME header which is not compliant with RFC, the editheader action (addheader/deleteheader/replaceheader) throws the exception of "javax.mail.internet.ParseException", and entire filter execution is canceled.
For example, the Content-Type is sometimes minorly malformed, like a value contains multiple semi-colon characters at the end of the value "Content-Type: text/plain;;". When a message with such malformed Content-Type is edited, even the editheader does not edit the Content-Type header, the ParseException is thrown during the execution of the action, and the message is delivered to the Inbox without editing.
Because the addheader, …
> ZCS-1845:editheader throws ParseException

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZimbraAuthToken.java
- store/src/java/com/zimbra/cs/account/callback/CallbackContext.java
- store/src/java/com/zimbra/cs/account/callback/EphemeralBackendCheck.java
- store/src/java/com/zimbra/cs/ephemeral/EphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/FallbackEphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/InMemoryEphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/LdapEphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigration.java
- store/src/java/com/zimbra/cs/imap/ImapDaemon.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/imap/ImapRequest.java
- store/src/java/com/zimbra/cs/mailclient/imap/CAtom.java
- store/src/java/com/zimbra/cs/mailclient/imap/ImapConnection.java
- store/src/java/com/zimbra/cs/security/sasl/Authenticator.java
- store/src/java/com/zimbra/cs/security/sasl/ZimbraAuthenticator.java
- store/src/java/com/zimbra/cs/service/admin/FlushCache.java
- store/src/java/com/zimbra/cs/service/admin/ReloadLocalConfig.java
- store/src/java/com/zimbra/qa/unittest/ImapTestBase.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
- store/src/java/com/zimbra/qa/unittest/TestImapClient.java
- store/src/java/com/zimbra/qa/unittest/TestImapDaemonNotifications.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaImapDaemon.java
- store/src/java/com/zimbra/qa/unittest/TestUtil.java
- store/src/java/com/zimbra/qa/unittest/prov/TestChangeEphemeralStore.java
This PR adds two new zimbra-only IMAP operations and updates the server to make use of those operations where necessary.
The `FLUSHCACHE` imap command is used to flush the specified cache. It is equivalent to _FlushCacheRequest_, except that it does not support an _allServers_ parameter. The syntax is as follows:
- `FLUSHCACHE <cacheTypes>` flushes the entire cache of the specified comma-separated cache types, such as `FLUSHCACHE account` or `FLUSHCACHE server,config`.
- `FLUSHCACHE <cacheTypes> (<id|name> <entry id or name> ... )` flushes the cache entries specified in the parameters list. For example, a single account can be flushed with `FLUSHCACHE account (id <accountId>)`
The `RELOADLC` imap command forces the imapd server to reload its LocalConfig instance. It is equivalent to …
> ZCS-1790: Ability to flush cache / reload LC on imapd servers

- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
The bug was caused by the fact that the ItemActionRequest API expects the flags to be passed in as a readable string, while ZMailbox sends it as the bitmask. This results in the flags not being parsed by the server correctly. The solution is to update _ItemActionHelper_ to accept a bitmask string as well as the readable form.
> ZCS-1781: Proper IMAP permanent flag handling in the remote case

- client/src/java/com/zimbra/client/ZMailbox.java
Part of the work done for ZCS-1571 changed the behavior of the
`getFolderById` method. Prior to the changes done for that ticket
the `getFolderById` function would return `null` if called
with an argument that was not a folder id; e.g., "INBOX".
More aggressive cache checking created a new behavior that would
instead result in a ServiceException when the method was
called in a similar fashion.
> ZCS-1571 ZMailbox::getFolderById exception with invalid id

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
I checked that with this change compliance tests give same results on local IMAP as on 'develop' branch and that there are no new test failures on this branch.
> zcs-2140: revert code change that always forced updating session flags

- client/src/java/com/zimbra/client/ZFolder.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
This fix addresses one specific scenario where RECENT is not reporting correct number of items after IMAP client selects a folder.
> allow recent cutoff to be zero for remote IMAP

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/admin/type/CacheSelector.java
- store/docs/soap-admin.txt
- store/src/java/com/zimbra/cs/account/ProvUtil.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
- store/src/java/com/zimbra/cs/ephemeral/EphemeralStore.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigration.java
- store/src/java/com/zimbra/cs/extension/ExtensionUtil.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/imap/ImapRequest.java
- store/src/java/com/zimbra/cs/service/admin/FlushCache.java
- store/src/java/com/zimbra/cs/service/admin/ReloadLocalConfig.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaImapDaemon.java
This bug was caused by `X-ZIMBRA-FLUSHCACHE` routing all cache types to _Provisioning.flushCache_, which is incorrect since some cache types, such as _license_ require special handling.
This is fixed with the following changes:
1. Restrict which cache types are forwarded by the _FlushCache_ SOAP handler to imapd servers. Not all cache types are applicable to imapd servers, so it makes sense to only forward relevant ones to avoid unnecessary requests. The relevant caches are listed in the new public static set _ImapHander.IMAP_CACHE_TYPES_, which current consists of _account, cos, domain, server, config_, and _all_. If there are other cache types that should be included here, please comment and I will update this set.
2. Update _ImapHandler_ to ignore other cache types even if they are …
> ZCS-2150: restrict flushing cache types on imapd

- store/src/java/com/zimbra/cs/imap/ImapSessionManager.java
This is a small change that prevents an NPE and throws NO_SUCH_FOLDER exception. I am not adding a test for this specific scenario, because it is already covered by 'append' test in IMAP compliance test suite.
> zcs-2244: prevent an NPE

- store/src/java/com/zimbra/cs/service/authenticator/SpnegoAuthenticator.java
Hello.
There is a typo in a few log messages where "SpnegoAuthenticator" is written out as "SpengoAuthenticator".
Trivial thing, but annoying if you grep the logs looking for "SpnegoAuthenticator".
> Typo correction SpengoAuthenticator -> SpnegoAuthenticator

- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
Added "Auto-Submitted" header name to the zimbraSieveImmutableHeaders
attribute value for the sake of the compatibility with RFC 5293.
> ZCS-887:Add "Auto-Submitted" to zimbraSieveImmutableHeaders

- store/src/java/com/zimbra/cs/service/admin/FlushCache.java
The previous fix to ZCS-2150 did not properly handle the case when _all_ of the provided cache types were filtered out as being not imap-compatible. In that case, X-ZIMBRA-FLUSHCACHE was issued anyways, with an empty string as the cache type, which caused a parse error on the imapd side. This fix updates the _FlushCache_ SOAP handler to not issue the IMAP command if no relevant cache types remain.
> ZCS-2150: don't issue FLUSHCACHE if empty cache type

- store/docs/soap.txt
* Updates to `GetContactsRequest/Response` and `SearchRequest/Response` for
new `memberOf`
* Fixed some errors in SearchResponse description based on
examples/ToXML.encodeContact source.  Nearly all info is currently
represented as Zimbra Attributes instead of having special XML
attributes like "email" and "type"
> ZCS-2271:soap.txt memberOf documentation

- client/src/java/com/zimbra/client/ZGetInfoResult.java
- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/soap/AccountConstants.java
- soap/src/java-test/com/zimbra/soap/account/GetInfoResponse.json
- soap/src/java-test/com/zimbra/soap/account/GetInfoResponse.xml
- soap/src/java-test/com/zimbra/soap/account/GetInfoResponseTest.java
- soap/src/java-test/com/zimbra/soap/account/JaxbToElementTest.java
- soap/src/java/com/zimbra/soap/account/message/GetInfoResponse.java
- store/src/java/com/zimbra/cs/imap/ImapSessionManager.java
- store/src/java/com/zimbra/cs/service/account/GetInfo.java
Currently the `BeginTrackingIMAPRequest` is issued for every:
- session creation
- folder selection
This PR:
- removes the folder selection tracking request entirely
- piggy-backs the ability to notify the caller using the GetInfoResponse of the tracking state of the user with the 'isTrackingIMAP' tag.
ZMailbox has been updated to only issue the `BeginTrackingIMAPRequest` If and only if the `isTrackingIMAP` value is '0'.
> Bugfix/zcs 2242 Optimize the BeginTrackingIMAPRequest SOAP call

- store/src/java-test/com/zimbra/cs/filter/AddHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/EditHeaderExtension.java
[bug]
Each element of the 'SieveImmutableHeaders' attribute was compared case-sensitively with the header name specified in the editheader actions' parameter.  As a result, sometimes headers were not immutable, and mistakenly added, deleted, and replaced.
[fix]
* Compared the header name case-insensitively. Any header name listed in the 'SieveImmutableHeaders' will not be editable no matter what letter the header name is specified in.
* Refactored the unit case code for improving the visibility.
[manual test]
* Unit test case: PASS
- AddHeaderTest
- DeleteHeaderTest
- ReplaceHeaderTest
> ZCS-1850:case-insensitive SieveImmutableHeaders

- build-common.xml
- client/build.xml
- client/ivy.xml
- common/ivy.xml
- native/ivy.xml
- soap/build.xml
- soap/ivy.xml
- store/build.xml
- store/ivy.xml
The intention of this PR is to remove reliance on `ant-contrib` being externally installed on the system. 
The following was done:
- rewrite the ivy2 download section to not rely upon `antcontrib:if`
- add `antcontrib` to the `ivy.xml` files for each of the sub-projects
- add new target `taskdefs` which makes the `antcontrib` namespace available (although not without the namespacing)
- update all targets that use `if` to depend on `taskdefs` and to prefix use of `if` with `antcontrib:`
- move propertyregex statements inside the target that requires them so as to utilize the `taskdefs` dependency along with adding the `antcontrib:` prefix.
**Verification:**
`zm-build/build.pl` verification was done along with an install of the resulting installer.
Also ran all of the various targets that …
> ZCS-2462 - Build script improvements

- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigrationUtil.java
When invoking `zmmigrateattrs` with an explicit list of attributes, the last attribute was being ignored due to an off-by-one error. If only a single attribute was specified, this would result in nothing being migrated.
> ZCS-2524: fixed off-by-one error when parsing CLI args

- store/src/java/com/zimbra/cs/account/callback/EphemeralBackendCheck.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigration.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/ZimbraMigrationInfo.java
The _AttributeMigration::clearConfigCacheOnAllServers_ method is used for two distinct use cases: when updating attribute migration status, and when changing _zimbraEphemeralBackendURL_. Currently, the method tries to register the admin auth token used to issue `X-ZIMBRA-FLUSHCACHE` in the previous ephemeral store; however, this is only necessary when changing the ephemeral backend. If _zimbraPreviousEphemeralBackendURL_ is unset, which can happen when this method is called during migration, the method is unable to instantiate the ephemeral store, logs an error, and doesn't flush imapd caches. This should not happen if we are calling this method during the migration process, since registering the auth token in the previous store is unnecessary.
This fix updates this method with a new …
> ZMS-708: Fix for error logged when clearing imapd cache

- store/src/java/com/zimbra/cs/imap/ImapProxy.java
- store/src/java/com/zimbra/qa/unittest/ImapTestBase.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaImapDaemon.java
* `ImapProxy` now looks to see if remote IMAP server is enabled if IMAP
server is disabled.
* `ImapTestBase` now saves and restores settings of
`ZimbraImapServerEnabled` and `ZimbraImapSSLServerEnabled` on the
local Server
* `TestImapViaImapDaemon` now disables `ZimbraImapServerEnabled`
and `ZimbraImapSSLServerEnabled` on the local Server during its run to
ensure that ImapProxy is exercised with remote IMAP.
> ZCS-2586:ImapProxy fails when using IMAP Daemon

- store/src/java/com/zimbra/qa/unittest/ImapTestBase.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaEmbeddedRemote.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaImapDaemon.java
Just test changes for now.  The test fails for embedded remote (though curiously, not for the Imap Daemon - at least for me) so disabled for that.
> ZCS-1855 Exploring notifications on shared folders

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
This is the result of a research spike ZMS-713. The goal of the research was to figure out why some IMAP compliance tests are failing only when being executed in a sequence. The Compliance test suite is complaining about wrong UIDVALIDITY value that is being sent by one of the 3 connections used by the test. The reason why Remote IMAP is sending the wrong value is that ImapListener does not pick up folder deletion when IMAP session is not in a selected state and a folder with the same name is created by another connection.
> ZMS-713: add failing SOAP test for the underlying problem

- build.xml
- pkg-builder.pl
- Zimbra's Jetty Distribution (9.3.5.v20151012) is installed in /opt/zimbra/common/jetty_home/ via a separate package.
- Zimbra specific webapps and other custom jetty configuration files will be installed in /opt/zimbra/jetty_base/.
- Now /opt/zimbra/mailboxd and /opt/zimbra/jetty are symbolic links that point to /opt/zimbra/jetty_base/.
> WIP: ZCS:2486 - Separated jetty.base and jetty.home, removed jetty-<version>

- store/src/java-test/com/zimbra/cs/filter/AddressTest.java
- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/HeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/EditHeaderExtension.java
- store/src/java/com/zimbra/cs/filter/jsieve/HeaderTest.java
[bug]
The way of handling the error case regarding the ":matches"
operation has been altered, any mal-encoded value cancels
the filter execution with UnsupportedEncodingException,
and the message is delivered to the Inbox.
Previously, when the header value was mal-encoded, the
:matches compared the "key" to the header value "as is"
(the encoded value).
[root cause]
Each header value is decoded and unfolded before the match
operation is attempted.  When MimeUtility.decodeText() tries
to decode the header value, and if it finds that the given
value is mal-encoded, it throws the UnsupportedEncodingException.
In reality, as the header would contain the un-decodable
value, it is totally fine to ignore such exception.
This issue affects:
* header test
* address test
* addheader action
* …
> zcs-2473:Sieve filter's error handling about :matches

- store/src/java-test/com/zimbra/cs/filter/AddHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/AddHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/ReplaceHeader.java
- store/src/java/com/zimbra/cs/mime/MimeUtil.java
[Bug]
Performing replaceheader to the header with encoded line-breaks may break the message structure.  When the replaceheader generates the following style of the header, any undesired headers may be added or the MIME structure of the resulting message may be broken.
The resulting header value after replaceheader...
- contains one or more than one line break characters (0x0A or 0x0D)
- consists of only printable US-ASCII characters (0x21 - 0x7E), space (0x20), or tab (0x09)
- the first character of the second line or later starts at the beginning of the line.
[Fix]
If the modified header value meets the following condition, that modified header value will be Base64 encoded:
- the text consists of only 0x21 - 0x7E, 0x20, 0x09, 0x0A, and 0x0D
- the 0x0A and/or 0x0D is in the middle of the …
> zcs-2520:replaceheader may break the message structure

- common/src/java-test/com/zimbra/common/zmime/ZMimeBodyPartTest.java
- common/src/java/com/zimbra/common/zmime/ZMimeBodyPart.java
- store/src/java-test/com/zimbra/cs/filter/RedirectCopyTest.java
- store/src/java/com/zimbra/cs/mime/Mime.java
[Problem]
Currently when the mail server receives the SendMsg request
whose message's mime parts have following characteristics,
the mail server transfers the outgoing message to the SMTP
server with the header "Content-Transfer-Encoding: binary".
- If that mime part is not an attachment or its Content-Type's primary type is "text".
- If that mime part contains non-ASCII characters more than 25% of the part size.
- If that mime part has a line which is longer than MAX_LINE_OCTETS (900).
Because the MTA (Postfix) does not support the "Content-
Transfer-Encoding: binary", Postfix treats such mime part as
"7bit", and folds a long line into 998 characters without
consideration of multi-byte characters.  As a result, the
multi-byte character which CRLF is inserted in the middle of
the …
> ZCS-1870:Multi-byte text in a long line gets garbled

- store/src/java-test/com/zimbra/cs/filter/AddressTest.java
- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/EnvelopeTest.java
- store/src/java-test/com/zimbra/cs/filter/HeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/SetVariableTest.java
Fixed unit tests
- Added capability strings in "require".
- Fixed mal-formatted script, and initialized the filter setting so that the filter can be tested successfully regardless of the executing order.
> ZCS-1858(3):declare extension in "require" command, Part 2

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
- store/src/java/com/zimbra/cs/account/callback/ContactBackupFeature.java
Problem : Add 2 LDAP attributes for Contacts backup functionality
Fix : Added 2 LDAP attributes zimbraFeatureContactBackupFrequecy and zimbraFeatureContactBackupLifeTime with callback skeleton.
Testing done : Local dev environment build is successful.
(1)
zmprov desc -a zimbraFeatureContactBackupFrequecy
zimbraFeatureContactBackupFrequecy
Sleep time between subsequent contact backups. 0 means that contact
backup is disabled. . Must be in valid duration format:
{digits}{time-unit}. digits: 0-9, time-unit: [hmsd]|ms. h - hours, m -
minutes, s - seconds, d - days, ms - milliseconds. If time unit is not
specified, the default is s(seconds).
type : duration
value : 
callback : ContactBackupFeature
immutable : false
cardinality : single
requiredIn : 
optionalIn : server,globalConfig
flags : …
> ZCS-2728 : Add 2 LDAP attributes for Contacts backup functionality

- store/src/java-test/com/zimbra/cs/filter/AddressTest.java
- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/EnvelopeTest.java
- store/src/java-test/com/zimbra/cs/filter/HeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/MimeHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/SetVariableTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/AddressTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/BodyTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/DeleteHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/EnvelopeTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/HeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/MimeHeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/ReplaceHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/StringTest.java
Additional fixes for the following Sieve commands without comparator-i;ascii-numeric.
* header test with no match type (implicit :is)
* address test with no match type (implicit :is)
* envelope test with no match type (implicit :is)
* deleteheader
* replaceheader
* mime_header (Zimbra special)
* body (Zimbra special)
And "string" test needs to check the "variables" capability in the require list.
> ZCS-1858(4):declare extension in "require" command, Part 2

- store/src/java-test/com/zimbra/cs/filter/DeleteHeaderTest.java
- store/src/java-test/com/zimbra/cs/filter/ReplaceHeaderTest.java
- store/src/java/com/zimbra/cs/filter/jsieve/EditHeaderExtension.java
Sieve:ReplaceHeader:Match pattern containing more than four backslashes leads to incorrect behaviour
[Problem]
When the match pattern contains four or more than four
backslashes in a row, replaceheader matches does not match correctly.
[Root cause]
The replaceheader and deleteheader call the com.zimbra.cs.filter.jsieve.EditHeaderExtension.matchValue() which makes a matching pattern using jsieve's org.apache.jsieve.comparators.ComparatorUtils.sieveToJavaRegex() method, but this method had a bug.  Other tests, such as header or address, have already used the fixed version of com.zimbra.cs.filter.FilterUtil.sieveToJavaRegex(), but replaceheader and deleteheader did not yet.
[Fix]
Call the fixed version of sieveToJavaRegex() method from replaceheader and deleteheader.
> zcs-2212:Inconsistent handling of "\" in editheader

- client/src/java/com/zimbra/client/ZMailbox.java
- store/src/java/com/zimbra/qa/unittest/server/TestDataSourceServer.java
Added getDataSourceByName, so that oauth service can check if a datasource for specific target already exists and update it if needed.
> add getDataSourceByName to ZMailbox

- common/src/java/com/zimbra/common/httpclient/ZimbraHttpClientManager.java
LocalConfig parameters for external HTTP connections (connections from Zimbra to other services) are different from those for internal connections (connections between Zimbra components), so need a separate instance of HttpClient and a separate connection manager for external connections. This is similar to com.zimbra.common.util.ZimbraHttpConnectionManager, which uses Apache Commons.
> add external client instance to ZimbraHttpClientManager

- client/src/java/com/zimbra/client/ZMailbox.java
- store/src/java/com/zimbra/cs/dav/DavContext.java
- store/src/java/com/zimbra/cs/dav/resource/MailItemResource.java
- store/src/java/com/zimbra/cs/dav/resource/RemoteCollection.java
- store/src/java/com/zimbra/cs/filter/FilterUtil.java
- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/calendar/cache/CtagInfoCache.java
- store/src/java/com/zimbra/cs/service/mail/GetMiniCal.java
- store/src/java/com/zimbra/cs/service/mail/ItemAction.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/cs/service/mail/Search.java
- store/src/java/com/zimbra/cs/service/mail/SendInviteReply.java
- store/src/java/com/zimbra/qa/unittest/TestZClient.java
PERM_DENIED spam in mailbox.log as a result of ZMailbox calling GetInfoRequest when it doesn't have the capabilities for that API to get the account ID when authenticating as another user.
Essentially, store the account ID / account name (used for logging) when constructing ZMailbox if know them and know might not have perms to GetInfo
> ZCS-3016 zmailbox perm denied

- store/src/java/com/zimbra/cs/filter/RuleManager.java
[Bug]
Five test scripts are failed because of a bug introduced by the fix of zcs-168.  Any spammy message delivered to the user with empty filter rules was discarded.
[Root cause]
Originally when the triggering message was spammy, the Sieve filter is neither evaluated nor executed.  After the fix of zcs-168, the Sieve filter was indeed not evaluated and an empty action list was generated.  ZCS, however, mistakenly executed such empty action list; the empty action list meant that the message should be discarded.
[Fix]
When the message is spammy and the attribute 'zimbraSpamApplyUserFilters' is FALSE (default), ZCS will not evaluate and execute the filter rule.
--------
Unit test:
ant test-all --> PASS
(1) Automation test : 105 scripts listed in the automation_list.txt --> PASS …
> zcs-2915:Few mimes are discarded on LMTP inject

- store/src/java-test/com/zimbra/cs/filter/NotifyMailtoTest.java
- store/src/java/com/zimbra/cs/filter/FilterUtil.java
- store/src/java/com/zimbra/cs/filter/jsieve/NotifyMailto.java
Headers specified by mailto: URI should capitalize the first letter
[Problem]
The name of the URL headers specified in the "mailto:" parameter was
always lower-cased; RFC says the the first letter of the added header
name should be capitalized though.
[Fix]
* The name of the URL headers will be capitalized. Although the MIME
header name is defined as only ASCII character's string, if the
header name should consisted of non-ascii characters, the first
letter of the header name will not changed.
* Fixed an unit test case "testNotifyMethodCapability_OnlineYes":
It was failed because the filter string was not grammatically correct,
and it threw an exception.
----
[Unit test] ant test-all (note) --> PASS
[Automation script] The scripts under data/soapvalidator/MailClient/Filters/Sieve/ (97 …
> zcs-282:SIEVE:notify:Capitalize the header name

- build-common.xml
- common/ivy.xml
- common/src/java-test/com/zimbra/common/calendar/Ical4JTest.java
This change adds a test I created some time ago in P4 to validate that work to migrate to upstream ical4j doesn't lose fixes we applied in our fork.
This targets the develop branch as clearly these tests should work both with the old library and our new integration.
> ZCS-3092 ical4j test

- client/src/java/com/zimbra/client/ZMailbox.java
- soap/src/java/com/zimbra/soap/mail/message/TestDataSourceResponse.java
- soap/src/java/com/zimbra/soap/mail/type/TestDataSource.java
- store/src/java/com/zimbra/qa/unittest/TestDataSource.java
Jaxb classes for TestDataSourceResponse do not match what the response looks like and therefore ZMailbox::testDataSource does not properly report errors when DataImport::test method fails.
There was no test that validated ZMailbox::testDataSource for negative behavior - add this test.
This change is part of ZCS-2976, because this problem blocks me from creating fully tested Data Source implementation for ZCS-2976
> adjust Jaxb for TestDataSourceResponse, fix ZMailbox::testDataSource and add SOAP test

- common/src/java/com/zimbra/common/zclient/ZClientException.java
- store/src/java-test/com/zimbra/cs/imap/NioImapDecoderTest.java
- store/src/java/com/zimbra/cs/imap/AppendMessage.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/imap/ImapParseException.java
- store/src/java/com/zimbra/cs/imap/ImapRequest.java
- store/src/java/com/zimbra/cs/imap/ImapURL.java
- store/src/java/com/zimbra/cs/imap/NioImapDecoder.java
- store/src/java/com/zimbra/cs/imap/NioImapHandler.java
- store/src/java/com/zimbra/cs/imap/NioImapServer.java
- store/src/java/com/zimbra/cs/imap/TcpImapRequest.java
- store/src/java/com/zimbra/qa/unittest/ImapTestBase.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
Should see a consistent error message now between the IMAP server implementations.
Also, the NIO decoder should now pick up config changes dynamically instead of requiring a server restart.
> ZCS-1824 imap append max msg size

- store/src/java/com/zimbra/cs/mailbox/util/MetadataDump.java
- store/src/java/com/zimbra/cs/stats/ZimbraPerf.java
- store/src/java/com/zimbra/qa/unittest/TestMetadataDump.java
- store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
* ZimbraPerf - ignore attempt to add a callback if initialization not
done.
* MetadataDump - declare some stings in variables for re-use.
* TestMetadataDump - new tests which execute zmmetadump - hopefully will
help catch any breakage in the tool early in future.
* ZimbraSuite - add `TestMetadataDump`
> ZCS-3227:zmmetadump NPE

- store/src/java/com/zimbra/qa/unittest/ImapTestBase.java
- store/src/java/com/zimbra/qa/unittest/TestEmbeddedRemoteImapNotificationsViaMailbox.java
- store/src/java/com/zimbra/qa/unittest/TestEmbeddedRemoteImapNotificationsViaWaitsets.java
- store/src/java/com/zimbra/qa/unittest/TestImapDaemonNotifications.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaEmbeddedLocal.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaEmbeddedRemote.java
- store/src/java/com/zimbra/qa/unittest/TestImapViaImapDaemon.java
- store/src/java/com/zimbra/qa/unittest/TestLocalImapNotifications.java
- store/src/java/com/zimbra/qa/unittest/TestRemoteImapSoapSessions.java
Don't set 2 LDAP attributes that trigger zmconfigd to restart mailboxd - we don't actually need to set them!
Verified that with these changes, imap logging went to the appropriate log file (imapd.log or mailbox.log) depending on the test being executed.
> ZCS-3362 unstable RunUnitTestsRequests

- store/src/java-test/com/zimbra/cs/event/logger/EventLoggerTest.java
- store/src/java/com/zimbra/cs/datasource/MailItemImport.java
- store/src/java/com/zimbra/cs/event/Event.java
- store/src/java/com/zimbra/cs/filter/ExistingMessageHandler.java
- store/src/java/com/zimbra/cs/filter/FilterHandler.java
- store/src/java/com/zimbra/cs/filter/FilterUtil.java
- store/src/java/com/zimbra/cs/filter/IncomingMessageHandler.java
- store/src/java/com/zimbra/cs/filter/OutgoingMessageHandler.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/service/formatter/ArchiveFormatter.java
Logging a "received" event via _ReceivedMessageCallback_. This is triggered from _ArchiveFormatter_, _IncomingMessageHandler_, and _MailItemImport_.
As part of this change, I added a new _getMessageCallbackContext_ method to the _FilterHandler_ interface and ensured that the callback context is set for all FilterHandler call paths that add a message to the mailbox. _ExistingMessageHandler_ uses the default null value, so that no events are triggered when processing existing messages.
> ZIMBRA-117: received event logging

- common/src/java/com/zimbra/common/util/ZimbraLog.java
- store-conf/conf/log4j.properties.production
- store/src/java-test/com/zimbra/cs/event/logger/FileEventLoggerTest.java
- store/src/java/com/zimbra/cs/event/Event.java
- store/src/java/com/zimbra/cs/event/logger/FileEventLogHandler.java
- store/src/java/com/zimbra/cs/util/Zimbra.java
This is the default event logger that serializes events into a logfile. Events are logged to `opt/zimbra/log/event.log` with the same rollover configuration as the other logs.
This is done using a new `eventlog` logger category. This is distinct from the existing `event` category, which is used for general logging of the event system. 
The _EventFormatter_ class is used for serializing/deserializing an event object. The deserialization functionality will be used in the future for re-indexing events in solr.
> ZIMBRA-121: File event logger

- common/src/java/com/zimbra/common/localconfig/LC.java
The Zimbra `cbpolicyd` creates the rather generically named cache file `/opt/zimbra/data/cache`.  It took me a while to find out where that file came from when I wanted to create a directory with the same name there (which we use for our scripts).
This patch changes the default filename to `/opt/zimbra/data/cbpolicyd/cbpolicyd.cache`.
The file is deleted and recreated on each restart of `cbpolicyd` so no further cleanup is required.
> Bug 105959: Change default value of cbpolicyd_cache_file

- store/src/java/com/zimbra/cs/service/UserServlet.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
* UserServlet - For remote IMAP, was using UserServlet GET specifying
"imap_id".  The formatter requires `context.target` to have a value
and this wasn't being setup under these circumstances.  Now set it up.
* New tests which exercise CATENATE with URLs which reference messages
in shared folders.
> ZCS-3010:IMAP APPEND CATENATE with URL broken

- store/src/java-test/com/zimbra/cs/filter/ZimbraMailAdapterTest.java
- store/src/java-test/com/zimbra/cs/store/MockStoreManager.java
- store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
- store/src/java/com/zimbra/cs/mailbox/DeliveryContext.java
- store/src/java/com/zimbra/cs/store/Blob.java
Case 00633040: CNCI/IIJ - Blob file created by editheader
is remained undeleted under the incoming directory.
[Bug]
When the message is delivered to only one recipient who has a
sieve filter rule of edit header action(s), the intermediate
blob files are left undeleted under the incoming directory
/opt/zimbra/store/incoming for ever.
(If the message is delivered to two or more than two recipients,
and one of them has an editheader filter rule, no intermediate
blob files are remained)
If multiple recipients are specified in the triggering message,
and if at least one of them has a sieve filter of edit header
action, then the message will be cloned so that the edit header
action can manipulate the message without any side effect to
other recipients' message.  The first edit header action …
> zcs-3263:sieve:undeleted blob by editheader action

- store/build.xml
Realized that the packaging for `zimbra-mbox-war` was still dropping in some obsoleted JAR files.  About the `lucene-smartcn` dependency. Not sure this is still needed.  Ilya and I talked about this earlier.  
Everything builds fine without it.  Will continue to test and can re-add this if necessary.  There is the following comment at the top of this section of the file:
delete anything that may have been left over, e.g.: older versions of same libs
So this may be something that is no longer needed.  With the older JAR files still in place it breaks certain functions, such as autocomplete.
> ZIMBRA-863 Updated war packaging

- build-common.xml
- store/src/java-test/com/zimbra/cs/store/MockStoreManager.java
- store/src/java/com/zimbra/cs/mailbox/DeliveryContext.java
- store/src/java/com/zimbra/cs/store/Blob.java
[Problem]
Unit test com.zimbra.cs.filter.DeleteHeaderTest failed.
[Root cause]
The unit test uses the MockBlob object to keep not only
the blob data, like other real-world Blob object, but also
its message data itself (the member parameter "content").
The MockBlob didn't copy the "content", so the old contents
remained.
[Fix]
Added the Blob.copy() method to perform a deep copy.
The child class of the MockBlob.copy() will copy the data
of the "content" as well.
[Unit test]
ant test-all --> PASS
> zcs-3585,3558,3559:Unit test DeleteHeaderTest failed

- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigrationUtil.java
* Make it clear that for most things, URL is required by
adding a footer to the usage message
* Fix minor typo in log message
New usage message:
usage: zmmigrateattrs [options] [URL] [attr1 attr2 attr3 ...]
-a,--account <arg>      Comma-separated list of accounts to migrate. If not
specified, all accounts will be migrated
-c,--clear              Clear the migration info
-d,--debug              Enable debug logging
-h,--help               Display this help message
-n,--num-threads <arg>  Number of threads to use in the migration. If not set,
defaults to 1
-r,--dry-run            Dry run: display info on what the migration would
accomplish
-s,--status             Show migration status
'URL' MUST be provided for all options except for:
'--clear' (-c) and '--status' (-s)
> ZCS-3365:more help on URL in usage

- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/mailbox/MailboxStore.java
- common/src/java/com/zimbra/common/soap/MailConstants.java
- store/src/java-test/com/zimbra/cs/event/logger/EventLoggerTest.java
- store/src/java-test/com/zimbra/cs/event/logger/SolrEventLoggerTest.java
- store/src/java/com/zimbra/cs/datasource/MailItemImport.java
- store/src/java/com/zimbra/cs/event/Event.java
- store/src/java/com/zimbra/cs/event/SolrCloudEventStore.java
- store/src/java/com/zimbra/cs/event/logger/EventLogger.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/mailbox/Chat.java
- store/src/java/com/zimbra/cs/mailbox/DeliveryOptions.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/Message.java
- store/src/java/com/zimbra/cs/mailbox/MessageCallbackContext.java
- store/src/java/com/zimbra/cs/mailbox/Metadata.java
- store/src/java/com/zimbra/cs/service/mail/ItemAction.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/cs/service/mail/Search.java
- store/src/java/com/zimbra/cs/session/SoapSession.java
This PR introduces three new message event types: `SEEN`, `READ` and `REPLIED`. The purpose of these events is to enable calculation of useful contact-level metrics such as the email open rate and average reply time.
The event state is stored in message metadata using the new `EventFlag` enum. A new message is instantiated as `not_seen`; the new method `Message:advanceEventFlag` is used to advance the event flag through the other states. The events must be triggered in order: a `SEEN` event can only be triggered for a message that has an internal event flag of `not_seen`; a `READ` event can only be triggered for a `seen` event, etc. This event flag metadata field also insures that only one event of each category is logged per message.
In addition to the EventFlag metadata field, several …
> ZIMBRA-112: SEEN/READ/REPLIED Events

- store/src/java/com/zimbra/cs/redolog/util/PlaybackUtil.java
The 'setup' call initializes all the underlying subsystems which cause the EHCache lock subsystem to hang.
There is no need to execute this before processing the command-line arguments.
Moving the location of the 'setup' call to after the processing of the command-line arguments avoids a thread-lock which was seen when running the `zmplayredo -h` command.
> ZCS-3785 move setup call after commandline processing

- store/src/java-test/com/zimbra/cs/mailbox/calendar/Calendar_ChangeMeetingRequest_WO_Rsvp.txt
- store/src/java-test/com/zimbra/cs/mailbox/calendar/Calendar_NewMeetingRequest_RsvpFalse.txt
- store/src/java-test/com/zimbra/cs/mailbox/calendar/Calendar_NewMeetingRequest_RsvpTrue.txt
- store/src/java-test/com/zimbra/cs/mailbox/calendar/ZAttendeeTest.java
- store/src/java/com/zimbra/cs/mailbox/CalendarItem.java
- store/src/java/com/zimbra/cs/mailbox/calendar/Invite.java
- store/src/java/com/zimbra/cs/mailbox/calendar/ZAttendee.java
- store/src/java/com/zimbra/cs/service/mail/SendInviteReply.java
- store/src/java/com/zimbra/cs/service/mail/ToXML.java
[Bug]
Organizer sees the attendee's status as Tentative instead of Accepted
even when the attendee proposed a new time in invite and the organizer
accepted it.
[Root cause]
In general, the RSVP info is not conveyed along with the communications
between the organizer and attendee(s) after the CreateAppointmentRequest.
When an attendee sent a "New Time Proposed" email (generated by the
CounterAppointmentRequest), the organizer accepted by the
ModifyAppointmentRequest and sent another email to the attendees, but
this modified invitation did not contain the RSVP info (because organizer
didn't change the RSVP status); and attendee did not send back the acceptance
email based on it.
Correctly, when the invitation email does not contains the RSVP info, if the
attendee has received the invitation …
> ZCS-3456: Attendee's status isn't updated

- store/build.xml
- store/ivy.xml
ZCS-3809
Adding new libs required by JWT
Maintaining both versions of jackson library for now, so that JWT build can be created
Will create a separate bug to switch to new jackson library and fix compilation and junit  failures in soap
New bug opened for 3840 opened for this.
> ZCS-3809 Adding new libs required by JWT

- store/src/java/com/zimbra/cs/ephemeral/migrate/AttributeMigration.java
- store/src/java/com/zimbra/cs/ephemeral/migrate/ShutdownHook.java
Update zmmigrateattrs to utilize a 'Shutdown-hook' such that when the JVM is exiting it can decide if it was successful or failed in the conversion process.
This enables the utility to output the appropriate message before fully exiting.
>  ZCS-2191 handle ctrl-c gracefully

- client/src/java/com/zimbra/client/ZMailbox.java
- client/src/java/com/zimbra/client/ZSmartFolder.java
- client/src/java/com/zimbra/client/ZTag.java
- client/src/java/com/zimbra/client/ZTagInfo.java
- client/src/java/com/zimbra/client/event/ZCreateSmartFolderEvent.java
- client/src/java/com/zimbra/client/event/ZModifySmartFolderEvent.java
- client/src/java/com/zimbra/client/event/ZRefreshEvent.java
- common/src/java/com/zimbra/common/mailbox/MailItemType.java
- common/src/java/com/zimbra/common/soap/MailConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/mail/message/GetSmartFoldersRequest.java
- soap/src/java/com/zimbra/soap/mail/message/GetSmartFoldersResponse.java
- store/src/java-test/com/zimbra/cs/mailbox/SmartFolderTest.java
- store/src/java/com/zimbra/cs/index/DBQueryOperation.java
- store/src/java/com/zimbra/cs/mailbox/Folder.java
- store/src/java/com/zimbra/cs/mailbox/MailItem.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/MailboxOperation.java
- store/src/java/com/zimbra/cs/mailbox/SmartFolder.java
- store/src/java/com/zimbra/cs/mailbox/SmartFolderProvider.java
- store/src/java/com/zimbra/cs/mailbox/Tag.java
- store/src/java/com/zimbra/cs/redolog/op/CreateSmartFolder.java
- store/src/java/com/zimbra/cs/service/formatter/ArchiveFormatter.java
- store/src/java/com/zimbra/cs/service/mail/GetSmartFolders.java
- store/src/java/com/zimbra/cs/service/mail/MailService.java
- store/src/java/com/zimbra/cs/service/mail/Sync.java
- store/src/java/com/zimbra/cs/service/mail/ToXML.java
- store/src/java/com/zimbra/cs/zclient/ZMailboxUtil.java
- store/src/java/com/zimbra/qa/unittest/TestSmartFolders.java
- store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
Upcoming NextGen work requires the server to use machine learning to classify incoming emails into one or more configurable "smart folders", such as `important`, `social`, or `finance`.  This makes a smart folder very similar to tag, with the difference being that the tagging is performed by the server instead of by the client.
`SmartFolder` subclasses `Tag` to enable us to take advantage of the existing tagging infrastructure. To avoid potential name collisions between smart folders and user-created tags, the internal tag corresponding to a smart folder has its name prefixed with two backslashes `\\`. This places smart folders into the namespace carved out for Flags, which begin with a single backslash. The method `SmartFolder.getSmartFolderName()` returns the "external" name which does …
> ZIMBRA-131: SmartFolder functionality

- store/src/java/com/zimbra/cs/imap/ImapDaemon.java
Currently this emits a 'WARNING' level message if the extension is not found but continues loading in the case of FOSS and causes the appropriate 'ALERT' to be sent to an IMAP client connecting to the IMAPD when the license is bad / expired.
The rules for the alert appearance are the same as the internal imap server since it is using the same code and mechanism.
IMAPD
telnet localhost 8143
Trying ::1...
Connected to localhost.
Escape character is '^]'.
* OK zcs-dev-testbed.dev Zimbra IMAP4rev1 server ready
* OK [ALERT] Your mail server's license is missing, invalid or expired.
Mailbox / IMAP
telnet localhost 7143
Trying ::1...
Connected to localhost.
Escape character is '^]'.
* OK zcs-dev-testbed.dev Zimbra IMAP4rev1 server ready
* OK [ALERT] Your mail server's license is missing, invalid …
> ZCS-2518 initialize LicenseExtension in ImapDaemon

- store/src/java-test/com/zimbra/cs/event/analytics/EventMetricTest.java
- store/src/java-test/com/zimbra/cs/mailbox/SmartFolderTest.java
- store/src/java/com/zimbra/cs/event/EventStore.java
- store/src/java/com/zimbra/cs/event/SolrEventStore.java
- store/src/java/com/zimbra/cs/event/StandaloneSolrEventStore.java
- store/src/java/com/zimbra/cs/event/analytics/AccountEventMetrics.java
- store/src/java/com/zimbra/cs/event/analytics/ContactFrequencyMetric.java
- store/src/java/com/zimbra/cs/event/analytics/EventDifferenceMetric.java
- store/src/java/com/zimbra/cs/event/analytics/EventMetric.java
- store/src/java/com/zimbra/cs/event/analytics/EventMetricManager.java
- store/src/java/com/zimbra/cs/event/analytics/EventRatioMetric.java
- store/src/java/com/zimbra/cs/event/analytics/IncrementableMetric.java
- store/src/java/com/zimbra/cs/event/analytics/RatioMetric.java
- store/src/java/com/zimbra/cs/event/analytics/TimeDeltaMetric.java
- store/src/java/com/zimbra/cs/event/analytics/ValueMetric.java
- store/src/java/com/zimbra/cs/event/analytics/contact/ContactAnalytics.java
- store/src/java/com/zimbra/cs/event/logger/EventLogger.java
- store/src/java/com/zimbra/cs/event/logger/EventMetricCallback.java
- store/src/java/com/zimbra/cs/event/logger/EventMetricUpdateFactory.java
- store/src/java/com/zimbra/cs/util/Zimbra.java
- store/src/java/com/zimbra/qa/unittest/SolrEventStoreTestBase.java
- store/src/java/com/zimbra/qa/unittest/TestSolrCloudEventStore.java
Adding machine learning to ZCS requires the ability to generate features to be used as inputs to classifiers. One important category of features are those calculated from event data to drive "important email" classification, such as sender contact frequency, read rate, or reply rate. Since these features potentially need to be generated for each incoming message, the mailbox server needs to be able to efficiently calculate this data without issuing a Solr query every time, which may be prohibitively expensive.
To enable event-driven ML features described above, This PR introduces the concept of  an `EventMetric`, which is an in-memory representation of some calculation derived from event data, which can be incrementally updated by the event stream. 
This code relies heavily on generics. …
> ZIMBRA-129: In-Memory Event Metrics

- common/src/java/com/zimbra/common/util/ZimbraLog.java
- store/src/java-test/com/zimbra/cs/ml/feature/FeatureFactoryTest.java
- store/src/java/com/zimbra/cs/event/Event.java
- store/src/java/com/zimbra/cs/mailbox/Message.java
- store/src/java/com/zimbra/cs/ml/Classifiable.java
- store/src/java/com/zimbra/cs/ml/feature/ComputedFeatures.java
- store/src/java/com/zimbra/cs/ml/feature/ContactFrequencyFeatureFactory.java
- store/src/java/com/zimbra/cs/ml/feature/ConversationFeatureFactory.java
- store/src/java/com/zimbra/cs/ml/feature/EventRatioFeatureFactory.java
- store/src/java/com/zimbra/cs/ml/feature/EventTimeDeltaFeatureFactory.java
- store/src/java/com/zimbra/cs/ml/feature/Feature.java
- store/src/java/com/zimbra/cs/ml/feature/FeatureFactory.java
- store/src/java/com/zimbra/cs/ml/feature/FeatureParam.java
- store/src/java/com/zimbra/cs/ml/feature/FeatureParams.java
- store/src/java/com/zimbra/cs/ml/feature/FeatureSet.java
- store/src/java/com/zimbra/cs/ml/feature/FeatureSpec.java
- store/src/java/com/zimbra/cs/ml/feature/MetricFeature.java
- store/src/java/com/zimbra/cs/ml/feature/NumRecipientsFeatureFactory.java
- store/src/java/com/zimbra/cs/ml/feature/PrimitiveFeature.java
- store/src/java/com/zimbra/cs/ml/feature/RatioFeature.java
- store/src/java/com/zimbra/cs/ml/feature/RecipientFieldFeatureFactory.java
This PR builds on the event metric work from #ZIMBRA-129 to introduce classifier feature management. This is a direct prerequisite to adding the concept of "Classifiers" to ZCS.
In machine learning, a _feature_ is some measurable property of the object to be classified. A set of features is the input into a classifier at both the training and classification steps.
For email classification, we need to be able to generate a wide variety of features. Some are event-driven, representing some metric related to the sender of the email. Others are properties of the message itself - how many recipients it has, whether it's part of a conversation, etc.
It should be noted that while content-based features such as subject and body words will certainly be used for classification, the task of parsing …
> ZIMBRA-132: Feature Generation for Machine Learning

- store/src/java/com/zimbra/soap/SoapEngine.java
Although individual SOAP requests are logged, the system administrator
can't see which SOAP requests are submitted along with the BatchRequest.
It is useful for the user support purpose to get the list of the real
"handleable" requests in the BatchRequest.
Changed the existing log text to display the list of the SOAP requests
under the BatchRequest.
> ZCS-3888:Better SOAP BatchRequest log

- store/src/java/com/zimbra/cs/imap/ImapListener.java
This ticket covered updating the `updateAccessTime` method.  Found a second method (`reload`) that needed the same update.
> ZCS-4004 - ensure mailbox not modified by another thread

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/ml/classifier/ClassifierManagerTest.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/ml/ClassificationExecutionContext.java
- store/src/java/com/zimbra/cs/ml/ClassificationHandler.java
- store/src/java/com/zimbra/cs/ml/ClassificationTask.java
- store/src/java/com/zimbra/cs/ml/ClassificationTaskConfigProvider.java
- store/src/java/com/zimbra/cs/ml/LdapClassificationTaskConfigProvider.java
- store/src/java/com/zimbra/cs/ml/callback/ClassificationCallback.java
- store/src/java/com/zimbra/cs/ml/callback/ExclusiveClassCallback.java
- store/src/java/com/zimbra/cs/ml/callback/OverlappingClassCallback.java
- store/src/java/com/zimbra/cs/ml/classifier/ClassifierManager.java
This PR builds on ZIMBRA-130 to introduce the concept of a _Classification Task_ to the mailbox.
A `ClassificationTask` represents some piece of mailbox functionality that is powered by machine learning; for example, tagging emails with SmartFolders. This task can then be _assigned_ a classifier, at runtime, to power it. Classifier development is an iterative process, requiring experimentation with feature engineering and hyper-parameter tuning; this mechanism allows for classifiers to be "plugging in" without any changes to the mailbox code.
`ClassificationTask` has two subclasses: `BinaryClassificationTask` and` MultilabelClassificationTask`.
The difference between them is that a multi-label task _must_ be handled by exclusive class labels, while a binary task can be handled by either …
> ZIMBRA-133: Classification Tasks

- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/soap/MailConstants.java
- soap/src/java/com/zimbra/soap/mail/message/GetContactFrequencyRequest.java
- soap/src/java/com/zimbra/soap/mail/type/ContactFrequencyData.java
- soap/src/java/com/zimbra/soap/mail/type/ContactFrequencyGraphSpec.java
- store/src/java/com/zimbra/cs/event/EventStore.java
- store/src/java/com/zimbra/cs/event/SolrEventStore.java
- store/src/java/com/zimbra/cs/event/analytics/contact/ContactAnalytics.java
- store/src/java/com/zimbra/cs/service/mail/GetContactFrequency.java
- store/src/java/com/zimbra/cs/zclient/ZMailboxUtil.java
- store/src/java/com/zimbra/qa/unittest/SolrEventStoreTestBase.java
- store/src/java/com/zimbra/qa/unittest/TestSolrCloudEventStore.java
- store/src/java/com/zimbra/qa/unittest/TestStandaloneSolrEventStore.java
This PR changes the contact frequency graph API to allow clients to specify arbitrary range start times.
Previously, the client could only specify a combination of "d", "w", or "m" flags:
- "d" returned the current month in day increments
- "w" returned the last 6 months in week increments
- "m" returned the _current_ year in month increments
This has been updated so that the client can specify one or more `spec` request elements, each consisting of:
- A `range` string,  in the format `#(d|w|m)`; for example, "30d" or "25w".
- An `interval`, which can be one of `d|day|w|week`. Note that aggregations by month are no longer supported. 
Given N time units (day, week, or month), the graph range will encompass N _complete_ units, as well as part of the current unit. In other words, requesting …
> ZCS-4007: Contact Frequency Changes

- store/src/java/com/zimbra/cs/mailclient/MailConnection.java
Update the code to catch the SSL related certificate exceptions and create a new
IOException that contains a more user-friendly message such that the end user isn't
shown a message that is meaningless. The message shown to the user should empower them
to inform the administrator of their server that their SSL certificate is invalid.
Messages shown to user:
Encrypted connection: Encrypted connection failed. Please check the SSL certificate on the external server
STARTTLS: STARTTLS failed. Please check the SSL certificate on the external server.
> ZCS-3663 more user friendly SSL error messages for external accounts

- store/src/java/com/zimbra/cs/service/account/GetDistributionListMembers.java
- store/src/java/com/zimbra/cs/service/admin/AdminDocumentHandler.java
- store/src/java/com/zimbra/cs/service/mail/OpenImapFolder.java
- store/src/java/com/zimbra/soap/DocumentHandler.java
[Problem]
When the SOAP request is proxied to another server (the account's zimbraMailHost server), ZCS does not log about the proxying information, such as "the request is proxying to which server".
When the ISP operator is tracking down the SOAP request, usually in the course of the trouble shooting around the account provisioning operation etc., they always have a hard time figuring out which SOAP request is proxied to where. If the information about the account name and the target proxying server along with the SOAP request path, it would be much easier for the operator to analyze the issue, provisioning issues.
[Fix]
"Proxying ..." event is now always logged in INFO level.
[Manual test]
* ModifyAccountRequest (admin level SOAP reqeust)
2018-02-01 17:01:38,483 INFO …
> ZCS-3886:Log about proxying requests to other MBS

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/imap/NioImapHandler.java
- store/src/java/com/zimbra/cs/pop3/NioPop3Handler.java
- store/src/java/com/zimbra/cs/pop3/Pop3Handler.java
POP3 and IMAP threads are NIO threads.
If the same user accesses via multiple POP3 or IMAP sessions from same
client host (IP), it is impossible to tell which connection is which
POP/IMAP operation.
This fix displays the connection id along with the existing log event
for POP3 and IMAP operations.
[Manual test result]
IMAP4 - accessed from two consoles on the same IP (192.168.59.1) to the same account (admin@synacorjapan.com).   "cid=2" and "cid=3" were logged.
```
2018-02-07 21:13:20,639 INFO  [ImapServer-0] [name=admin@synacorjapan.com;ip=192.168.59.1;cid=2;] imap - user admin@synacorjapan.com authenticated, mechanism=LOGIN
2018-02-07 21:13:20,641 INFO  [ImapServer-0] [name=admin@synacorjapan.com;ip=192.168.59.1;cid=2;] imap - LOGIN elapsed=90
2018-02-07 21:13:51,342 INFO …
```
> ZCS-3885:Add connection id for POP3/IMAP log event

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/service/ModifyPrefsTest.java
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
Zimbra NextGen supports a year view for calendar, which is stored
under the user preference zimbraPrefCalendarInitialView.
Currently zimbraPrefCalendarInitialView supports: day,week,workWeek,month,list,
we need to add "year" enum to this list.
[manual test]
Before fix
```
$ zmprov desc -a zimbraPrefCalendarInitialView
zimbraPrefCalendarInitialView
initial calendar view to use
type : enum
value : day,week,workWeek,month,list
callback : 
immutable : false
cardinality : single
requiredIn : 
optionalIn : cos,account
flags : accountInherited,domainAdminModifiable
defaults : workWeek
min : 
max : 
id : 240
requiresRestart : 
since : 
deprecatedSince : 
```
After fix
```
$ zmprov desc -a zimbraPrefCalendarInitialView
zimbraPrefCalendarInitialView
initial calendar view to use
type : enum
value : …
```
> ZCS-3892:Add year enum to zimbraPrefCalendarInitialView

- store/src/java/com/zimbra/cs/imap/ImapMailboxStore.java
- store/src/java/com/zimbra/cs/imap/LocalImapMailboxStore.java
- store/src/java/com/zimbra/cs/imap/RemoteImapMailboxStore.java
- store/src/java/com/zimbra/qa/unittest/SharedImapNotificationTests.java
These are the two commits from the ZCS-4221 hotfix for 8.8.6GA.  They need to be integrated into `develop`.  Unit tests and all IMAP-related SOAP tests pass.
> bugfix/ZCS-4221 Forward-port fixes from the 8.8.6 hotfix

- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/mailbox/Notification.java
- store/src/java/com/zimbra/cs/service/mail/SendDeliveryReport.java
Handling additional cases that the messages is sent automatically
when the end user sends a message via Web Client.
- User-specified notification message (it is not the one which is supported by the Sieve filter, but the legacy non-conditional notification feature)
- Delivery report message (it is not exactly triggered by SendMsgRequest, but still this is sent from the Web client at his/her own will).
[Manual Test]
Notification message
```
smtp - Sending message to MTA at mail.synacorjapan.com: Message-ID=<1342530317.85.1518698157119.JavaMail.zimbra@mail.synacorjapan.com>, origMsgId=400, sender=user2@synacorjapan.com, nrcpts=1, to=admin@synacorjapan.com, reason=notify
```
Delivery Report message
```
smtp - Sending message to MTA at mail.synacorjapan.com: …
```
> ZCS-3887-2:Enhancement of SMTP log format

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
[Adding feature]
- If zimbraPrefDisplayTimeInMailList is TRUE, web client displays not only date but also time of a message received yesterday or before in email list.
- Adding a setting in Preferences -> Mail tab
[Related]
- Jira ticket id: NICPS-30
- Pull requests:
https://github.com/Zimbra/zm-ajax/pull/46
https://github.com/Zimbra/zm-web-client/pull/227
> Bugzilla-77129: added zimbraPrefDisplayTimeInMailList

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
Problem : display received/sent time of all messages in email list. Before the fix, only (year/)month/day is shown if the message was received yesterday or before.
Fix : 
- added new attribute: zimbraPrefDisplayTimeInMailList
- If zimbraPrefDisplayTimeInMailList is TRUE, web client displays not only date but also time of a message received yesterday or before in email list.
Testing done : testing done by developer.
Testing to be done by QA: testing needed to be done by QA
Link:
- Set of PRs : https://github.com/Zimbra/zm-ajax/pull/47, https://github.com/Zimbra/zm-web-client/pull/231, https://github.com/Zimbra/zm-mailbox/pull/525
- RP to develop branch: https://github.com/Zimbra/zm-ajax/pull/46, https://github.com/Zimbra/zm-web-client/pull/227, https://github.com/Zimbra/zm-mailbox/pull/511
> snickers: NICPS-30: added zimbraPrefDisplayTimeInMailList

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Problem: provide the ability to display banners to users on the domain or user level.
Fix : added new attribute zimbraCustomAppBanner. It is accountCosDomainInherited.
Testing done : testing done by developer
Testing to be done by QA : testing needed to be done by QA in PS team
Related PR: https://github.com/Zimbra/zm-web-client/pull/233
> snickers: NICPS-14: added zimbraCustomAppBanner

- store/src/java/com/zimbra/cs/index/history/LuceneSearchHistoryIndex.java
- store/src/java/com/zimbra/cs/index/solr/SolrIndex.java
- store/src/java/com/zimbra/qa/unittest/TestSearchHistory.java
This bug was caused by `LuceneSearchHistoryIndex` passing an empty ID list to the `SolrIndex::deleteDocument` method, which happens if there is no search history entries to purge. This fix adds a check for list emptiness in two places:
- in the `LuceneSearchHistoryIndex::delete` method, which addresses this immediate problem by short-circuiting the method before an indexer is even opened
- in the `SolrIndex::deleteDocument` method, to avoid other potential scenarios where an empty ID list is passed in
A unit test `TestSearchHistory::testPurgeHistory` has been added to verify this fix.
> ZCS-4339: Search History Purge Fix

- store/ivy.xml
- store/src/java/com/zimbra/cs/service/authenticator/CertUtil.java
Upgrading the bcprov jar version in store repo to 1.55 which is packaged in jetty/common/lib to remove the NoClassDefFoundError as earlier the repo was built with 1.46 version and there were significant changes in bouncy castle classes in version 1.47.
Testing Done: certauth working fine without any exceptions and user is logged in successfully.
> ZCS-4223:CertAuth broken: failing with exception

- store/src/java/com/zimbra/cs/event/StandaloneSolrEventStore.java
The bug only happens when the event backend is set to `StandaloneSolrEventStore`. The issue is that `StandaloneSolrEventStore.Factory` erroneously declares its own `solrHelper` variable that shadows the one set in the parent class. The bug is fixed by removing this declaration and casting the underlying `SolrRequestHelper` to `StandaloneSolrHelper` when constructing `StandaloneSolrEventStore`.
> ZCS-4252: NPE When Deleting Account

- store/src/java/com/zimbra/cs/db/DbSearchHistory.java
- store/src/java/com/zimbra/qa/unittest/TestSearchHistory.java
The DbSearchHistory::setSavedSearchStatus method, which updates a row in the `searches` DB table, would throw and error if the return value of the stmt.executeUpdate() call is zero. This happens if the update doesn't actually affect any rows, meaning that the search has not been registered in search history. This is actually a valid scenario, however, since it's possible to create a search folder for a query that isn't logged in search history, such as "in:inbox". This fix removes the return value check.
> ZCS-4247: Bugfix in DbSearchHistory

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
Problem : STARTTLS support for outbound mail
Fix : Add a ldap attribute zimbraSmtpStartTlsTrustedHosts to configure mail.smtp.ssl.trust Java Mail property after discussion in #533. Please refer to #533 for details.
Testing done : testing done by developer
Testing to be done by QA : testing needed to be done by QA
Linked PR : #533
> Another ldap attribute for NICPS-59/Bug 34202: STARTTLS support for outbound mail

- store/src/java/com/zimbra/cs/session/Session.java
- store/src/java/com/zimbra/cs/session/WaitSetAccount.java
Use fact that we have a mailbox object when registering an associated
WaitSet session, so that we don't end up creating another mailbox object
which tries to register an associated session...
> ZCS-4430:stack overflow registering session

- store/src/java/com/zimbra/cs/redolog/logger/DbLogWriter.java
Without this change I was able to reliably reproduce the issue documented in [ZCS-4275](https://jira.corp.synacor.com/browse/ZCS-4275) by executing the following from the `test` container:
/zimbra/init --run-soap yes --soap Admin/ACL
That was with one or two mailbox replicas.  After deploying this change, the above is no longer triggering the failure.
**Note** Have been trying to execute the full SOAP test run and has yet to run to completion for me. I started a run last night before going to bed and it had not completed this morning.  Am seeing different issues in the log files and will ensure we have tickets for them.
> ZCS-4275 DbLogWriter::close set conn to null

- store/src/java-test/com/zimbra/cs/util/JMSessionTest.java
- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/util/JMSession.java
Problem
-------
In NICPS-59/Bug 34202, we want to support STARTTLS for sending mail from mailboxd to Zimbra MTA.
Fix
---------
We can activate STARTTLS by configuring appropriate Java Mail properties.
We can use one of the following methods to send mails.
a. static void send(Message msg)
b. static void send(Message, Address[] addrs)
c. static void send(Message msg, Address[] addrs, String user, String password)
d. static void send(Message msg, String user, String password)
e. abstract void sendMessage(Message msg, Address[] addrs)
And only a, b, and e are used in mailboxd code.
In most of the cases, mailboxd calls JMSession.getSmtpSession() to get SMTP Session object.
I add new method configureStartTls() to set starttls properties based on the *zimbraSmtpStartTlsMode* value, and call it …
> NICPS-59/Bug 34202 STARTTLS support for outbound mail

- store/src/java/com/zimbra/cs/index/solr/SolrUtils.java
- store/src/java/com/zimbra/cs/util/RetryUtil.java
The RetryUtil class had bug that resulted in a null being returned if the `OnFailureAction.run()` invocation returned false. This resulted in an NPE thrown from `SolrIndex` class if the Solr collection was not able to be created for whatever reason, masking the real underlying problem.
This fix changes the `RetryUtil` logic to propagate any errors encountered in the `OnFailureAction.run()` method, making it impossible for a null to be returned.
> ZCS-4398: fixed NPE when failing to create solr collection

- store/src/java/com/zimbra/cs/index/IndexDocument.java
- store/src/java/com/zimbra/cs/index/query/FieldQuery.java
- store/src/java/com/zimbra/cs/index/query/Query.java
- store/src/java/com/zimbra/cs/index/solr/SolrUtils.java
- store/src/java/com/zimbra/cs/mime/ParsedContact.java
- store/src/java/com/zimbra/cs/mime/ParsedMessage.java
- store/src/java/com/zimbra/qa/unittest/TestSolrHeaderSearch.java
- store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
For numeric email headers like `HeaderName: 100`, the Zimbra query language supports both wildcard searches like `#HeaderName:1*` and range queries `#HeaderName:>90`. This was done with a custom tokenizer that, when encountering a numeric header value, generated two tokens:
- A token with the value `headername:100`, to allow for wildcard queries
- A token with the value `headername:#{code}`, where {code} is the integer value _prefix-coded_ using the `NumericUtils` class.
The prefix-coded tokens provided a sort order that could be used for range queries on the underlying numbers, instead of on their string representations.
With Lucene 6, the version used for our original Solr backend, prefix-coding functions were moved to the `LegacyNumericUtils` class. Lucene 7 (and therefore Solr 7) …
> ZCS-4385: Refactored Header Search

- store/ivy.xml
- store/src/java/com/zimbra/cs/index/TermInfo.java
- store/src/java/com/zimbra/cs/index/ZimbraTopDocs.java
- store/src/java/com/zimbra/cs/index/ZimbraTopFieldDocs.java
This PR bumps the `Solr/Lucene` ivy dependencies to `7.2.1` and resolves a few issues caused by API changes that comes with the version upgrade.
Relevant Lucene 7 API changes:
- `TopDocs.totalHits` is now a `long` instead of an `int`. For our use case, it's safe to just cast it to an integer
- `Field.fieldType()` now returns `IndexableFieldType`. This affects the `TermInfo` class, though I'm not sure if this class is even used anymore.
> ZCS-4242: Upgrade to Solr 7

- build.xml
- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- pkg-builder.pl
- store/build.xml
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
A mechanism was needed to be added such that a given `zimbra-store` package could know which version of the LDAP schema it was built against.
This PR adds a new ant target `create-version-ldap` which generates a file which is utilized by scripts in the `zm-build` repository.
> Task/zcs 4381 - generate an ldap schema file + add zimbraLDAPSchemaVersion attribute

- store/src/java-test/com/zimbra/cs/redolog/logger/DbLogWriterTest.java
- store/src/java/com/zimbra/cs/redolog/logger/DbLogWriter.java
- store/src/java/com/zimbra/cs/redolog/logger/LogWriter.java
This PR addresses a problem with The `DbLogWriter` class, hopefully resolving the `com.zimbra.cs.redolog.logger.DbLogWriter com.zimbra.cs.redolog.logger.DbLogWriter failed` error.
Prior to this change, `DbLogWriter` maintained a single `DbConnection` instance in the `conn` variable. This connection was created at `RedoLogManager` startup and only closed in the `stop` method, which is only called during system shutdown. This connection was responsible for handling all DB calls for the duration of the `DbLogWriter` lifetime; it is entirely possible that the intermittent error is due to it timing out or being otherwise corrupted.
This change makes it so that every database call in this class uses a new `DbConnection` instance (for reference, this is how all other DB-bound classes function). …
> ZCS-4455: DbLogWriter Connection Handling

- store/src/java-test/com/zimbra/cs/mailbox/InMemoryIdProvider.java
- store/src/java-test/com/zimbra/cs/mailbox/MailboxTestUtil.java
- store/src/java/com/zimbra/cs/mailbox/IdProvider.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/RedisIdProvider.java
- store/src/java/com/zimbra/cs/util/Zimbra.java
This PR introduces an `IdProvider` that ensures that IDs in a multi-server environment remain monotonically increasing. This externalizes the state of three values previously read from the in-memory `MailboxData` instance: `itemId`, `searchId`, and `changeId`.
`SynchronizedId` represents a value that can be safely read and incremented in a distributed environment. It has three methods:
- `value()` returns the cluster-wide current value of the ID
- `increment()` atomically increments the value by the given delta
- `setIfNotExists()` atomically sets the value if it is currently unset, and returns the value regardless of whether it was modified or not.
`IdProvider` is an abstract class with methods `getItemId`, `getSearchId`, and `getChangeId` that return implementations of `SynchronizedId`. …
> ZCS-4755: ID synchronization via Redis

- store/src/java/com/zimbra/cs/mailbox/MailItem.java
This bug was introduced with the recent addition of SmartFolders. The UnderlyingData::setTags method was updated to handle both tags and SmartFolders, and in the process, null handling was broken. When all tags are removed from a MailItem, the value passed to setTags is a null, which tells the system to set the tags field to NO_TAGS. This bugfix restores this logic.
> ZCS-4607: fixed bug when removing all tags from MailItem

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/mailbox/RedissonClientHolder.java
The latest zm-docker expects to access redis using the service name "zmc-redis" instead of "redis".
Fixed zm-mailbox to match, making it configurable via LC keys at the same time.
> ZCS-4893 Ability to configure redis

- store/src/java/com/zimbra/cs/lmtpserver/LmtpHandler.java
For quite a while now Zimbra has generated a broken `Return-Path` header without the mandatory angle brackets.  Additionally, it didn't add a `Return-Path` at all for an empty envelope sender. This tends to confuse some scripts I have.
[RFC 5322 section 3.6.7.](https://tools.ietf.org/html/rfc5322#section-3.6.7) says:
> The "Return-Path:" header field contains a pair of angle brackets
> that enclose an optional addr-spec.
This patch makes sure the `Return-Path` header is always set and the (optional) address value is enclosed in angle brackets.
To verify this I used the following `swaks` invocations:
**With regular Envelope Sender**
```bash
swaks --to admin@$(hostname -f) --from test@example.com --protocol LMTP --server 127.0.0.1 --port 7025
```
Before:
```
Return-Path: test@example.com …
```
> Bug 102931: Add missing angle brackets to Return-Path

- soap/src/java/com/zimbra/soap/mail/message/CreateAppointmentExceptionRequest.java
- store/src/java/com/zimbra/cs/mailbox/CalendarItem.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/Message.java
- store/src/java/com/zimbra/cs/mailbox/calendar/InviteInfo.java
- store/src/java/com/zimbra/qa/unittest/TestJaxb.java
- store/src/java/com/zimbra/qa/unittest/TestUtil.java
ZWC expects each exception in a message to have a unique item ID
associated with it.  If this doesn't happen, the details of the first
exception are used.
Pseudo exceptions created when a reply is received specifying a
particular PARTSTAT to single instance of the main series
were not obeying this rule.  Instead 0 was used for both the item ID
and the component number.  I had hoped that using the item ID of the
calendar entry and a different component number would fix the issue,
as intuitively, this is what I expected those values to mean but
that doesn't match reality or what happens when exceptions are created
in the calendar as a result of ZWC actions (or CalDAV actions)
* public `Mailbox.ItemIdGetter` interface and private
`Mailbox.NextItemIdGetter` implementation added as a preferred …
> ZCS-3055 Different date shown for Recurring Appointment Instance

- store/src/java/com/zimbra/cs/zimlet/ZimletUtil.java
Fixed an error found while deploying classic zimlets
Old zimlets do not have an attribute Semver. Which was causing and LDAPException while updating attributes.
Verified that zimlet deployment works after this fix.
> ZCS-4142 Fixing error found for deploy zimlet

- store/src/java/com/zimbra/cs/mailbox/CalendarItem.java
There is an existing ZWC bug that responses to allday appointments
contain a DATE-TIME for the value of the RECURRENCE-ID instead of
a DATE.  The previous ZCS-3055 changes introduced a change in
behavior when handling this, which is even more buggy than
the previous handling.  In particular, you end up with:
RECURRENCE-ID;TZID="UTC":20180427T230000
instead of the more correct (but still wrong):
RECURRENCE-ID:20180427T230000Z
This change re-instates the old behavior.
Note that this does NOT address display problems resulting from
the way the bad response is currently handled - See ticket ZCS-4932
> ZCS-3055:Bad ZWC allday reply treated old way

- store/src/java-test/com/zimbra/cs/mailbox/MailboxTestUtil.java
- store/src/java/com/zimbra/cs/imap/ImapListener.java
- store/src/java/com/zimbra/cs/imap/LocalImapMailboxStore.java
- store/src/java/com/zimbra/cs/mailbox/Folder.java
- store/src/java/com/zimbra/cs/mailbox/LocalPubSub.java
- store/src/java/com/zimbra/cs/mailbox/MailItem.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/NotificationPubSub.java
- store/src/java/com/zimbra/cs/mailbox/RedisPubSub.java
- store/src/java/com/zimbra/cs/session/AdminSession.java
- store/src/java/com/zimbra/cs/session/LocalSessionDataProvider.java
- store/src/java/com/zimbra/cs/session/PendingLocalModifications.java
- store/src/java/com/zimbra/cs/session/PendingModifications.java
- store/src/java/com/zimbra/cs/session/RedisSessionDataProvider.java
- store/src/java/com/zimbra/cs/session/RemoteSoapSession.java
- store/src/java/com/zimbra/cs/session/Session.java
- store/src/java/com/zimbra/cs/session/SessionCache.java
- store/src/java/com/zimbra/cs/session/SessionDataProvider.java
- store/src/java/com/zimbra/cs/session/SoapSession.java
- store/src/java/com/zimbra/cs/session/WaitSetAccount.java
- store/src/java/com/zimbra/cs/session/WaitSetSession.java
- store/src/java/com/zimbra/cs/util/Zimbra.java
- store/src/java/com/zimbra/qa/unittest/TestImapServerListener.java
- store/src/java/com/zimbra/soap/DocumentHandler.java
- store/src/java/com/zimbra/soap/SoapSessionFactory.java
This PR enables soap session functionality in an multi-node environment, restoring mailbox notifications via response headers. This is done through several enhancements:
1. A new pub/sub mechanism that allows sessions to receive notifications from anywhere in the cluster
2. Migration of several instances of session state to Redis
3. An update the session modification sequence logic that (hopefully) ensures that the client does not receive duplicate notifications from multiple nodes
To understand this PR, it's first important to understand how soap sessions handled mailbox notifications prior to HA and how the new architecture breaks it. 
The two relevant components of a SoapSession are:
* `SoapSession.changes`, which is a `QueuedNotifications` object that contains an increasing sequence …
> ZCS-4362, ZCS-4363, ZCS-4364: Distributed Sessions via Pub/Sub

- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
This fix rolls back behavior behavior introduced with the migration to redis for folder/tag caches. I had erroneously thought that these caches are built at every transaction, which was a result if my misunderstanding the condition that short-circuits the `loadFoldersAndTags` method. While this method is called at every transaction, it is meant to exit if the caches are already in place. 
My recent changes made it so that this did not happen, causing the folder/tag snapshots to be rebuilt every time. This resulted in a performance hit, as well as introduced bugs caused by multiple objects representing the same folder existing at the same time.
The downside of this rollback is that folders and tags are no longer synchronized between mailbox workers. Finding a new approach to resolve this …
> zcs-4842: folder/tag cache rollback

- store/src/java/com/zimbra/cs/mime/ParsedMessage.java
Attachment queries like `has:attachement` have been broken with Solr due to how we now index attachment types. The fix on the mailbox side is to explicitly add "any" or "none" tokens to each index document, instead of relying on the tokenizer to do this.
See https://github.com/Zimbra/zm-solr/pull/9 for the zm-solr side of this fix, and for a more in-depth explanation of the issue.
> ZCS-4147: Explicitly indexing 'none' and 'any' attachment types

- common/src/java/com/zimbra/common/util/Log.java
- store/src/java/com/zimbra/cs/ldap/LdapUsage.java
Fix compilation issue:
[javac]                 ZimbraLog.ews.errorQuietly("Error generating the salt", e);
[javac]                              ^
[javac]   both method errorQuietly(Object,Throwable) in Log and method errorQuietly(String,Object) in Log match
> ZCS-4928:fix ambiguous Log.[warn|error]Quietly

- store/docs/rest.txt
- store/src/java-test/com/zimbra/cs/service/formatter/MobileConfigFormatterTest.java
- store/src/java/com/zimbra/cs/service/formatter/FormatterFactory.java
- store/src/java/com/zimbra/cs/service/formatter/MobileConfigFormatter.java
- store/src/java/com/zimbra/cs/service/util/UserServletUtil.java
Problem : user should be able to download his caldav/carddav/imap profile configuration file to setup his/her account on mac/iphone without any hassle.
Approach :
1. Expose rest api to download profile configuration file
2. Profile configuration file should be created using parser and well formatted file should be downloaded.
Fix :
1. Created new formatter named - MobileConfigFormatter
2. Used dom parser to create profile configuration file
3. caldav, carddav and imap config files are working fine.
Testing done :
1. tested caldav, carddav and imap profile config files, working fine.
2. tested negative test cases like entering wrong configType and fmt, expected errors received.
3. tested by setting different auth user and target users, expected error message received.
4. added unit tests …
> ZCS-4832 : Create configuration file for CalDav and CardDav

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
This is for ticket https://jira.corp.synacor.com/browse/NICPS-232, 
Run 
#zmprov desc -a zimbraAuthDomainCheckEnabled 
to Verify if new LDAP attribute is available 
Run zmprov mcf zimbraAuthDomainCheckEnabled TRUE
to update the attribute value to TRUE 
Verify domain/virtualhost check is enaabled.
Run zmprov mcf zimbraAuthDomainCheckEnabled FALSE
to update the attribute value to FALSE 
Verify domain/virtualhost check is disabled.
Related PRs: https://github.com/Zimbra/zm-taglib/pull/9,
https://github.com/Zimbra/zm-taglib/pull/10
> NICPS-232: Restrict user to login on virtual domain - Part 2

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
This is a new ldap attribute added to store the captcha API url, which is access on webmail login page to dispaly and validate captcha.
Related PRs: https://github.com/Zimbra/zm-taglib/pull/12/
https://github.com/Zimbra/zm-web-client/pull/267
> NICPS-167: Add new ldap attribute to store captcha api url

- soap/src/java/com/zimbra/soap/admin/message/ContactBackupResponse.java
- soap/src/java/com/zimbra/soap/admin/type/ContactBackupServer.java
- store/src/java-test/com/zimbra/cs/service/admin/ContactBackupApiTest.java
- store/src/java/com/zimbra/cs/service/admin/ContactBackup.java
Moved ContactBackupServer
**common/src/java/com/zimbra/common/soap/ContactBackupServer.java → soap/src/java/com/zimbra/soap/admin/type/ContactBackupServer.java**
Renamed **Status** to **ContactBackupStatus** as two classes should not have the same XML type name.
> ZCS-5107 : xml type in common should be in soap type directory

- store/src/java-test/com/zimbra/cs/service/RecoverAccountTest.java
- store/src/java/com/zimbra/cs/service/mail/RecoverAccount.java
Fixed failures related to auth, resend count and input validation.
1. Authentication is not required for RecoverAccountRequest
2. email input verification.
3. resend count increased before comparison. 
Testing done :
tested all 3 fixes manually.
> ZCS-4798 : RecoverAccount API and it's implementation

- common/src/java/com/zimbra/common/service/ServiceException.java
- common/src/java/com/zimbra/common/soap/AccountConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/account/message/ResetPasswordRequest.java
- soap/src/java/com/zimbra/soap/account/message/ResetPasswordResponse.java
- store/docs/soap.txt
- store/src/java-test/com/zimbra/cs/service/ResetPasswordTest.java
- store/src/java/com/zimbra/cs/service/account/AccountService.java
- store/src/java/com/zimbra/cs/service/account/ResetPassword.java
- store/src/java/com/zimbra/cs/service/mail/RecoverAccount.java
**Problem:** Write reset password API and it's implementation
**Fix:** 
1. Created API ResetPasswordRequest and its response
```
<ResetPasswordRequest>
<password>...</password>
</ResetPasswordRequest>
<ResetPasswordResponse />
```
2. Implemented required code for password reset. Password will be changed for account in auth token.
3. Updated soap.txt
4. Added feature check in the same api and recover account api
1. Manually tested API
2. Manually tested different scenarios with valid/invalid input.
3. Manually tested all the scenarios of logout on password change. Tested with ZWC, IMAP and ActiveSync clients. All clients ask to login again once the password is reset.
4. Added unit tests.
1. Manually test api and different scenarios with …
> ZCS-4802 : Reset Password API and it's implementation

- store/conf/attrs/zimbra-attrs.xml
**Problem:** zimbraFeatureResetPasswordEnabled, zimbraPrefPasswordRecoveryAddress and zimbraPrefPasswordRecoveryAddressStatus are not accessible on UI
**Fix:** add "accountInfo" flag to these attributes, so that they can be received on UI in GetInfoResponse.
**Testing Done:** Manually tested all 3 attributes using "zmprov desc -a". Flag is set to all 3 now.
```
zmprov desc -a zimbraFeatureResetPasswordEnabled
zimbraFeatureResetPasswordEnabled
whether or not password reset feature is enabled
type : boolean
value : 
callback : 
immutable : false
cardinality : single
requiredIn : 
optionalIn : domain,cos,account
flags : accountInfo,accountCosDomainInherited
defaults : FALSE
min : 
max : 
id : 3024
requiresRestart : 
since : 8.8.9
deprecatedSince : 
zmprov desc -a …
```
> ZCS-5187: Add accountInfo flag

- store/src/java/com/zimbra/cs/index/ZimbraHit.java
**Problem:** Scrolling down causes network error(toggle read / unread)
**Fix:** in case of readAsc and readDesc, "sortValue" is Long object so it should be treated with other Long operations, which previously was done with String and it was throwing class cast exception.
**Testing done:** tested functionality on ZWC manually.
- test the functionality with different sorting along with readAsc and readDesc.
- automation should be added for the case.
> ZBUG-425: Scrolling down causes network error(toggle read / unread)

- soap/src/java-test/com/zimbra/soap/JaxbToJsonTest.java
- soap/src/java/com/zimbra/soap/json/JacksonUtil.java
- soap/src/java/com/zimbra/soap/json/jackson/ZimbraJaxbAnnotationIntrospector.java
- soap/src/java/com/zimbra/soap/json/jackson/ZmPairAnnotationIntrospector.java
This is a workaround for a presumed bug in Jackson (see https://github.com/FasterXML/jackson-modules-base/issues/47) where it doesn't work with our way of mapping `@XmlElementWrapper` / `@XmlElement` annotated properties to JSON - we use the name in `@XmlElementWrapper` rather than the usual Jackson preference for the name in `@XmlElement`.
In theory, there is a feature which should switch things to work the way we want them to work but that doesn't work, at least in specific scenarios we use where we have the same name at the `@XmlElement` level for objects of the same class for 2 different fields.
After that change, can now select "edit properties" of the inbox in ZWC and also configure message retention.
> ZCS-5202,ZCS-5112 JSON XmlElementWrapper support broken

- store/src/java-test/com/zimbra/cs/service/RecoverAccountTest.java
- store/src/java-test/com/zimbra/cs/service/SetRecoveryAccountTest.java
- store/src/java/com/zimbra/cs/account/EmailChannel.java
- store/src/java/com/zimbra/cs/account/ForgetPasswordException.java
- store/src/java/com/zimbra/cs/service/mail/RecoverAccount.java
- store/src/java/com/zimbra/cs/service/mail/SetRecoveryAccount.java
- store/src/java/com/zimbra/cs/service/util/ResetPasswordUtil.java
**Problem:** Errors shown on UI should be language independent
**Fix:** Create error codes and pass them instead of passing plain string message for error condition.
1. Corrected and ran unit tests for SetRecoverAccountTest and RecoverAccountTest.
2. Manually tested responses on SOAPUI.
1. Correct required automation.
2. Test and verify errors received in responses.
**Linked PR:**
https://github.com/Zimbra/zm-web-client/pull/279
> ZCS-5266: Errors shown on UI should be language independent

- store/src/java/com/zimbra/cs/imap/ImapFolder.java
- store/src/java/com/zimbra/cs/imap/LocalImapMailboxStore.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
This is largely safety code.  We don't appear to have been able to reproduce the NPEs reported internally and I haven't been able to either but this code should address one theory:
* thread 1 enters `restore`.
* thread 2 enters `restore` and gets all the way through.
* thread 1's associated session is being decommissioned, so it sets mailboxStore = null and throws
an ImapSessionClosedException
* later, thread 2 accesses mailboxStore and goes boom.
I largely think of `restore` as being part of a get from cache, that get shouldn't really be fully successful until the returned object is valid and complete.  However, I have observed multiple gets from ehcache returning the same object, and then go on to call `restore` to tidy it up.  I've made `restore` synchronized so that at least you …
> ZBUG-446 NPE avoidance

- store/src/java/com/zimbra/qa/unittest/TestSendAndReceive.java
Unittest TestSendAndReceive wasn't fixed to reflect the change Malte
did for Bug 102931 to be correct by standards and put the sender email
in angle brackets in Return-Path
> Bug102931:Return-Path now has angleBrackets

- store/src/java/com/zimbra/cs/session/SessionMap.java
Prevents a NPE when there is no AccountSessionMap.
> ZCS-5256 ensure acctMap is not null

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/callback/DefaultCalendarIdCallback.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/service/mail/ItemAction.java
Enhancement: Introduce default calendar preference attribute
Approach & Fix:
- Added new ldap attribute zimbraPrefDefaultCalendarId on account and cos level
- Added callback on the same to do verification before changing the value of it.
- Changing value on cos level is blocked
- Verified folder presence, type, and permissions in case of shared calendar.
- In case of shared calendar, can only be used as default calendar when WRITE access is available.
Testing done:
- Tested scenarios manually. (http://testrail01.buf.synacor.com/testrail/index.php?/cases/view/1272290)
Testing needs to be done by QA:
- Tests scenarios manually (http://testrail01.buf.synacor.com/testrail/index.php?/cases/view/1272290)
- Automate the same
- Test on multi-node for shared calendar case.
> ZCS-90 introduce default calendar preference attribute

- store/src/java/com/zimbra/cs/account/callback/DefaultCalendarIdCallback.java
**Problem:** CreateCosRequest fails with invalid request exception.
**Fix:**
- Invalid request exception was thrown because the entry object is null while creating cos.
- This was not found on local as the new attribute was introduced as part ZCS-90 and It is not initialized to default value on dev environment.
- Added null check for entry object in the callback class from where the exception was being thrown.
- Tested on zdev-vm004.eng.zimbra.com by replacing store jar.
- Tested by creating cos from command line using zmprov command.
- Tested by creating cos from admin console.
- Cos creation should not fail because of this attribute.
- Account creation should not fail because of this attribute.
> ZCS-5577 Receiving Invalid request exception for CreateCosRequest.

- common/src/java-test/com/zimbra/common/zmime/ZInternetHeaderTest.java
- common/src/java/com/zimbra/common/zmime/ZInternetHeader.java
Added code to ignore if encoded header has space which is not encoded and char set is ISO-8859-1
Added unit test.
1327 | 0 | 0 | 10 | 100.00% | 359.591
> ZBUG-536 Fixed email subject rendering

- store/src/java/com/zimbra/cs/service/UserServlet.java
This change removes the "WWW-Authenticate: BASIC realm="Zimbra"  from the response header for existing users in the test curl calls, 401 responses.
Test calls:
curl -k -i -u 'admin:password' 'https://[zimbra.hostname]/service/home/~'
curl -k -i -u 'doesnotexistrandom737:password' 'https://[zimbra.hostname]/service/home/~'
For the following calls both 401 headers should not have the following row, 
"WWW-Authenticate: BASIC realm="Zimbra"
> ZCS-5598: Bug 109012 - Account Enumeration [CWE-203]

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
**Problem:** Create zimbraAccountSeniorityIndex and zimbraHierarchicalAddressBookRoot ldap attributes with given details on the jira ticket ZCS-5698.
**Fix:**  Created zimbraAccountSeniorityIndex and zimbraHierarchicalAddressBookRoot ldap attributes.
**Testing done:** Tested attributes manually using zmprov command.
```
zmprov desc -a zimbraAccountSeniorityIndex
zimbraAccountSeniorityIndex
seniority index of the account which will determine the sorting order
in the hierarchical address book
type : integer
value : 
callback : 
immutable : false
cardinality : single
requiredIn : 
optionalIn : account
flags : 
defaults : 
min : 
max : 
id : 3030
requiresRestart : 
since : 8.8.10
deprecatedSince : 
zmprov desc -a zimbraHierarchicalAddressBookRoot
zimbraHierarchicalAddressBookRoot
domain level …
```
> ZCS-5698 Add ldap attributes required for HAB

- common/src/java/com/zimbra/common/gql/GqlConstants.java
- soap/src/java/com/zimbra/soap/mail/message/CreateSearchFolderRequest.java
- soap/src/java/com/zimbra/soap/mail/type/ModifySearchFolderSpec.java
- soap/src/java/com/zimbra/soap/mail/type/NewFolderSpec.java
- soap/src/java/com/zimbra/soap/mail/type/NewSearchFolderSpec.java
- soap/src/java/com/zimbra/soap/mail/type/SearchFolder.java
**Problem:** Implement CreateSearchFolder, GetSearchFolder and ModifySearchFolder api in gql
**Fix:**
- Created query for GetSearchFolder and mutation for CreateSearchFolder and ModifySearchFolder
- Added required annotations for all 3 apis
- Made required changes in repository and resolver classes
- Tested all 3 apis manually using graphiql client
- Docs for the same can be viewed on graphiql
- Test all 3 apis manually with all different combinations of input
- Automate the same
**Linked PR:**
https://github.com/Zimbra/zm-gql/pull/15
> ZCS-5607 Implementing CreateSearchFolder API in GraphQL

- common/src/java/com/zimbra/common/gql/GqlConstants.java
- soap/src/java/com/zimbra/soap/account/message/GetAccountInfoResponse.java
- soap/src/java/com/zimbra/soap/type/NamedValue.java
**Problem:** Write graphql api for GetAccountInfo and EndSession soap apis
**Fix:**
- Created both apis
- Tested both apis maually
```
query{
accountInfoGet{
name
attrs {
name
value
}
soapURL
publicURL
communityURL
changePasswordURL
adminURL
boshURL
}
}
```
```
mutation{
accountEndSession(clearCookies: true)
}
```
**Testing needed by QA:**
- test both the apis
- write automation for the same
**Linked PR:**
https://github.com/Zimbra/zm-gql/pull/23
> ZCS-5351 Implement API for user account info

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/admin/message/DeleteDistributionListRequest.java
- store/src/java-test/com/zimbra/cs/account/MockProvisioning.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
- store/src/java/com/zimbra/cs/service/admin/DeleteDistributionList.java
Problem: Cascade delete static hierarchy in ldap.
Fix:
- Added "cascadeDelete" param in DeleteDistributionListRequest.
- Made code changes to delete sub dls.
- Member will be deleted only if it's dl. And no else member will be deleted.
Testing done:
Tested the api with and without cascade delete param manually from soapui.
Testing needs to be done by QA:
- Test api with and without cascade delete param.
- Test DeleteDistributionListRequest and verify nothing is broken.
- Verify that only hierarchy is deleted and no actual accounts are deleted.
> ZCS-5395 Admin API to delete static hierarchy in ldap

- common/src/java/com/zimbra/common/gql/GqlConstants.java
- soap/src/java/com/zimbra/soap/mail/type/ActionResult.java
- soap/src/java/com/zimbra/soap/mail/type/CalTZInfo.java
- soap/src/java/com/zimbra/soap/mail/type/ContactActionSelector.java
- soap/src/java/com/zimbra/soap/mail/type/ContactGroupMember.java
- soap/src/java/com/zimbra/soap/mail/type/ContactInfo.java
- soap/src/java/com/zimbra/soap/mail/type/ContactSpec.java
- soap/src/java/com/zimbra/soap/mail/type/ConversationMsgHitInfo.java
- soap/src/java/com/zimbra/soap/mail/type/ConversationSummary.java
- soap/src/java/com/zimbra/soap/mail/type/EmailInfo.java
- soap/src/java/com/zimbra/soap/mail/type/MailCustomMetadata.java
- soap/src/java/com/zimbra/soap/mail/type/MessageHitInfo.java
- soap/src/java/com/zimbra/soap/mail/type/MessageInfo.java
- soap/src/java/com/zimbra/soap/mail/type/ModifyContactAttr.java
- soap/src/java/com/zimbra/soap/mail/type/ModifyContactGroupMember.java
- soap/src/java/com/zimbra/soap/mail/type/ModifyContactSpec.java
- soap/src/java/com/zimbra/soap/mail/type/ModifySearchFolderSpec.java
- soap/src/java/com/zimbra/soap/mail/type/NewContactAttr.java
- soap/src/java/com/zimbra/soap/mail/type/NewContactGroupMember.java
- soap/src/java/com/zimbra/soap/mail/type/SearchFolder.java
- soap/src/java/com/zimbra/soap/mail/type/VCardInfo.java
- soap/src/java/com/zimbra/soap/type/ContactAttr.java
- soap/src/java/com/zimbra/soap/type/CursorInfo.java
- soap/src/java/com/zimbra/soap/type/NamedValue.java
- soap/src/java/com/zimbra/soap/type/TzOnsetInfo.java
- soap/src/java/com/zimbra/soap/type/WantRecipsSetting.java
* Annotations for gql contacts resolver.
* Updated some booleans for consistency (using `include`, `is`, `do` since they're most common).
* This affects some gql search resource properties:
* `wantHtml` -> `includeHtml`
* `needCanExpand` -> `includeIsExpandable` (the resulting property as `isExpandable`)
* `wantRecipients` -> `includeRecipients`
* Prefix class constants.
Minimal testing with basic properties for all resources, see jira ticket for some example queries/mutations.
See testrail.
See associated PR Zimbra/zm-gql#25 for more info.
I added a constructor to `ContactActionSelector` such that the update method can set the `ids` and `operation`.
> ZCS-4165 Annotations for Contact resolver.

- common/src/java/com/zimbra/common/gql/GqlConstants.java
- soap/src/java/com/zimbra/soap/mail/type/AttachSpec.java
- soap/src/java/com/zimbra/soap/mail/type/AttachmentsInfo.java
- soap/src/java/com/zimbra/soap/mail/type/EmailAddrInfo.java
- soap/src/java/com/zimbra/soap/mail/type/InvitationInfo.java
- soap/src/java/com/zimbra/soap/mail/type/InviteComponent.java
- soap/src/java/com/zimbra/soap/mail/type/MessageCommon.java
- soap/src/java/com/zimbra/soap/mail/type/MessageInfo.java
- soap/src/java/com/zimbra/soap/mail/type/MimePartInfo.java
- soap/src/java/com/zimbra/soap/mail/type/Msg.java
- soap/src/java/com/zimbra/soap/mail/type/MsgSpec.java
- soap/src/java/com/zimbra/soap/mail/type/MsgToSend.java
- soap/src/java/com/zimbra/soap/mail/type/MsgWithGroupInfo.java
- soap/src/java/com/zimbra/soap/type/AttributeName.java
- soap/src/java/com/zimbra/soap/type/MsgContent.java
Added annotations and grapgQL contants for zm-gql messages functionality.
Fetch message by id
Send message
Testing Done
Minimal testing with basic properties, see jira ticket for tested queries/mutations.
Requires ZCS-4164 branch on zm-gql 
Testing to be done by QA
> ZCS-4164 Update annotations and constants on related classes for send receiving messages.

- store/src/java/com/zimbra/cs/imap/ImapListener.java
- store/src/java/com/zimbra/cs/session/Session.java
- store/src/java/com/zimbra/cs/session/SoapSession.java
* Store user agent, and request ip in Session to associate with session id
* Store auth token only in SoapSession to associate with session id
Manual logins, session creation from various places (webclient, gql, etc)- fetched sessions associated with test accounts to determine property retention
Session creation
> ZCS-4905 Store user agent, ip address, and auth token

- common/src/java/com/zimbra/common/soap/AccountConstants.java
- soap/src/java/com/zimbra/soap/account/message/EndSessionRequest.java
- store/docs/soap.txt
- store/src/java/com/zimbra/cs/service/account/EndSession.java
**Problem:** End specific session using sessionId 
**Fix:**
- Setting sessionId will end session for given session id and not current session.
- De-register auth token for given sessionId if "logoff" is true.
```
<EndSessionRequest xmlns="urn:zimbraAccount" [logoff="1"] [sessionId="session_id"]/>
```
- Tested api manually using soapui with and without session id param.
**Testing needs to be done by QA:**
- Test api changes
- Test existing funtionality
- Test overall end session api
> ZCS-5800 End specific session using sessionId 

- store/src/java/com/zimbra/cs/index/SearchParams.java
Was able to replicate error, and then updated condition to prevent the non null exception.
For testing remove sortby value in searchRequest while querying "is:unread"
```Java
<soap:Body>
<SearchRequest xmlns="urn:zimbraMail" types="message" needExp="1" recip="0" limit="100" offset="0">
<query>is:unread</query>
</SearchRequest>
</soap:Body>
```
> ZCS-5871 updated is:unread condition to fix non null error

- store/conf/attrs/zimbra-attrs.xml
**Problem:** Sync address list to the GAL
**Fix:**
- Added address list in zimbra sync in zimbraGalLdapFilterDef
- Also added description search with has in the same
- Testing done manually.
- Address list is being synced in the Gal
- Address list is being searched from the gal
- Search is working for description with has 
- verify address list is being synced in gal
- verify address list is being searched from gal
- verify search is working for description with has
> ZCS-5849 Sync address list to the GAL

- client/src/java/com/zimbra/client/ZMailbox.java
- common/src/java/com/zimbra/common/soap/HeaderConstants.java
- common/src/java/com/zimbra/common/soap/SoapHttpTransport.java
- common/src/java/com/zimbra/common/soap/SoapTransport.java
- store/src/java/com/zimbra/cs/session/SoapSession.java
- store/src/java/com/zimbra/soap/SoapEngine.java
- store/src/java/com/zimbra/soap/SoapServlet.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
Store the original user agent header as a separate value (originally named browserInfo, but renamed per request). 
* This header value is added to context, then passed through until ZSC then as a `SoapSession` is created where we can store it such that it winds up in the `SessionCache`.
* ZMailbox sends this header if it is set, since we need this on login/getinfo - this is done by respective tags using zclient requests.
See associated PRs:
Zimbra/zm-taglib#16
Zimbra/zm-gql#30
Basic login tests and checks to verify that the information is visible. Login tests with no browser user agent.
Session creation, and verifying accessibility of the browser information.
> ZCS-4905 Store original user agent

- store/src/java/com/zimbra/cs/service/account/SearchGal.java
**Problem:** if type is "all", !(#zimbraAccountCalendarUserType:RESOURCE) should not be added in gal and ldap query.
**Fix:** missed to add type in params, so account was being set as default value and !(#zimbraAccountCalendarUserType:RESOURCE) was being added in the query.
- Tested create address list api manually for different values of "type" and queries are generated according to type.
- verify gal and ldap queries are generated according to type and given conditions.
> add tyep in params

- soap/src/java/com/zimbra/soap/account/type/HABGroup.java
- soap/src/java/com/zimbra/soap/admin/type/HABGroupOperation.java
- store/src/java/com/zimbra/cs/account/ProvUtil.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
Added operation to update seniority index to Modify HABGroup
<urn1:ModifyHABGroupRequest>
<urn1:habGroupOperation habGroupId="id"  seniorityIndex="34" op="assignSeniority"/>
</urn1:ModifyHABGroupRequest>
Added zmprov command for updating seniority index of HAB group:
mhabsi  {habGrpId} {seniorityIndex}
Bulk updates can be done using
zmprov < update.txt
where update.txt contains:
mhabsi {id1} {seniorityIndex}
mhabsi {id2} {seniorityIndex}
mhabsi {id2} {seniorityIndex}
> ZCS-5707 Updating seniority index for HAB group

- common/src/java/com/zimbra/common/gql/GqlConstants.java
- soap/src/java/com/zimbra/soap/mail/type/NewFolderSpec.java
* Use constants in `NewFolderSpec`
* Use `@GraphQLInputField` on setters and ignore the singular grant method
* Boolean type is derived from setter (true/false is all we need for `fetchIfExists`)
* `true` and `false` for `fetchIfExists`.
* General success/fail cases
Folder tests - testrail.
> ZCS-5865 Fix gql folderCreate input annotations.

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
Changes to show capthca after specific failed login attempt that count must be configurable by ldap attribute
> NICPS-417: Changes to show capthca after specific failed login attempt

- store/src/java/com/zimbra/cs/service/UserServlet.java
Add the BASIC auth header to both invalid account and valid account but wrong password flow.
This is to prevent account enumeration.
Verified that the following SOAP automation has not failure 
data/soapvalidator/RestServlet/Sharing/permissions_guest.xml
data/soapvalidator/RestServlet/Sharing/permissions_GranteeType.xml
Verified URL like when accessed from the browser
https://xxxx:8443/home/user1@xxxx/Briefcase/TestLog shows the prompt for username and pasword
> ZCS-6047 Fixing  regression

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/admin/message/ModifyAddressListRequest.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
* Added `clearFilter` attribute
* Ignored if filter is non-null
* When true, create base search filters with no conditions
* Update domain fetch from old gal query to support condition-less query
* LDAP escape the new name before rename
All cases outlined in new jira comment request
See jira ticket
> ZCS-5388 Support clearFilter when modifying address list.

- store/src/java-test/com/zimbra/cs/store/MockStoreManager.java
- store/src/java/com/zimbra/cs/service/admin/DeleteVolume.java
- store/src/java/com/zimbra/cs/service/admin/ModifyVolume.java
- store/src/java/com/zimbra/cs/store/StoreManager.java
- store/src/java/com/zimbra/cs/store/external/ExternalStoreManager.java
- store/src/java/com/zimbra/cs/store/file/FileBlobStore.java
Hello,
we want to deny zmvolume command and Zimbra admin web-ui to edit/delete volumes
handled by a custom StoreManager.
We can accomplish this by adding a new StoreFeature.CUSTOM_STORE_API.
ZeXtras StoreManager also allows to create volumes on different store types,
each supporting different features, so we added a new method to StoreManager to
check features of a single volume:
StoreManager.supports(StoreFeature feature, String locator)
Thanks
> Deny edit/delete custom volumes -> Zimbra 8.8.10

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/admin/message/GetAddressListInfoRequest.java
- soap/src/java/com/zimbra/soap/admin/message/GetAddressListInfoResponse.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/ldap/ZLdapFilterFactory.java
- store/src/java/com/zimbra/cs/ldap/unboundid/UBIDLdapFilterFactory.java
* Added constants, models, and ldap util methods for GetAddressListInfo - this API returns the meta info of the address list, and does not execute the query.
See jira ticket.
See testrail.
> ZCS-6075 GetAddressListInfo API constants, models, and util methods.

- common/src/java/com/zimbra/common/gql/GqlConstants.java
Added support for 2 new params in endSession
clearAllSoapSessions
excludeCurrentSession
Tested the new attributes work in the GQL query
> ZCS-6063 Adding  new params for endSession

- store/src/java/com/zimbra/cs/lmtpserver/LmtpAddress.java
When we send email to above users (having special hindi characters like joined letter) LMTP throws error "Syntax error in recipient address"
for e.g. अजिंक्य@test.com, उत्तम@test.com
Verify this work using this fix.
> NICPS-494: IDN - LMTP - support Hindi Email with special characters

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
NICPS-537: Add new Zimbra attribute for the file type check
An attribute named zimbraFileTypeCheckEnabled is added. This boolean attribute is responsible for enabling/disabling of file content type check while uploading a file in the briefcase.
> NICPS-537: Add new Zimbra attribute for the file type check

- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
**Problem:**
If it is configured to use Ephemeral (zimbraEphemeralBackendURL is set to ssdb:host.domain.com:8888), the zimbraLastLogonTimeStampFrequency is not honored.
**Fix:**
Remove "if" statement so that zimbraLastLogonTimeStampFrequency is always used.
> ZBUG-674: changed to honor zimbraLastLogonTimeStampFrequency even when ephemeral store is used

- store/src/java-test/com/zimbra/cs/imap/Hacker.java
- store/src/java-test/com/zimbra/cs/imap/MemcachedImapCacheTest.java
- store/src/java/com/zimbra/cs/imap/DiskImapCache.java
- store/src/java/com/zimbra/cs/imap/ImapCredentials.java
- store/src/java/com/zimbra/cs/imap/MemcachedImapCache.java
- store/src/java/com/zimbra/cs/index/query/parser/Token.java
- store/src/java/com/zimbra/cs/io/SecureObjectInputStream.java
- store/src/java/com/zimbra/cs/service/util/ItemId.java
- store/src/java/com/zimbra/cs/session/PendingLocalModifications.java
- store/src/java/com/zimbra/cs/session/PendingModifications.java
- store/src/java/com/zimbra/cs/store/file/BlobReference.java
- store/src/java/com/zimbra/cs/util/Zimbra.java
Fixing ObjectInputStream to de-serialize only specified classes .
Followed the techniques specified in
https://www.owasp.org/index.php/Deserialization_Cheat_Sheet#Java
 Add a SecureObjectInputStream to only de-serialize class specified in deserializing.
-------
Removed the code that initializes the MessageChannel. Tried to remove the MessageChannel code completely however it is being reference CrossMailbox notification and RemoteSoapSesssion. Hence decided against it.
Testing: Added unit test to verify that an incorrect object during de serialization causes exception and is not read.
 Installed the code changes on ZCS and verified that current functionality is not affected Verified that IMAP functionality is not affected .
Verified no new exceptions are thrown in the logs
Tests | Failures …
> ZCS-6695 Fixing ObjectInputStream to deserialize only specified class

- common/src/java/com/zimbra/common/localconfig/LC.java
Modified the JVM parameters and cacerts location to work with JDK 11.
Tested ZCS with these changes and JDK 11
Verified that all ZCS services start without any issue and ZCS is functional
> Changes neede for JDK 11

- common/src/java/com/zimbra/common/soap/AccountConstants.java
**Problem:** When license store is installed, hab roots should be returned in GetInfoResponse.
**Fix:** Added <habRoot> element in the response. Format will be as below
```
<habRoot>
<hab>xxxxx</hab>
....
</habRoot>
```
**Testing done:** Tested GetInfo api manually from SoapUI, and hab root is being return in the response.
**Testing to be done by QA:** Verify GetInfoResponse with and without license store installed.
**Linked PR:** https://github.com/Zimbra/zm-license-store/pull/4
> ZCS-6830 Modify getinfo api to get hab roots

- store/src/java/com/zimbra/cs/rmgmt/RemoteMailQueue.java
This an official integration of the already approved pull request https://github.com/Zimbra/zm-mailbox/pull/794
Removed case alterations to queue IDs.
In order to support the long format of Postfix queue IDs, which is
case-sensitive, IDs are no longer subject to case alterations.
> ZCS-6225:Postfix long queue IDs support.

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java-test/com/zimbra/cs/service/FeedManagerTest.java
- store/src/java/com/zimbra/cs/service/FeedManager.java
Issue:
* FeedManager has no target address restriction of user supplied RSS feed locations, resulting in potential misuse of the feed resource for SSRF to internal addresses. 
Solution:
* Restrict feed address from all private addresses by default with a localconfig (for now) blacklist which supports CIDR notation and single addresses - no wildcards.
Potential Solution Issue:
*  _Update: Private can be configured with the blacklist._ Restricting private addresses may cause problems in a corporate environment where an RSS service is available in a private ip range for employee use - this solution would prevent access if no public range ip is available for the service.
Other:
IPv6 feeds are not supported due to HttpURL parsing. (unchanged)
* Tested in webclient with …
> ZBUG-913 SSRF vulnerability - restrict feed manager target addresses.

- common/src/java/com/zimbra/common/localconfig/LC.java
Added --module-path for loading jcharset and zimbra-charset  issue.
Verified that the mime mentioned in ZCS-6956 is correctly injected
> ZCS-6956 Fixing charset loading  issue

- common/src/java/com/zimbra/common/util/L10nUtil.java
- store/src/java/com/zimbra/cs/account/accesscontrol/RightCommand.java
- store/src/java/com/zimbra/cs/service/account/ToXML.java
`GetAllLocalesRequest` looks in the appropriate L10nMsg.properties
file for a localised string to describe a locale name.  For many of
them, there are descriptions but for some there aren't.  When there
aren't, another string is used.
`GetAllRightsRequest` looks in ZsMsgRights.properties for certain keys.
Again, if it isn't found, the code uses another string.
On the basis of the above 2 scenarios, added a new `L10nUtil.getMessage`
signature which has a selector on whether it is worth logging the
whole exception if MissingResourceException is thrown.  The default is
the same as it used to be but the 2 call sites above have been changed
to be less chatty.
Logging has also been improved with more details.  In particular, the
old error message implied that a resource bundle hadn't been found …
> ZCS-6759:Suppress MissingResourceException

- store/src/java/com/zimbra/cs/html/DefangFilter.java
Reworked the change introduced by Sneha baed on discussion with Prashant Surana.
Used StringBuilder instead on string concatenation
Applied the logic of chunking and sanitizing to all style values.
Verified all unit test pass
Verified that the mimes do not cause a CPU spike
> ZCS-6944 Reworking the change

- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
**Problem:**
A target account of ChangePasswordRequest is not written in mailbox.log. A system operator cannot know who actually changes his/her password from mailbox.log. It is a problem at investigating or tracking user's behavior.
**Root cause:**
There was not a logging code after password change action.
**Fix:**
Add a logging code to `LdapProvisioning.setPassword(Account, String, boolean, boolean)`. It is called at ChangePasswordRequest or SetPasswordRequest. It is not called at CreateAccountRequest.
> ZCS-7079: logging target account of ChangePasswordRequest

- common/src/java/com/zimbra/common/gql/GqlConstants.java
- soap/src/java/com/zimbra/soap/account/type/ContactGroupMember.java
- soap/src/java/com/zimbra/soap/account/type/ContactInfo.java
- soap/src/java/com/zimbra/soap/mail/type/ContactGroupMember.java
- soap/src/java/com/zimbra/soap/mail/type/ContactInfo.java
* Differentiate between account/mail namespace duplicate models for both `ContactInfo` and `ContactGroupMember` to resolve collision conflict when generating schema.
> ZCS-6952 Fix class namespace conflict for gql contacts.

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/html/DefangFilterTest.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/html/DefangFactory.java
- store/src/java/com/zimbra/cs/html/OwaspHtmlSanitizer.java
**Problem:** Make OWASP filtering configurable
**Fix:**
- Created OwaspHtmlSanitizer class for owasp filtering which will be implemented later
- Created zimbraUseOwaspHtmlSanitizer, boolean ldap attribute at globalConfig level
- Updated DefangFactory class to use zimbraUseOwaspHtmlSanitizer to decide which defang class to use for filtering.
- Build successful.
- zimbraUseOwaspHtmlSanitizer is available at global config level with default value as TRUE
- Added unit test
[report.zip](https://github.com/Zimbra/zm-mailbox/files/3062667/report.zip)
- Make sure zimbraUseOwaspHtmlSanitizer is available at global config level with default value TRUE.
- If zimbraUseOwaspHtmlSanitizer set false, HtmlDefang filter should be used.
> ZCS-6871 Make OWASP filtering configurable

- soap/src/java/com/zimbra/soap/type/ShareInfo.java
* Allow grantee name and id to be null in graphql responses - as it may be in soap responses.
* This resolves an exception when gql is parsing responses that do not have a granteeName or granteeId.
Testing basic fetches on zdev and local machines with data highlighting this issue.
See jira ticket.
> ZCS-7020 Grantee name and id can be null in share info elements.

- store/src/java/com/zimbra/cs/imap/ImapPath.java
- store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
When ZWC is used to add a shared folder for "All applications", the resulting sub-folder hierarchy was not visible via IMAP.
This regression was introduced when IMAP daemon support was added.  A mountpoint was rejected when accumulating paths because the referent's folder id was the user root whereas before (and now again) the folder's id is compared.
Fix validated using Thunderbird to subscribe to folders.
New RunUnitTests test passes against local imap, remote imap and imap daemon.
> ZBUG-795 imap shared mailbox not visible

- common/src/java/com/zimbra/common/net/ProtocolSocketFactoryWrapper.java
- common/src/java/com/zimbra/common/net/SecureProtocolSocketFactoryWrapper.java
- common/src/java/com/zimbra/common/net/SocketFactories.java
- common/src/java/com/zimbra/common/soap/SoapHttpTransport.java
- common/src/java/com/zimbra/common/util/ZimbraHttpConnectionManager.java
- store/src/java/com/zimbra/cs/service/FeedManager.java
Fixed the code that created the Sockets.
For FeedManager changed the code for reading content type from HttpResponse
Verified that the following error is no longer seen
[] INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://localhost:7071: Socket is closed
[] INFO: Retrying request to {s}->https://localhost:7071
Verified by running the failing SOAP automation test case
/opt/qa/soapvalidator/data/soapvalidator/MailClient/Folders/folders_url.xml
> ZCS7167 Fixing issues found in SOAP automation

- store/src/java-test/com/zimbra/cs/html/DefangFilterTest.java
**Problem:** DefangFilterTest broken
**Fix:** Fixed unit test to use LC
**Testing done:** Tested unit test
```
$ant -Dtest.name=com.zimbra.cs.html.DefangFilterTest  single-test
Buildfile: /Users/chinmay.pathak/Github/zm-mailbox/store/build.xml
build-init:
make-dirs:
[echo] Creating dirs under /Users/chinmay.pathak/Github/zm-mailbox/store/build/dist
test.if.ivy.available:
download-ivy:
init-ivy:
Trying to override old definition of task antlib:org.apache.ivy.ant:buildobr
Trying to override old definition of task antlib:org.apache.ivy.ant:buildobr
resolve:
Trying to override old definition of task antlib:org.apache.ivy.ant:buildobr
[ivy:resolve] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = …
```
> ZCS-7168 fixing unit test

- common/ivy.xml
- store/ivy.xml
- store/src/java/com/zimbra/cs/service/authenticator/SpnegoAuthenticator.java
- store/src/java/com/zimbra/cs/servlet/ZimbraLoginService.java
issue: related to jetty 9.4.15.xxx
fix : in jetty 9.4.xxx some security related classed has been removed, so fixed all compile time errors. Tested that build passed successfully.
Testing to be done: Test with upgraded jetty version that everything works fine.
Linked PR: 
https://github.com/Zimbra/zm-jetty-conf/pull/4
https://github.com/Zimbra/zm-zcs-lib/pull/42
> zcs-6542:jetty upgrade to 9.4.15.xxx

- client/src/java/com/zimbra/client/ZMailbox.java
Fixed the code used for uploading the file.
Fixed the content type used while uploading a file using zimbra-client.
Ran the following SOAP automation, they are all passing.
/opt/qa/soapvalidator/data/soapvalidator/RestServlet/Fmt/tgz/resolve/resolveBasic.xml
/opt/qa/soapvalidator/data/soapvalidator/RestServlet/Mail/Post/basic.xml
/opt/qa/soapvalidator/data/soapvalidator/RestServlet/Fmt/vcf/contact_vcf.xml
/opt/qa/soapvalidator/data/soapvalidator/RestServlet/Fmt/xml/message_xml.xml
/opt/qa/soapvalidator/data/soapvalidator/RestServlet/Mail/Part/part_basic.xml
/opt/qa/soapvalidator/data/soapvalidator/RestServlet/Mail/rest_blockedAttachments.xml
/opt/qa/soapvalidator/data/soapvalidator/MailClient/Contacts/ContactBackup/ContactBackup_ZCS-2730.xml
> ZCS-7167 Fixing error to fileupload in SOAP automation tests

- common/src/java/com/zimbra/common/localconfig/LC.java
* Few changes to default localconfig mailbox options arguments for G1GC
* Shift lower/upper boundaries for new young gen size from 5%/60%.
* Lower gc log level to reduce latency from excess writes.
See jira ticket for load testing results.
This resolves part of the known performance issues, more to go; see ticket for full discussion.
> ZCS-7106 GC optimization config defaults

- store/src/java/com/zimbra/cs/fb/ExchangeEWSFreeBusyProvider.java
issue : id was not getting in GetFreeBusyResponse in case of nodata response as the value of name which was set for `FreeBusy.nodataFreeBusy(name, startTime, endTime);` was null. 
fix: removed name and added emailAddress. Now getting id as part of nodata freebusy response.
Tested with local set up for both nodata and free status.
Tested to be done by QA:
For all freebusy scenario id should come as part of freebusy response.
> fixed for getting user id in freebusy response

- client/src/java/com/zimbra/client/ZMailbox.java
* Skip item id cache refresh if the ZMailbox instance cannot acquire account id.
* Resolves an issue of failing to fetch the account id for each item to be cached in the keying process, which resulted in many GetInfoRequests and lengthy load times when the refresh event was triggered by server side response to various jsp tag soap requests (refresh block in soap response)
Local tests with stale state session to trigger refresh.
See jira ticket.
> ZBUG-527 Check for invalid auth before attempting to refresh item id in cache.

- common/ivy.xml
- store/ivy.xml
Previously upgraded to 9.4.15.xxx which I have tested with the 9.4.15 package provided by @Prashantsurana  and it was working as expected. As the latest jetty version has been released with 9.4.18.xxx it is better to use it. I have tested with 9.4.18.xxx deb package provided by @rupalid and it is working fine. Tested with ZWC as well as mac outlook. all basic mail functionalities are working fine.
Testing:
QA needs to verify it.
Related PR
https://github.com/Zimbra/zm-mailbox/pull/908
> zcs-6542 : upgrade jetty to 9.4.18.xxx

- common/src/java-test/com/zimbra/common/zmime/ZInternetHeaderTest.java
- common/src/java/com/zimbra/common/zmime/ZInternetHeader.java
Added code to ignore if encoded header has space which is not encoded and char set is UTf-8
Added unit test.
1348 | 0 | 0 | 10 | 100.00% | 2447.997
> ZBUG-1022 Fixed email subj rendering for incorrectly encoded subj

- store/src/java/com/zimbra/cs/db/DbSearch.java
- store/src/java/com/zimbra/cs/index/ResultsPager.java
[Problem]
Copy action doesn't stop when more in the following case.
- 500 message exists in a folder
- some of messages have the same value in a field specified by sortVal of SearchRequest
- cursor of SearchRequest points one of them
[Root cause]
When SearchRequest is processed on mailstore, SELECT command is executed like this.
`SELECT mi.id, mi.type, mi.parent_id, mi.folder_id, mi.prev_folders, mi.index_id,mi.imap_id, mi.date, mi.size, mi.locator, mi.blob_digest, mi.unread, mi.flags, mi.tag_names, mi.subject,mi.name, mi.metadata, mi.mod_metadata, mi.change_date, mi.mod_content, mi.uuid, mi.date AS sortcol FROM mboxgroup5.mail_item AS mi FORCE INDEX (i_folder_id_date) WHERE mi.mailbox_id = 5 AND ((mi.type = 5 OR mi.type = 16) AND mi.folder_id = 44173) ORDER BY sortcol DESC, mi.id LIMIT …
> ZBUG-715: added DESC to "order by mi.id" to find correct item specified by cursor in message search

- store/src/java/com/zimbra/cs/zimlet/ZimletUtil.java
ZCS-7500 Fixing null parameter while uploading attachment
verified the following command works in a multi node deployment
zmzimletctl deploy /opt/zimbra/zimlets-network/com_zimbra_smime.zip
[] INFO: Deploying Zimlet com_zimbra_smime in LDAP.
[] INFO: Installing Zimlet com_zimbra_smime on this host.
[] INFO: Deploying on service node zdev-vm011.eng.zimbra.com
[] INFO: post to server zdev-vm011.eng.zimbra.com, data size 543486
[] INFO: Deploy initiated. Check the server xxxx's mailbox.log for the status.
> ZCS-7500 Fixing null parameter

- client/src/java/com/zimbra/client/ZMailbox.java
Fixing "java.lang.IllegalArgumentException: MIME type may not contain reserved characters
at org.apache.http.util.Args.check(Args.java:36)" while moving item from shared folder to user folder.
Verified that the above exception does not happen an email or email with attachment is moved.
> ZCS-7568 Fixing exception while moving email to another folder

- common/src/java/com/zimbra/common/util/ZimbraHttpConnectionManager.java
- common/src/java/com/zimbra/common/util/ngxlookup/ZimbraNginxLookUpClient.java
Fixed error related to java.lang.UnsupportedOperationException for a deprected HttpClient method
Since on a split UI node no service webapp is installed. The SocketFactories  and the default PoolingHttpClientConnectionManager was created without SSLContext.
Added code to initialize PoolingHttpClientConnectionManager  with SSLContext. Verified by installing on Split UI setup that login into web client is possible.
> ZCS-7581 Fixing broken Split UI setup

- store-conf/conf/owasp_policy.xml
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
- store/src/java/com/zimbra/cs/html/owasp/OwaspPolicy.java
- store/src/java/com/zimbra/cs/html/owasp/OwaspPolicyProducer.java
Added 'display' css property into whitelist for owasp html sanitization.
Made the css whitelist configurable through owasp policy xml file
Added junit test.
> ZCS-7621:Whitelist display CSS property in owasp

- store/src/java/com/zimbra/cs/service/UserServlet.java
- store/src/java/com/zimbra/cs/service/UserServletContext.java
- store/src/java/com/zimbra/cs/service/formatter/HtmlFormatter.java
**Problem:**
buttons and links don't work in Calendar in separate window on web-split environment.
**Root cause:**
The behavior is different between on single server environment and web-split environment.
**on single server environment:** 
GET request has view and date params like
`https://SERVER/service/home/test1@xmail.test.com/Calendar.html?view=week&date=20181026`
**on web-split environment:** 
GET request is sent to Mailstore. Then Mailstore generates and sends GET request to UI server (via proxy).
https://dev.zimbra.com/h/rest?
zimbra_target_item_color=0&
CsrfTokenCheck=false&
zimbra_request_uri=/home/test1@dev.zimbra.com/Calendar.html&
zimbra_target_account_prefSkin=harmony&
zimbra_target_account_prefCalendarDayHourEnd=18&
zimbra_target_item_type=folder&
zimbra_target_item_id=10& …
> ZBUG-859: added params for restCalendar

- store/src/java/com/zimbra/cs/account/AuthToken.java
- store/src/java/com/zimbra/cs/account/ZimbraAuthToken.java
- store/src/java/com/zimbra/cs/account/ZimbraJWToken.java
- store/src/java/com/zimbra/cs/service/FileUploadServlet.java
- store/src/java/com/zimbra/cs/service/doc/SaveDocument.java
Fixed the code that set the auth token cookie on the Httpclient request object.
Verified that zmboxmove command works in a multi node setup. 
Verified that the account is moved to target server.
> ZCS-7655 Fix MailboxMove API

- store/src/java/com/zimbra/cs/service/admin/GetDomainInfo.java
Issue:  zimbraFeatureResetPasswordStatus was removed from bootstrapInfoAttrs list.
```
zmprov md <domainName> zimbraFeatureResetPasswordStatus enabled.
Trigger domainInfo request for given domain.
Expected : zimbraFeatureResetPasswordStatus should be returned in the response
Actual: zimbraFeatureResetPasswordStatus is not returned in the response
```
Fix : Added `zimbraFeatureResetPasswordStatus` in bootstrapInfoAttrs.
Test: Forgot password flow is working as expected.
> zcs-7675:Domainfo request is not returning 'zimbraFeatureResetPasswordStatus' attribute

- store/src/java/com/zimbra/cs/zimlet/ProxyServlet.java
Removed the deprecated method.
Verified that when a url is passed to a proxy servlet it opens the target URL and no 503 is not seen.
Verified that Basic Auth also works for target URL
> ZCS-7660 ProxyServlet not working

- common/src/java/com/zimbra/common/soap/SoapHttpTransport.java
- common/src/java/com/zimbra/common/util/ZimbraHttpConnectionManager.java
FIxed the code that set the auth token in cookie for HttpClient object.
Verified that login and logout works without errors with  zimbraCsrfTokenCheckEnabled set to true and false.
Verified no connection pool shutdown error is seen in the logs.
> ZBUG-1080 Fixing code that sets auth token in cookie

- store/src/java/com/zimbra/cs/service/mail/ToXML.java
GetFolderRequest is not returning "permissions" data
Fix:
Adding perm attribute for mounted folders
> ZCS-7686:Make GetFolderRequest return "permissions" data

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/service/account/Auth.java
**Issue:**
When the accounts has aliases, accounts kept getting locked out due to bots trying to login with alias instead of actual email address. Currently there is no option to block the alias login.
**Fix:**
Added a Local config which will be `true` by default that means alias login is enabled.
If we want to block alias login modify the Local config value to `false`. After that all alias login will be blocked.
**Test:**
- Manual testing done. Created an alias for an account. default local config value is set to `true`, so the user successfully logged in.
- when the local config value modified to `false`, all alias login blocked.
- Test that login with email address works.
- Login with alias account works.
- when local config set to `false`, only alias …
> zcs-7680 : Ability to have an option to block login using the alias

- store/src/java-test/com/zimbra/cs/account/MockProvisioning.java
- store/src/java-test/com/zimbra/soap/AuthRequestTest.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/service/account/Auth.java
- store/src/java/com/zimbra/cs/util/AccountUtil.java
**_Issue :_** 
- Alias login was successful though `LC` value `alias_login_enabled` set to `false` in case of `IMAP`, `POP` and `EWS` as well because auth provisioning is different for different protocol. 
- We had only a check in `Auth.java` where only `ZWC` login request was getting blocked for alias but all other auth request were getting successful. 
- Another problem was that when we send the whole email address in request and `LC` set to `false` the login request was getting failed where as when we send only the display name like `test` instead of `test@test.com` it was getting successful.
**_Fix:_**
- Ultimately when auth request comes from any other client other than ZWC like IMAP, POP and EWS, it encounters `prov.authAccount()` call which verifies the password in …
> zcs-7680 - Added alias check at common place and added unit test

- store/src/java/com/zimbra/cs/account/krb5/Krb5Login.java
Java 1.9 has a change with kerbros authentication which breaks Zimbra's Kerberos Auth
https://bugs.openjdk.java.net/browse/JDK-8173069
Applied the patch given in jira ticket
Fixed the exception raised due to the failed logout attempt, the verify password function returns false and a login is not attempted.
Zimbra 8.7 was JDK 1.7 and Zimbra 8.8 is JDK 1.11. This issue started with JDK 1.9.
> ZBUG-1087: Java - Kerberos authentication is broken on upgrade

- store/src/java/com/zimbra/cs/util/AccountUtil.java
issue :  The current logic had a check for `contains` which might result the condition as success and allow an alias login. found another scenario which is mentioned in the [ZCS-7680](https://jira.corp.synacor.com/browse/ZCS-7680). Need to identify ways to fix that.
Fix: Removed the `contains` check and removed the empty `return` as well. if the login email address has domain value and account name also has domain value then comparing both values otherwise taking out the local parts and comparing both values and based on this throwing exception.
Test: Tested that alias login is blocked when LC value is `false` and alias login works when LC value set to `true`.
> zcs-7680 : Modified logic for alias check

- store/src/java/com/zimbra/cs/dav/client/WebDavClient.java
- store/src/java/com/zimbra/cs/dav/service/DavServlet.java
Issue:
Getting NPE due to invoking of super() method for empty response (SC.NO_CONTENT) in DELETE, COPY and few other request methods in UserServlet.java at line no. 939.
Fix:
Implement a custom method which does not invoke HttpInputStream.
/opt/qa/soapvalidator/data/soapvalidator/Dav/CalDav/Calendar/Appointments/DeleteAppointment.xml
/opt/qa/soapvalidator/data/soapvalidator/Dav/CalDav/Calendar/Folders/DeleteCalendar.xml
/opt/qa/soapvalidator/data/soapvalidator/Dav/WebDav/copy.xml
/opt/qa/soapvalidator/data/soapvalidator/Dav/WebDav/lock.xml
/opt/qa/soapvalidator/data/soapvalidator/Dav/WebDav/move.xml
Also fixes tests failing previously in -
/opt/qa/soapvalidator/data/soapvalidator/Dav/CalDav/Calendar/Mountpoints/DeleteAppointment.xml
Related soap-harness PR - …
> ZCS-7765: Fix DAV related failures in zm-soap-harness legacy

- store/src/java/com/zimbra/cs/util/SpoolingCache.java
Added code to reset the objectoutputstream to flush the buffer after each write and reset the stream's internal object cache.
Verified with mailbox move in a multinode setup that no exceptions are thrown
> ZBUG-1112 reset the oos to flush buffer

- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
Given the existence, for example, of a zimbraDomain
subdomain.example.com and of a zimbraDomain example.com, deleting the
domain example.com the ldap object dc=example,dc=com cannot be deleted
given the presence of the domain subdomain.example.com .
Instead all zimbra-related attributes are removed from the object
dc=example,dc=com .
The code however just removes attributes related to the zimbraDomain object
class but not the amavisAccount and DKIM object Classes with their
related attributes, since quite likely the code predates the introduction of those
objectClasses/attributes at domain level.
The fix is to handle the removal of those as well.
Also bypassing/clearing the domain Cache is necessary to get an up-to-date domain Object before clearing the attributes and to remove it from …
> Fix: incomplete attribute removal deleting domains

- store-conf/conf/owasp_policy.xml
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
- store/src/java/com/zimbra/cs/html/owasp/HtmlElement.java
- store/src/java/com/zimbra/cs/html/owasp/OwaspPolicy.java
Issue:  Owasp was removing style attribute of image component
eg.
> ZCS-7784: Img tag style attribute getting truncated

- store/src/java/com/zimbra/cs/service/FileUploadServlet.java
Issue:
The convertd native process is stuck and CPU spikes if the .har file is uploaded to briefcase or in attachment
Fix:
When .har file is uploaded its content type was being set to 'application/octet-stream' by default(retrieved from HttpServletRequest instance)
But, the file actually contains data in json format. the convertd is trying to convert the document based on 'application/octet-stream' and failing.
Changing the content type of the uploaded .har document to 'application/json' resolves the issue.
> ZBUG-711:convertd exhausts system memory when .har file is indexed

- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
authCtxt is null when received from changePassword.
Adding null check.
verified that  alias login works and when alias_login_enabled is false, alias login fails.
Verified Change password works
> ZCS-7870 Fixing NPE

- store/src/java/com/zimbra/cs/service/mail/CheckSpelling.java
Problem:  Spell check was not working
Approach And Fix: After checking, found that spellcheck has an issue with special chars so added "UTF-8" to fix it.
Testing done: Created signature with the MIME attached to the ticket and with few manual sample signatures and verified the spellcheck functionality.
Testing to be done by QA: Verify the spellcheck using the MIME attached to the ticket
> ZBUG-1109: spell check is not working correctly with 8.8.15

- store/build.xml
Upgrading OWASP library to latest version, which resolves ZBUG-1148
Added fix for ZCS-7497 in new owasp library
Ref PRs:
https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/1
https://github.com/Zimbra/zm-build/pull/154
https://github.com/Zimbra/zm-zcs-lib/pull/54
> ZBUG-1148:Loosing table format with owasp sanitizer

- store/src/java/com/zimbra/cs/zimlet/ProxyServlet.java
**Issue**
ProxyServlet returns a 500 error if the downstream service returns a response with no body.
**Solution**
Check for null on response entity before accessing it.
DELETE requests. See ZCS-7949.
> ZCS-7949 Fix NPE in ProxyServlet response.

- common/src/java/com/zimbra/common/localconfig/LC.java
Implemented a new LC config for not updating auth time in zimbraAppSpecificPassword attr value.
Related PR - https://github.com/Zimbra/zm-twofactorauth-store/pull/10
> ZCS-8181: zimbraAppSpecificPassword (2FA) is not scalable, need to be scalable for millions of accounts

- common/src/java/com/zimbra/common/localconfig/LC.java
As current LC had "password" string in it, we had to use zmlocalconfig -s
Modified LC name to address this issue  - "zimbra_two_factor_apppasswd_update_authtime"
Related PR: https://github.com/Zimbra/zm-twofactorauth-store/pull/11
Related Original PRs:
https://github.com/Zimbra/zm-twofactorauth-store/pull/10
https://github.com/Zimbra/zm-mailbox/pull/975
> ZCS-8181: update LC name to zimbra_two_factor_apppasswd_update_authtime

- store/build.xml
- store/ivy.xml
Upgrading owasp Antisamy library to latest version, with added fix for ZBUG-1174 in new antisamy library
Ref PRs:
https://github.com/Zimbra/zm-build/pull/157
https://github.com/Zimbra/zm-mailbox/pull/982
https://github.com/Zimbra/zm-zcs-lib/pull/57
https://github.com/Zimbra/antisamy/pull/1
> ZBUG-1174: Web client does not show UTF-8 "Quoted-Printable"

- store/src/java/com/zimbra/soap/SoapEngine.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
**Issue :** 
The option "Save a copy of sent messages to my Sent folder" doesn't work with a persona in the web client.
- UserA has given userB "SendAs" or "Send of Behalf". and selected the option "Save a copy of sent messages to my Sent folder"
- UseB has created a persona for userA and sent an email to userC.  Sent email did't save in userA's sent folder.
When the `SendMsgRequest` comes for `sendAs` and `sendOnBehalf`  from the logged in user account, the request header contains the actual user accountId and in this case we get the target mailbox is the userA, but in case of Persona the header contains the logged in user accountId which is userB, so the target mailbox is always the logged in user mailbox and when the message sent successfully it stores in the …
> zbug-903:Problem with sendAs delegate rights and Save a copy of sent messages to my Sent folder

- store/ivy.xml
Issue:  vulnerabilities in existing commons-compress jar 1.10
Fix: Upgrade commons-compress jar to the latest version 1.19
Related PRs:
https://github.com/Zimbra/zm-zcs-lib/pull/58
https://github.com/Zimbra/zm-genesis/pull/41
https://github.com/Zimbra/zm-soap-harness/pull/95
> ZCS-8013: Third party vulnerabilities in commons-compress

- store/ivy.xml
- store/src/java-test/com/zimbra/cs/service/FileUploadServletTest.java
Issue:
commons-fileupload older version have vulnerabilities in older version.
Fix:
Updating version from 1.2.2 to 1.4
Related PRs:
https://github.com/Zimbra/zm-zcs-lib/pull/56
https://github.com/Zimbra/zm-genesis/pull/40
https://github.com/Zimbra/zm-soap-harness/pull/93
https://github.com/Zimbra/zm-taglib/pull/33
https://github.com/Zimbra/zm-clientuploader-store/pull/3
https://github.com/Zimbra/zm-clam-scanner-store/pull/2
[zcs-8016-soap-tests.zip](https://github.com/Zimbra/zm-mailbox/files/3872885/zcs-8016-soap-tests.zip)
> ZCS-8016: updating commons fileupload version from 1.2.2 to 1.4

- soap/src/java/com/zimbra/soap/admin/type/CountObjectsType.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/ldap/LdapUtil.java
- store/src/java/com/zimbra/cs/ldap/ZLdapFilterFactory.java
- store/src/java/com/zimbra/cs/ldap/unboundid/UBIDLdapFilterFactory.java
- store/src/java/com/zimbra/cs/service/admin/CreateAccount.java
**Raising PR for Chinmay**
**Problem:** Feature wise account count is not maintained and verified.
**Fix:** Added code to maintain and verify EWS account count against the installed license.
- Tested on local dev environment by putting jars.
- if account creation with EWS enabled is blocked, if ews account count reached max allowed count given in the license.
- if modifying account with EWS enabled/disabled, ews account count is validated 1st and then increased/decreased.
- if deleting account which had EWS enabled, ews account count is decreased.
- Verify ews account count behavior with valid license installed while account creation, modification and deletion.
- Verify nothing is broken.(Sanity testing)
**Linked PR:** …
> ZCS-8105 Modify license implementation to verify feature wise count - EWS

- soap/ivy.xml
- store/ivy.xml
Issue: Third-party vulnerabilities in Jackson library
Fix: Upgrade the Jackson library to the latest version
Related PRs:
https://github.com/Zimbra/zm-oauth-social/pull/54
https://github.com/Zimbra/zm-zcs-lib/pull/59
https://github.com/Zimbra/zm-gql/pull/54
https://github.com/Zimbra/zm-gql-admin/pull/1
https://github.com/Zimbra/zm-network-gql/pull/5
> ZCS-8011: Third party vulnerabilities in Jackson databind

- store/src/java-test/com/zimbra/cs/servlet/util/CsrfUtilTest.java
- store/src/java/com/zimbra/cs/servlet/util/CsrfUtil.java
When a SOAP request is sent with Expired auth token and CSRF token enabled. The CSRF token validation fails as auth token is set to null in ZSC when auth token is expired.
Verified that NPE is not thrown
Added unit test
1332 | 0 | 0 | 10 | 100.00% | 245.740
> ZCS-8246 Fixing NPE with CSRF check

- store/ivy.xml
Issue:
Vulnerabilities in older version 1.55 of bouncy castle.
Fix:
Update version to 1.64
> ZCS-8010: updating bouncycastle version to 1.64 from 1.55

- store/build.xml
Removing spring-asm as it is not required by apache cxf and newer version of spring
> ZCS-8018 Removing spring-asm , not required

- common/src/java/com/zimbra/common/soap/Element.java
Issue: Few SOAP test cases were failing due to the dom4j library upgrade, as newly updated library added an exception.
Fix: Update the codebase to catch the exception.
> ZCS-8014: Third party vulnerabilities in dom4j

- .travis.yml
**Issue**
travisci build job is failing due to unsupported `oraclejdk8` version in the new default `xenial` dist.
**Solution**
Use `openjdk8` to match Zimbra's java defaults (rather than swap to `trusty` dist).
Details:
https://travis-ci.community/t/install-of-oracle-jdk8-is-failing/4365
> ZCS-8297 Use openjdk8 for travisci.

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java-test/com/zimbra/cs/service/FeedManagerTest.java
- store/src/java/com/zimbra/cs/service/FeedManager.java
**Issue**
* Adjusting the FeedManager blacklist for individual IPs is too difficult.
* FeedManager blocked address error logging is too generic.
**Solution**
* Add a whitelist for exceptions to the blacklist ranges.
* In localconfig `zimbra_feed_manager_whitelist`
* Same format as blacklist (comma separated individual or CIDR notation IPs)
* Add additional information to logging around blocked IP address.
**Testing**
* See ZCS-8286 for details.
Relates to comments/requests for QoL from #863.
> ZCS-8286 Add whitelist (blacklist exceptions) for FeedManager.

- .circleci/config.yml
**Issue**
Circleci jobs are failing due to the specified image
**Solution**
Update to one of their pre-built jdk8 images that includes node, and remove the explicit node install steps. Also update the home directory to account for the new env.
> ZCS-8298 Replace deprecated circleci image.

- store/src/java/com/zimbra/cs/ephemeral/EphemeralStore.java
- store/src/java/com/zimbra/cs/extension/ExtensionDispatcherServlet.java
- store/src/java/com/zimbra/cs/extension/ExtensionHttpHandler.java
This is a backport.
**Issue**
Existing singleton ephemeral store instance is not flexible enough for extensions to make changes to properties such as the attribute encoder.
**Solution**
Allow explicitly retrieving a new instance if the factory implements support for it.
**Changes**
* Add defaulted `getNewStore` method that ephemeral stores can override
* This allows them to acquire an instance which no other process can alter.
* Backport extension http handler PUT, DELETE support (this is unrelated to the ephemeral issue, I can split this off into another PR if necessary)
See Also:
Zimbra/zm-ssdb-ephemeral-store#12
> Ephemeral additions and backport extension http method support

- store/src/java/com/zimbra/cs/db/DbDataSource.java
In ZCS 8.8.15_GA_3869, external accounts that are larger than 4 GiB fail to sync because a database query returns a number that does not fit into an integer, but `getDataSourceUsage()` attempts to call `ResultSet.getInt()` on it.
This raises an SQLException, which gets eventually converted into a message similar to the following, which ends up being displayed to the user:
> Error: system failure: Folder sync failed, system failure: Synchronization of folder '/DATASOURCE/Inbox' failed, system failure: UID FETCH failed: com.zimbra.cs.mailclient.CommandFailedException: UID FETCH failed: Error in response, UID FETCH failed: Error in response, Exception in response handler, system failure: Unable to get size of dataSource DATASOURCE, Out of range value for column 'sum(mi.size)' : value …
> Fix sync issues with external accounts > 4GiB

- common/src/java/com/zimbra/common/localconfig/LC.java
**Problem:** If EAS protocol version is updated to support 16.1, account can not be configured on iPhone
**Fix:**
- Provision command updated to support DeviceInformation in the request
- Added supported protocol version methods
**Testing done:** Device configured account with EAS 16.1 and mails are syncing on iPhone
- Verify accounts can be configured with EAS 16.1
**Linked PR:**
https://github.com/Zimbra/zm-sync-common/pull/7
https://github.com/Zimbra/zm-sync-store/pull/15
> ZCS-8365 Support for Active Sync protocol till 16.1

- build-ivysettings.xml
- common/ivy.xml
- common/src/java/com/zimbra/common/localconfig/LC.java
- store/conf/attrs/zimbra-attrs.xml
- store/ivy.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
TLS1.0 and TLS1.1 support are going to expire in all major browsers, so we are making it off by default.
If users want to use it, they can on it by setting the values of some LDAP variables manually.
> ZCS 8290: Upgrade TLS in Zimbra classic

- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/service/mail/ParseMimeMessage.java
- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
- store/src/java/com/zimbra/cs/service/util/ItemId.java
**_Issue:_**
Not able to send an email with send-as with a persona and gets the following error after updating Patch 5 on ZCS 8.8.15. Below is the exception
>2019-12-24 01:57:47,277 WARN  [qtp1225197672-10224:https://10.15.8.161/service/soap/SendMsgRequest] [name=user1@labzimbra.com;aname=user2@labzimbra.com;mid=18;oip=10.15.32.83;port=40532;ua=ZimbraWebClient - G
C79 (Win)/8.8.15_GA_3890;soapId=2be84d02;] SoapEngine - handler exception
com.zimbra.cs.mailbox.MailServiceException$NoSuchItemException: no such message: 367
ExceptionId:qtp1225197672-10224:https://10.15.8.161/service/soap/SendMsgRequest:1577132867277:7fc26d2ff004b110
Code:mail.NO_SUCH_MSG Arg:(itemId, IID, "367")
at com.zimbra.cs.mailbox.MailServiceException.NO_SUCH_MSG(MailServiceException.java:219)
at …
> zbug-1292:user is not able to send an email using send-as (persona) with an attachment

- build-ivysettings.xml
Maven central repo now supports https only also added support for orgPath 
orgPath
The organisation name where '.' has been replaced by '/'. This can be used to configure Maven 2-like repositories.
Cleared ivy2 cache and verified build is working.
> ZCS-8464 Fixing maven move to https only

- common/src/java/com/zimbra/common/localconfig/LC.java
- common/src/java/com/zimbra/common/soap/SoapHttpTransport.java
Add code to set socket timeout on request config object based on the value of member variable mTimeout.
SoapCLI command set timeout in old http client to 0 which meant infinite. '0' is not longer infinite with new httpclient, so setting it to Integer.MAX_VALUE.
Verified by running zmmboxmove , zmbackup and zmrestore that read timeout is no longer observed.
> ZBUG-1283 Read timeout with new HttpClient

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
Add attribute at Cos and account level
zimbraFeatureMobileAppEnabled
zimbraFeatureModernDesktopEnabled
This should be returned in the GetInfo Response license block
Testing Instructions:
Check the response of "GetInfoRequest" soap call, it should return values of above attributes in the license block
`zmsoap -z -m t1@`zmhostname` GetInfoRequest/ @sections="mbox,prefs,attrs,props,idents,sigs,dsrcs,children" -t account`
> ZCS-8474: Add new Feature enable attributes for Zimbra 9

- store/src/java/com/zimbra/cs/account/ldap/AutoProvision.java
- store/src/java/com/zimbra/cs/filter/FilterUtil.java
- store/src/java/com/zimbra/cs/mailbox/Notification.java
- store/src/java/com/zimbra/cs/service/account/DistributionListAction.java
- store/src/java/com/zimbra/cs/service/account/SubscribeDistributionList.java
- store/src/java/com/zimbra/cs/service/admin/ComputeAggregateQuotaUsage.java
- store/src/java/com/zimbra/cs/service/mail/SendDeliveryReport.java
- store/src/java/com/zimbra/cs/service/util/SpamHandler.java
- store/src/java/com/zimbra/cs/util/AccountUtil.java
- store/src/java/com/zimbra/cs/util/JMSession.java
- Updated code to use domain level value (if set) for zimbraSmtpHostname.
- Along with Read receipt and receiving notifcation, also fixed the other files listed in ticket description.
Verified Read Receipt and Receiving Notification with domain level value set and empty both.
As per jira ticket comment OOO issue is not reproducible.
Verify fixes done in other files as per ticket description.
> ZBUG-1311: Fix for zimbraSmtpHostname should honour domain level value (if set) instead of server level

- store/src/java/com/zimbra/cs/service/account/AutoCompleteGal.java
Issue:
Any authenticated user can request any GAL account
Fix:
Added condition to check if the authenticated account is on same domain as that of galsync account in request. If not, throw permission denied.
Testing done:
Manual testing done with user and galsync account on different domains
> ZBUG-1094:Broken GAL search filtering

- store/src/java/com/zimbra/cs/store/file/BlobConsistencyUtil.java
Added a condition to check if auth token is expired, if it is then authenticate the admin user before making the SOAP request.
Verified by setting the expiration lifetime to a very low value, add a sleep in the for loop and letting the token expire.
Validated that the token is reauthenticated and zmblobchk continues.
> ZBUG-1295 Check if authtoken is expired abd reauthenticate

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- store/src/db/hsqldb/db.sql
Issue : For ABQ feature two more fields need to be added in zimba.mobile_devices table.
Fix : Added two more columns as per the description in ZCS-8670. created build and checked that new fields are present.
```
zimbra@ip-172-31-20-17:~$ zmcontrol -v
Release 8.8.15.GA.3031.UBUNTU16.64 UBUNTU16_64 NETWORK edition.
zimbra@ip-172-31-20-17:~$ mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 247
Server version: 10.1.25-MariaDB Zimbra MariaDB binary distribution
Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MariaDB [(none)]> use zimbra;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker …
```
> zcs-8670: database changes to support abq

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- store/src/db/hsqldb/db.sql
Revert changes done to ZCS-8670
Added following keys to configs:
ABQMode, Admin email list, notification interval, last notification time.
Added new ABQ devices table which will have following columns:
Device ID
Account ID
Status
Created Time
Created By
Modified time
Modified By
Testing done:
Manual testing by creating and deploying ZCS-build. Check if the database has new changes.
Ref PR: https://github.com/Zimbra/zm-db-conf/pull/10
> ZCS-8730:ABQ-database changes to support ABQ

- store/src/db/hsqldb/db.sql
Indexing is not needed for unit test
ENUM is not supported by H2 database. Adding check() instead.
> ZCS-8730:Fixing unit test

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/admin/message/ABQConfigRequest.java
- soap/src/java/com/zimbra/soap/admin/message/ABQConfigResponse.java
- store/src/java/com/zimbra/cs/db/DbConfig.java
- store/src/java/com/zimbra/cs/util/Config.java
Adding soap API '**AbqConfigRequest**' to manage ABQ config values for Mode, Admin Email List, Notification Interval, Notification Time.
**Operations supported**: Get, Add, Modify.
Admin email list config update uses '**append**' attribute with boolean value to allow appending to existing list on true, replaces on false value.
https://github.com/Zimbra/zm-network-store/pull/40
> ZCS-8510: adding ABQ configs admin api

- store/src/db/hsqldb/db.sql
Issue: we can't keep the device along with account entries in the database.
Fix:
Remove the existing primary key from field device_id and create a new field with name 'id' AUTO_INCREMENT as a primary key. Add Index on fields device_id, account_id, and status
Testing is done:
- Created a new build on branch bugfix/ZCS-8815 on "zm-mailbox" and "zm-db-conf" repos
- Installed the build and verified the DB changes by connecting to MySQL DB.
- Added more details in the ticket
> ZCS-8815: ABQ - update database schema for table abq_devices

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/admin/message/GetABQDevicesListRequest.java
- soap/src/java/com/zimbra/soap/admin/message/GetABQDevicesListResponse.java
- soap/src/java/com/zimbra/soap/admin/type/ABQDevice.java
- store/src/java/com/zimbra/cs/db/DbMailbox.java
Issue : Create Admin API for listing ABQ devices.
Fix: Added API `GetABQDeviceListRequest` which has one optional attribute `status`.
If status is passed then it will get status specific ABQ device list.
If status is not passed, then it will return all the ABQ device list.
Allowed ABQ device status are : `allowed`, `blocked`, `quarantined`. If status is passed other than these allowed values, the API will throw ServiceException.
Test: Tested with passing specific status, it only returns the status specific device list.
If status is not passed then it returns all the device list.
> ZCS-8757: Create Admin API for listing ABQ devices

- common/src/java/com/zimbra/common/soap/SyncAdminConstants.java
- common/src/java/com/zimbra/common/soap/SyncConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/admin/message/AllowDeviceRequest.java
- soap/src/java/com/zimbra/soap/admin/message/AllowDeviceResponse.java
- soap/src/java/com/zimbra/soap/sync/message/AllowDeviceRequest.java
- soap/src/java/com/zimbra/soap/sync/message/AllowDeviceResponse.java
**Issue :** 
rename ResumeDeviceRequest to AllowDeviceRequest. Rename all its related constants and implementations.
**Fix:**
- Renamed the ResumeDeviceRequest to AllowDeviceRequest in both the namespaces (admin and sync).
- Renamed all its constants and implementations.
- Made Device id mandatory and account as optional for the Admin API.
- Added two more unit tests as per the implementation.
**Test:**
- Ran the unit test and all are passing.
- Tested the Admin API with SOAP API for below scenarios.
-  With device id and account by name
- with device id and account by id
- without account and with only device id.
- when device is not passed, throw exception
* QA needs to verify all scenarios for AllowDeviceRequest.
> zcs-8835:rename ResumeDeviceRequest

- store/src/java/com/zimbra/cs/extension/ExtensionDispatcherServlet.java
- store/src/java/com/zimbra/cs/extension/ExtensionHttpHandler.java
* Patch support is needed for oauth extension.
> ZCS-8911 Allow extensions to support HTTP Patch method.

- soap/src/java/com/zimbra/soap/admin/message/RemoveDeviceRequest.java
Issue : modify RemoveDeviceRequest to make account id an optional request element
Fix : Modified admin RemoveDeviceRequest to make account device optional.
1. if account id is present - remove device entry for given account and device id
2. if account id is not present - remove all device entries for given device id
Test: Ran Unit Test and all are passing.
Tested the API manually with SOAP API and it is working as per the condition.
QA needs to verify all scenarios according to the test cases.
> zcs-8836:modify RemoveDeviceRequest

- store/src/java/com/zimbra/cs/service/FeedManager.java
Proxy settings were not taking effect with hew Httpclient.
Created a new HttpClientBuilder and set the proxy settings on it, instead of using the one initialized  when Zimbra starts.
Verified by installing in NIC environment and verified connection through squid proxy to external site happens.
> ZCS-8781 Fixing proxy request with new Httpclient

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/service/FileUploadServlet.java
Issue:
A user can upload malicious files in the Contact section of the mailbox as avatar image for a contact.
Fix: 
Added new LC parameter to have blacklisted content type during any file upload. The value can be regex value to blacklist certain category of files.
Default value is set to 'application/x-mx*' to blacklist all exe files.
Testing done:
Manual testing done. The exe file upload now throws 403 forbidden error.
> ZBUG-1459:Abuse of File upload functionality in Zimbra webmail

- common/src/java/com/zimbra/common/util/Props2Js.java
**Issue:** 
- Currently all zimlets which shows on Admin console has different properties file for supported Locales and the zimlet meta xml contains place holders for  labels and descriptions.
- Initially the modern zimlets does not contain any properties file and the zimlet meta xml contains hardcoded values for label and description. After had a discussion with @silentsakky and as agreed, the modern zimlets will be packaged as legacy zimlets and will contain properties file for default Locale (en_US).
- But the issue is that, the old zimlet name has format of `com_zimbra_xxx` which is a valid variable name in Javascript where as the modern zimlets name is like `zm-x-zimlets-sideloader` which is not a valid variable name in Javascript.
When the server gets …
> ZCS-8822:Support for showing display names for Zimbra X zimlets on admin UI

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
Issue: 
When an account is configured in IMAP with shared folders, the shared folder is not correctly displayed as well as the emails inside the folder is not visible where as the subfolders email are visible.
Fix:
After ZBUG-1096 change, For the logged in account, there was separate collection for owner account folders and separate collection for shared folder(Mountpoint). Though the Folder structure is correctly displayed on Thunderbird client but the shared folder was getting added to the owner's folder collection which was causing the problem and the mail inside the folder is not correctly displayed.
So put a check for shared folder so that it will add to the shared folder collection and maintain correct hierarchy.
Test:
- Tested that the issue with ZBUG-1096 is working where the …
> ZCS-8901 - IMAP: Shared folder does not visible properly as well as can't see emails in shared folder in Thunderbird client

- store/src/java/com/zimbra/cs/mailbox/MailboxListener.java
Issue:
Mailboxlistener unregister() method is not accessible like register method() is for classes. So the listeners registered cannot be de-registered.
Fix: make unregister() public to de-register listener.
> ZCS-8993: making the mailbox listener unergister method accessible from extension

- store/src/java/com/zimbra/cs/service/FileUploadServlet.java
Issue:
When uploading .xls file, the content type of uploaded file was incorrectly being set to application/x-ole-storage
Cause:
The beginning characters of .xls and .docx files resemble to files with content type application/x-ole-storage and application/zip
Fix:
If mime magic returns these content types check by the file extension 
Testing done:
Tested with following file types:
zip, zipx, xls, xlsx, doc, docx, ppt, pptx, 7z, rar, tar, tar.gz
> ZCS-9288:Incorrect content type is displaying for xls and xlsx file type

- store/src/java/com/zimbra/cs/service/mail/ParseMimeMessage.java
- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
- store/src/java/com/zimbra/cs/util/AccountUtil.java
- store/src/java/com/zimbra/soap/SoapEngine.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
**Issue:**
- user A has given sendAs and SOB delegate rights to userB and userA has set the preference to `save Copy of sent messages to  my sent folder `. userB added a persona for userA and sends message using userA but the sent message is not saved to userA's sent folder.
- Problem here is that in case fo sendAs and SOB the context header always contains userA and the server identifies the target account and mailbox and process accordingly. But in case of Persona the context header contains userB and  the server identifies that it has to perform on userB's account and mailbox for which it always stores the sent message to userB's sent folder.
- Also the there is difference in request for sendAs, SOB and persona.
- added an overloaded constructor for …
> ZBUG-903: Problem with 'sendAs' delegate rights and 'Save a copy of sent messages to my Sent folder

- store/src/java/com/zimbra/cs/index/ZimbraHit.java
Fix exception seen in logs  when sorting emails by Unread in a multi node environment when sharer and sharee are on different mbox server.
This exception is seen when search response hit does not contain a 'u' attr.
Verified the fix by sorting by Unread/All in Message and Conversation view in multinode env.
> ZCS-6022 Fixing Exception handling

- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
- store/src/java/com/zimbra/cs/util/AccountUtil.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
Issue:
Draft is not getting deleted when message is send using persona account and draft folder is count is getting increased.
Fix:
- renamed method `isMessageSentUsingPersona` to `isMessageSentUsingOwnersPersona`.
- `AccountUtil.isMessageSentUsingOwnersPersona()` method was always returning false because `fromAddrPrefType` and `fromAddrPrefValue` value is always null as these are the properties set on identity. updated the method to get the values from identity.
- The above modification is required because in case of `sendAs and SOB` sendMsg request contains draft id which is always appended with auth user account id but in case of persona it is only the item id because of which it was not getting deleted.
Test:
Tested that all functionality is working fine and drafts are getting deleted …
> zbug-903:Problem with 'send as' delegate rights and 'Save a copy of sent messages to my Sent folder

- store/src/java/com/zimbra/cs/service/mail/ParseMimeMessage.java
Issue:
If the mime body part contains non-ascii characters, postfix modifies the content-transfer-encoding of the message part to 'quoted-printable', which breaks the signature on receiver side bacause of message digest  mismatch
Fix:
Before signing the message, check if the mime part contains non-ascii characters. If yes, encode the body text with 'quoted-printable' encoding, so that the message contents remain same at the time of signing the message and after receiver receives  the message.
Testing done:
Manual testing done with different types mime parts. Message signature is no longer breaking.
> ZBUG-1035:Content-Transfer-Encoding causes breakage of S/MIME sign

- store/conf/attrs/zimbra-attrs.xml
Following attributes needed to be returned as part of GetInfo:
zimbraPasswordMinAge, zimbraPasswordMaxAge, zimbraPasswordEnforceHistory, zimbraPasswordModifiedTime
Added AccountInfo flag to these attributes.
Testing done:
Manually tested GetInfo response. The response now contains attributes mentioned above.
> ZCS-9066:Update GetInfoResponse to report all Password rules

- store/src/java/com/zimbra/cs/util/AccountUtil.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
**Issue:**
Sending message from IMAP/POP account is not working, throws `service.PERM_DENIED`
Steps to reproduce:
- Add external account as IMAP/POP
- Compose mail with added IMAP/POP account
- send an email to recipient 
**Fix:**
- After zbug-903 fix, we are checking from address to manipulate persona from sendMessage request. But when we configure external account, we create a datasource for that account and when we send message using that external account, we check for from address and try to get the account using that email address. As it is configured as datasource `prov.get()` method returns null and thats why it is throwing exception.
- For the fix, added an utility method to check if the from address is a datasource address or not. If it is a datasource email address then we will …
> zcs-9464:Send message from external IMAP/POP account is not working

- store/src/java/com/zimbra/cs/util/AccountUtil.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
reworked the fix for 903.
If the from address is an external account or a delegated  DL the account is going to be null.
Hence iterate through the identities  for the  account and if we find the from address  in  the Identity, try to  get the account.
If the account is non null then assign the requested Account to this.
removed the datasource code
Tested all the scenarios in 903, ZBUG-1659, 9483
> ZCS-9483 rework the fix for ZBUG-903

- store/src/java-test/com/zimbra/cs/mailbox/ContactTest.java
- store/src/java/com/zimbra/cs/dav/resource/AddressObject.java
- store/src/java/com/zimbra/cs/mailbox/Contact.java
- store/src/java/com/zimbra/cs/mailbox/ContactGroup.java
- store/src/java/com/zimbra/cs/mailbox/ContactMemberOfMap.java
- store/src/java/com/zimbra/cs/mime/ParsedContact.java
- store/src/java/com/zimbra/cs/service/formatter/ContactFolderFormatter.java
- store/src/java/com/zimbra/cs/service/mail/CreateContact.java
- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/qa/unittest/TestContactGroup.java
ZCS-613
Bugzilla: https://bugzilla.zimbra.com/show_bug.cgi?id=107777
Migrate legacy group metadata by stripping accountId for local contacts references.
Most of changes are to pass along the account owner Id.
> Not able to delete a member from a contact group after the upgrade to ZCS 8.7.1

- store/src/java/com/zimbra/cs/service/formatter/ArchiveFormatter.java
While  replying  to  an email  if the original message  is included  as  an  attachment it has no name, hence the NPE.
Added  check for NPE. Verified  scenario for  replying, forwarding  and sending  attachment.
> ZBUG-1605 Fixing NPE

- common/src/java-test/com/zimbra/common/util/UnmodifiableBloomFilterTest.java
- common/src/java/com/zimbra/common/soap/AccountConstants.java
- soap/src/java/com/zimbra/soap/account/message/ChangePasswordRequest.java
- store/src/java-test/com/zimbra/cs/account/MockProvisioning.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
- store/src/java/com/zimbra/cs/service/account/ChangePassword.java
- store/src/java/com/zimbra/cs/service/admin/ModifyCos.java
Added support for dryrun in ChangePasswordRequest. Please  refer to the Jira ticket for req/resp.
Tested by setting up password rules and then try  to change password.
Checked valid failure message is returned when password rule is not followed or a common password is used.
Had to modify ModifyCos as the the Admin console  sends request with attribute zimbraPasswordBlockCommonEnabled but this is not supported in Zimbra 9.0 only in ZimbraX. Thisc  change  should have been made  when CommonPassword block code was ported from Zimbrax
> ZCS-9569 Add support for dry runn in ChangePassword

- store/src/java/com/zimbra/cs/service/account/ChangePassword.java
When dryrun is true and new password is valid and satisfy the rules return an empty response.
Tested with dryrun true and dryrun  false
> ZCS-9569 Return  empty response for success  and dryrun=1

- store/src/java/com/zimbra/cs/service/admin/ModifyAccount.java
**Issue:**
Can not reset the Two factor setup from trusted device clients even though `zimbraTwoFactorAuthEnabled` is set to `FALSE`. For detailed information refer [ZBUG-1555](https://jira.corp.synacor.com/browse/ZBUG-1555). It is because the user has already added the client in to his/her trusted devices list and logging in from that same client.
**Approach & Fix:**
As a fix, tried existing functionality how it works and looking into all possibilities added the code in ModifyAccount.java. The newly added code block would look for the attribute `zimbraTwoFactorAuthEnabled` in the request and its value. If the attribute value is `false` and the value for other two attributes `zimbraFeatureTwoFactorAuthAvailable` and `zimbraFeatureTwoFactorAuthRequired` is set to `true`, it will reset all …
> ZBUG-1555:Can not reset the Two factor setup (zimbraTwoFactorAuthSecret) from trusted device clients

- store/src/java/com/zimbra/cs/imap/ImapMailboxStore.java
When syncing large number of folders to Thunderbird, OutOfMemory error was observed.  Simulated the issue by reducing the heap space.
The SystemFlags variable was being initialized when loading each folder,  this is a static data and can be initialized only once. Made system flags a static variable. Tested with the same reduced heap space, no OOO memory error was observed.
> ZBUG-1694 Fixing OOM error for large no.  of folders

- store/src/java/com/zimbra/cs/service/account/ChangePassword.java
Modified the code  that reads dryrun flag from request. Verified  it works for both JSON and XML format.
> ZCS-9735 DryRun flag when req in JSON format

- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
Add check to fetch mailbox only if it is local, else revert to the requested account mailbox. Verified scenarios in ZBUG-903. All scenarios  except ZBUG-1666 are  working fine.
> ZBUG-1850 Add check if mailbox is local

- store/src/java/com/zimbra/cs/account/accesscontrol/CollectAllEffectiveRights.java
**Problem:** If a delegated admin is given grants on dynamic distribution list created with custom member url, gets `service.INVALID_REQUEST` when trying to do getAllEffectiveRights.
**Fix:**
- in getAllEffectiveRights, all the groups are iterated for searching the member items. and members for dynamic dls with custom member url, can not be fetched. so LdapProvisioning is throwing invalid request service exception.
- so to avoid this situation, if a dynamic dl with custom member url is found, it is ignored and members of that dynamic dl are not searched.
- testing done on local vm with latest develop branch changes
- no more invalid request exception for getAllEffectiveRights. Sample command request and response …
> ZBUG-1577  getting service.INVALID_REQUEST while checking grants of a domain admin using getAllEffectiveRights

- store/src/java/com/zimbra/cs/db/DbMailbox.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
The mailbox quota is stored by the DbMailbox at every end of transaction and loaded during mailbox initiaization.
The stored quota accounts for both mail items quota and addictional quota but the addictional quota is provided at run-time and should not be stored at all.
This fix split the size of the mailbox into mail items and addictional quota and store in database only the mail items size.
In the affected mailboxes a recalculation of the mailbox quota is needed.
> Fix for addictional quota counted multiple times.

- store/src/java/com/zimbra/cs/service/account/ChangePassword.java
Issue: After the [ZCS-9735](https://jira.corp.synacor.com/browse/ZCS-9735) fix for json request, server throws below exception
```
(Windows)/9.0.0_GA_3031;soapId=3407aeab;] SoapEngine - handler exception
com.zimbra.common.service.ServiceException: invalid request: missing required attribute: dryRun
ExceptionId:qtp366590980-151:https://zqa-402.eng.zimbra.com/service/soap/ChangePasswordRequest:1600244644227:31b28a3714bd72b5
Code:service.INVALID_REQUEST
at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:295)
at com.zimbra.common.soap.Element.checkNull(Element.java:412)
at com.zimbra.common.soap.Element.getAttribute(Element.java:347)
at com.zimbra.cs.service.account.ChangePassword.handle(ChangePassword.java:66)
at …
```
> ZCS-9829:Invalid attribute fix

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
Fixing ZBUG-1694 regression. As part of ZBUG-1694, a new LC was added to fix the pagination issue when there are huge number of folders present on an account. So the block 
```
if (ownerSelected.size() <= paginationSize) {
```
was causing the issue because when the size is less then pagination size server was not able to send the folder list which caused the regression [ZCS-9810](https://jira.corp.synacor.com/browse/ZCS-9810) and [ZCS-9820](https://jira.corp.synacor.com/browse/ZCS-9820).
- Done some code refactoring. There was multiple try-catch blocks. so removed those as the exception is already handled in single try block. Moved those codes into same try block
- There was high memory usage when connecting from multiple IMAP sessions. so externally nullifying all the objects so that …
> zcs-9810:Fixing IMAP regression caused by ZBUG-1694

- soap/src/java/com/zimbra/soap/admin/message/SetPasswordRequest.java
- store/src/java-test/com/zimbra/cs/account/MockProvisioning.java
- store/src/java-test/com/zimbra/cs/service/ResetPasswordTest.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
- store/src/java/com/zimbra/cs/service/account/ResetPassword.java
**Problem:**
Add support for `dryRun` in `ResetPasswordRequest`
**Approach:**
Added support for `dryRun` in `ResetPasswordRequest` in the API.
Verified valid failure message is returned when the password rule is not followed when COS settings are changed.
> ZCS-9842: Add support for dry run in ResetPassword

- store/src/java-test/com/zimbra/cs/account/MockProvisioning.java
- store/src/java/com/zimbra/cs/account/Provisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
**Problem:**
When the `ResetPassword` request has `dryRun=true` password is also getting changed.
**Fix:**
Fixed when the request has `dryRun=true` password is not getting changed now.
- Tested when `dryRun` option is provided it satisfies the password rule when `COS` settings are changed and is **NOT** changing the password.
- Tested when the `dryRun` option is not provided then in that case only password is getting changed.
> ZCS-9842: Fixed when request has dryRun=true password should not be changed.

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/localconfig/LC.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/service/admin/ModifyCos.java
**Problem:** `zimbraPasswordBlockCommonEnabled` should be returned in the `GetInfoResponse`
**Fix:**
- Removed LC with name `zimbra_block_common_passwords_enabled` and created ldap attribute with name `zimbraPasswordBlockCommonEnabled` with `accountInfo` flag.
- After doing `generate-getters` found that value for `zimbraPrefClientType` was changed in PREAPPS-4182 but `ZAttrProvisioning.java` did not have the new value i.e. `modern`. So kept it in the PR.
- Verify that value for `zimbraPasswordBlockCommonEnabled` is returned in the `GetInfoResponse` and same is used while checking password strength.
> ZCS-9767 Zimbra9 - Update GetInfoResponse to report zimbraPasswordBlockCommonEnabled password rule

- store/src/java/com/zimbra/cs/mailbox/calendar/ZRecur.java
- store/src/java/com/zimbra/cs/service/mail/CalendarUtils.java
**Problem:** Recurring appointments do not honor max limits set by below attributes.
```
zimbraCalendarRecurrenceMaxInstances
zimbraCalendarRecurrenceDailyMaxDays
zimbraCalendarRecurrenceWeeklyMaxWeeks
zimbraCalendarRecurrenceMonthlyMaxMonths
zimbraCalendarRecurrenceYearlyMaxYears
zimbraCalendarRecurrenceOtherFrequencyMaxYears
```
**Fix & Approach:**
-  When recurring appointment is created/modified, verify it's `count` or `until` with above attribute values and calculate correct `count` or `until` and update in the invite.
- Do above in all 3 cases, when `count` is provided in the invite, when `until` is provided in the invite or invite is created/modifed with never ending recurrence.
- Testing done with new zimbra web client.
- All above attribute value changes require …
> ZCS-9578 Recurring appointment is shown over zimbraCalendarRecurrenceDailyMaxDays/Weeks

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
Adding placeholder attribute for 9.1 release.
- Added below two attribute 
- `zimbraFeaturePowerPasteEnabled`
- default COS value `TRUE`
- `zimbraPrefPowerPasteEnabled`
- default COS value `TRUE`
- Generated getters and setters
- This feature and pref attribute will be returned as part of GetInfo Response.
> ZCS-9850: Add placeholder LDAP attributes to Z9.1

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
ran `ant generate-getters` to finish missed change.
> missed version number changes

- store/src/java-test/com/zimbra/cs/account/MockProvisioning.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
- store/src/java/com/zimbra/cs/service/account/ResetPassword.java
Fixing ResetPasswordResponse that started sending `authtoken` in soap response in `dryRun` support implementation.
- Verified after enabling the following conditions from the admin console for at least 2 Uppercase letters, at least one lowercase letter, at least one numeric value, and password history not to repeat for 5 times.
- Verification done for both XML as well as JSON.
- Verified all the above scenarios.
- Verified if the password was recently used with both XML as well as JSON formats with and without `dryRun` flag:
***XML***
```
zimbra@apps-automation1:~$ zmsoap -vv -m akshat@apps-automation1.synacor.tk -p Akshat123A -f /tmp/ResetPassword.xml
Sending auth request to http://localhost:8080/service/soap
.....
<soap:Body>
<soap:Fault>
<soap:Code> …
```
> Fixing ResetPasswordResponse that started sending  authtoken in soap response

- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
just changed the way of sending the error so that ui does not need any change
**before change**
```
2021-01-29 07:27:17,731 WARN  [qtp366590980-130:https://zdev-vm145.eng.zimbra.com:8443/service/soap/ChangePasswordRequest] [name=bhavin@zdev-vm145.eng.zimbra.com;mid=4;ip=172.16.13.207;port=63908;soapId=520f5928;] SoapEngine - handler exception
com.zimbra.cs.account.AccountServiceException: invalid password: zimbraPasswordBlockCommonEnabled password is known to be too common
ExceptionId:qtp366590980-130:https://zdev-vm145.eng.zimbra.com:8443/service/soap/ChangePasswordRequest:1611923237730:5b4fc290317d42f4
Code:account.INVALID_PASSWORD
```
**after change**
```
2021-01-29 07:41:47,126 WARN  [qtp366590980-127:https://zdev-vm145.eng.zimbra.com:8443/service/soap/ChangePasswordRequest] …
```
> ZCS-9159 correct the way of sending error

- common/src/java/com/zimbra/common/service/ServiceException.java
- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/mailbox/MailServiceException.java
- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
**Problem:**
Change error messages when the customer is not able to send mail.
To support RFE [ZCS-7256](https://jira.corp.synacor.com/browse/ZCS-7256), clients need the summary information to explain the reason for the email send failures, which is been updated as per the following messages codes:
```
* FAILURE             -> ERROR_WHILE_PARSING_UPLOAD                 : For the error while parsing the upload.
* TRY_AGAIN           -> SENDING_MESSAGE_IN_PENDING_STATE_TRY_AGAIN : For waiting for another thread to complete the send.
* PARSE_ERROR         -> INTERNAL_ERROR                             : Error while sending the message during fixup for SENT-BY of ICalendar on behalf of other user.
* INVALID_REQUEST     -> INVALID_DATASOURCE_ID                      : For …
```
> ZCS-8658: Changed error messages when customer is not able to send mail.

- common/src/java/com/zimbra/common/service/ServiceException.java
- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/mailbox/MailServiceException.java
- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
- This PR reverts the earlier commit 15e4c6b.
- Fixed messages to use %s style for strings as per java standards.
[Reference](https://github.com/Zimbra/zm-mailbox/pull/1118)
> ZCS-8658: Revert for commit 15e4c6b and fixing message styles.

- store/src/java/com/zimbra/cs/dav/service/DavServlet.java
**Problem:** when  a '+' character is present in UID in shared appointment, it breaks caldav syncing.
**Fix and Approach:**
- when '+' character is present in uid, the url created to get ics gets broken.
- url is decoded after getting proxy response and before sending it to client.
- removed code which was decoding href after getting response from proxy request
- added encoding of '@' to fix bugzilla bug#106438
- Tested on mac calendar client and thunderbird, both do sync all appointments in shared calendar including appointment with '+' character in UID and `+`, `@` in calendar name.
- verify given scenario
- verify nothing is broken
> ZBUG-1967 Problem synchronizing shared calendar via caldav when a '+' character is present on the EVENT

- store/src/java/com/zimbra/cs/httpclient/URLUtil.java
- store/src/java/com/zimbra/soap/WsdlServlet.java
**Problem:** Admin is not able to open admin console from web client
**Fix:** 
- Added `URLUtil.getSoapPublicAdminConsoleURLForDomain()` to be used in WsdlServlet class
- Updated `URLUtil.getPublicAdminConsoleURLForDomain()` to use `server.getAdminURL()` to fetch correct admin console url
- testing done on local vm by replacing jars
- Admin is able to open admin console from web client
- Verified wsdl behaviour as given by Gren on https://github.com/Zimbra/zm-mailbox/commit/bff882def9f8ba086366e1adad99661864bc6671
- verify both of the given scenarios
- make sure nothing else is broken related to wsdl and admin console url
> ZCS-10418 Admin is not able to open admin console from web client

- store/src/java/com/zimbra/cs/service/account/ResetPassword.java
- store/src/java/com/zimbra/cs/service/mail/RecoverAccount.java
Problem : During Soap Testing, it was found that RecoverAccountRequest throws generic exception rather than MAX_ATTEMPTS_REACHED_SUSPEND_FEATURE
> ExceptionId:qtp103536485-127:https://zqa-225.eng.zimbra.com/service/soap/RecoverAccountRequest:1616657029636:392ec513c12fda53
Code:service.MAX_ATTEMPTS_REACHED_SUSPEND_FEATURE
at com.zimbra.cs.account.ForgetPasswordException.MAX_ATTEMPTS_REACHED_SUSPEND_FEATURE(ForgetPasswordException.java:68)
at com.zimbra.cs.service.mail.RecoverAccount.checkVerifiedRecoveryAccAndSetResendCount(RecoverAccount.java:136)
at com.zimbra.cs.service.mail.RecoverAccount.generatePasswordRecoveryCode(RecoverAccount.java:113)
at com.zimbra.cs.service.mail.RecoverAccount.handle(RecoverAccount.java:84)
at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:646)
at …
> bugfix/ZCS-10425: Throwing particular exception rather

- store/ivy.xml
- store/src/java/com/zimbra/cs/rmgmt/RemoteManager.java
Problem: RemoteManager calls are failing with FIPS enabled.
https://jira.corp.synacor.com/browse/ZCS-10060?focusedCommentId=1419982&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1419982
Ganymed SSH-2 offering KexAlgorithms: diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1 , which are not allowed in FIPS mode.
Solution : Replaced Ganymed SSH-2 with Apache MINA SSHD , which supports KexAlgorithms allowed in FIPS mode.
> ZCS-10060 :  Replaced Ganymed SSH-2 with Apache MINA SSHD

- common/src/java/com/zimbra/common/localconfig/DebugConfig.java
- store/build.xml
- store/ivy.xml
- store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
**Problem:** 
PTD - Message not displaying correctly. [[TSS-18004](https://jira.corp.synacor.com/browse/TSS-18004)]
**Analysis:**
It was reported that some of the messages were not getting displayed correctly. On further analysis, it was found that
the particular attached message was having a lot of malformed inline styling in the original message body which contains a
lot of unclosed double quotes which was escaping large chunks of the real message. The mailer which the customer has used seems like `sendgrid` which has malformed the html.
Looking through the Antisamy policy which we are using turned out that it cannot be fixed through that the reason is that the
`antisamy` policy which we are using with `owasp` can able to handle various operations like validate, truncate, filter, remove …
> TSS-18004: Fix for PTD - Message not displaying correctly

- store/src/java/com/zimbra/cs/service/admin/Auth.java
**Problem:** For admin auth, no exception was returned to client indicating that two-factor setup is required.
**Fix:** Added necessary code to return exception indicating that two-factor setup is required.
**Testing to be done by QA:** 
1. Check if proper exception is returned when two factor is enabled for admin auth indicating that two-factor setup is required.
2. Check if auth is working as before if 2fa is not enabled for the admin account.
> ZCS-10035: Return error code when 2fa is enabled for admin account

- build-common.xml
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
- store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
**Problem:**
Some of the emails displaying as blank.
**Analysis and Fix:**
It was observed that certain e-mails were displaying as blank. On analysing the input mime it was found that there was issue with the input html that there was no closing `style` tag. Here, there are 2 issues:
1. In the `JTidy` configuration `setPrintBodyOnly()` was earlier set to true so it was processing only the body part and skipping the style tags.
2. Earlier in the code skipped the trimming of the parsed string which was getting null value as it was not handling the head of the html because of `setPrintBodyOnly()` was set to true but the code  was written to handle these situation earlier and fallback to the `OWASP` if the output from the `JTidy` was `null`. In this particular case it was not able to handle …
> TSS-18300: Fix for emails displaying as blank

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/localconfig/LC.java
- common/src/java/com/zimbra/common/service/ServiceException.java
- store-conf/conf/custom-mimetypes.xml
- store/build.xml
- store/conf/attrs/zimbra-attrs.xml
- store/ivy.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/service/FileUploadServlet.java
**Problem:**
LDAP Attribute for supporting Attachment Type Restrictions.
**Approach for Implementation:**
Added new ldap attributes at account and cos levels.
`zimbraFileUploadBlockedFileTypes` - Commonly blocked file types for uploading.
`zimbraFeatureFileTypeUploadRestrictionsEnabled` - Enable/Disable blocked file types set in `zimbraFileUploadBlockedFileTypes` for uploading.
Added ldap attribute `zimbraFeatureFileTypeUploadRestrictionsEnabled` for enabling and disabling the blocked file types set in the `zimbraFileUploadBlockedFileTypes` for uploading. If this ldap attribute is disabled then the atachment is uploaded without scanning the ldap attribute `zimbraFileUploadBlockedFileTypes` and the any type of the attachments are allowed to be uploaded.
If the ldap attribute …
> ZCS-10322: LDAP Attribute for supporting Attachment Type Restrictions

- common/src/java/com/zimbra/common/localconfig/DebugConfig.java
- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
- store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
**Problem:**
Some of the emails displaying as blank.
**Analysis and Fix:**
It was observed that certain e-mails were displaying as blank. On analysing the input mime it was found that there was issue
with the input html after getting parsed div tag was containing a new line between `<` and `/div>`. ~~To fix this issue a new
condition is introduced to handle if any of the end tag contains this situation then newline is removed from that tag and it
should constitute a well-formed end tag.~~
**Update:** Handled the newline condition using the `JTidy` library option `setWraplen(0)` as earlier `JTidy` was wrapping the html at 68th character. So, setting this option to set the wrapping to `0` which in removes any chances of having the unnecessary newline in the html.
Also, added `localconfig` …
> TSS-18349/ZCS-10544: Fix for emails displaying as blank [2]

- common/src/java/com/zimbra/common/localconfig/LC.java
Zulip base host & jwt secret attrs have been moved to LDAP removing them from localconfig.
> ZCS-10585: zulip base host & jwt secret attrs moved to ldap removing from lc

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
- store/src/java/com/zimbra/cs/service/FileUploadServlet.java
- store/src/java/com/zimbra/cs/service/mail/ParseMimeMessage.java
**Problem:** 
File upload size restrictions per user.
**Description:**
- Added new `LDAP` attribute `zimbraMailAttachmentMaxSize` at `account` and `cos` level for restricting the maximum size in bytes for e-mail attachment.
- Set the `defaultCOSValue` for the `LDAP` attribute `zimbraMailAttachmentMaxSize` as `0`.
- Modified `zimbraFileUploadMaxSizePerFile` `LDAP` attribute to be used for file uploads restrictions other than e-mail. Now, the old `defaultCOSValue` is removed as its value should be less than the `LDAP` attribute `zimbraFileUploadMaxSize`. If the default value is not set then upload size is limited by `zimbraFileUploadMaxSize` which is global. Also, added accountInfo flag to `zimbraFileUploadMaxSizePerFile`.
- Added new ldap attributes for restricting  the maximum size in …
> ZCS-10443: File upload size restrictions per user

- store/src/java/com/zimbra/cs/db/Versions.java
Updating database version for feature addition of document editing with Briefcase APIs. Database has been updated with new tables of watch & event in mailbox groups.
Also adding support for ZCS upgrade with supported scripts in below PRs
https://github.com/Zimbra/zm-db-conf/pull/19
https://github.com/Zimbra/zm-build/pull/182
> ZCS-10589: update db version for adding watch & event tables for briefcase api

- store/conf/attrs/zimbra-attrs.xml
Added `accountInfo` flag to ldap attribute `zimbraMailAttachmentMaxSize`
> ZCS-10596: Added accountInfo flag to ldap attribute zimbraMailAttachmentMaxSize

- store/src/java/com/zimbra/cs/index/ZimbraQuery.java
Issue
Sharing briefcase folder on multi node environment across the mailbox servers between 2 users resulting into WRONG_HOST exception when fetching the mailbox account of authenticated user. Resulting into no files list for shared folders for sharee user.
Fix
Added flag to skip the check of is on local server and get the mailbox of authenticated user using account id.
Testing done
Verified folder shared across mailbox server on multi node environment between user, sharee user is able to get the files list.
> ZCS-10603: fetch authenticated user mailbox skipping check of is on local server

- store/build.xml
- store/ivy.xml
**Problem:**
Apache MINA SSHD Client 2.6.0 not compatible with lower version of OpenSSH(<7).
**Fix:**
Update Apache MINA SSHD Client to latest version 2.6.1, and updated it's dependent jar's
> ZBUG-2191: Updated Apache MINA and it's dependent jar's

- common/src/java/com/zimbra/common/soap/SyncConstants.java
- soap/src/java/com/zimbra/soap/sync/message/GetDeviceStatusRequest.java
**Problem:**
- device removed by user immediately gets re-provisioned and continues syncing and gets listed in the syncing device list on UI
- user api `GetDeviceStatusRequest` returns removed devices too
- once device is removed by user, do not allow it to re-provision on it's own. user should be able to allow it using `AllowDeviceRequest`. This stops devices syncing after removal by user.
- added optional attribute `includeRemovedDevices` in user api `GetDeviceStatusRequest` with default value as `false`. this will give control on api level whether removed devices should be returned in response or not.
- once device is removed by user, it does not get re-provisioned and stops syncing new items.
- user can allow re-provision of removed device using …
> ZCS-10158 user api GetDeviceStatusRequest returns removed devices too

- store/src/java/com/zimbra/cs/imap/ImapPath.java
Because of the logic a `null pointer` was being returned and this caused any folder containing an `*` to be marked as `not visible` and tagged with a a `\NoSelect` flag.
The code was attempting to avoid returning an ImapFolder object in the case of an exact match to `*` but was instead returning it for any folder with an `*` character included.
**Note:** This is a bugfix discovered in Zimbra X but also applicable to Zimbra 8/9.
Before change:
```
* LIST (\NoSelect \HasNoChildren) "/" "*_TEMP"
```
After change:
```
* OK IMAP4rev1 proxy server ready
. login user1@zmc.com test123
. OK [CAPABILITY IMAP4rev1 ACL BINARY CATENATE CHILDREN CONDSTORE ENABLE ESEARCH ESORT I18NLEVEL=1 ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ LOGIN-REFERRALS MULTIAPPEND NAMESPACE QRESYNC QUOTA RIGHTS=ektx SASL-IR …
```
> ZCS-8895 correct handling of wildcard listing

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/rmgmt/RemoteManager.java
**Problem**
- zmmboxmove and moveMailboxRequest was broken, invalid exception thrown and rsync timeout
**Approach and Fix**
- Increase the default timeout.
- Introduce configurable timeout.
- Tested the mailbox move in the machine where issue was reproducing.
> ZBUG-2289: zmmboxmove broken with rsync timeout

- store/src/java/com/zimbra/cs/zimlet/ProxyServlet.java
**Issue**
- Proxy SSRF: An attacker in control of any user-account regardless of their privileges on a targeted Zimbra
instance can forge arbitrary requests on the server the Zimbra instance is hosted on. This could
lead to disclosure of sensitive information and access control bypasses.
**Solution:**
- Do not take into consideration the Host header setting.
**Test:**
- Tested the scenario where a user should not be able to redirect to any service with the Help of X-host.
> ZBUG-2283: Do not allow to explicitly set the Host header

- store/src/java/com/zimbra/cs/service/PreAuthServlet.java
**Problem:**
As per description in the ticket an authenticated user can recover his `authoken` by simply looking at what URLs are loaded by his browser after authentication. This valid `authtoken` can be used to exploit the insecure redirect in the `PreAuthServlet`.
```
/service/preauth? isredirect=1&authtoken=[VALIDTOKEN]&redirectURL=http://whatever
```
**Fix:**
~~To fix the above exploitation checked the `redirectURL` in the `PreAuthServlet` to look if the domain is `localhost` or `127.0.0.1` or it belongs to the set of private IP addresses then it restricts the user from redirecting it to the local addresses and if it is an external addresses then it allows the redirection.~~
**Update:** There is an insecure redirect in the `PreAuthServlet` which can only be exploited with a valid …
> ZCS-9764: Open Redirect Vulnerability in PreAuthServlet

- common/src/java/com/zimbra/common/localconfig/DebugConfig.java
- store/build.xml
- store/ivy.xml
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
- store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
- Reverted JTidy related changes done in [TSS-18004](https://jira.corp.synacor.com/browse/TSS-18004), [TSS-18300](https://jira.corp.synacor.com/browse/TSS-18300) and [TSS-18349](https://jira.corp.synacor.com/browse/TSS-18349)
- Updated `owasp-java-html-sanitizer` to `20190610.2z` 
It was found that the particular attached message was having a lot of malformed inline styling in the original message body which contains a lot of unclosed double quotes which was escaping large chunks of the real message. To fix this issue the code changes have been done in the `owasp-java-html-sanitizer` and its jar file is updated in the `ivy.xml`.
[Reference](https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/4)
> ZCS-10612: Removed JTidy related changes and update owasp-java-html-sanitizer

- store/src/java/com/zimbra/cs/imap/ImapRequest.java
Workaround for android outlook sending 25-character dates in append commands, which was causing a loop of "Failed to add recipient" "Failed to remove recipient" error messages in Android Outlook.
Android outlook will send APPEND commands with dates that look like this:
```
A2374 APPEND "Drafts" (\Seen) "3-May-2021 20:38:39 +0000" {570}
```
Where date is expected to be:
```
A2374 APPEND "Drafts" (\Seen) " 3-May-2021 20:38:39 +0000" {570}
```
Example in: https://datatracker.ietf.org/doc/html/rfc3502
```
Example: C: A003 APPEND saved-messages (\Seen) {329}
S: + Ready for literal data
C: Date: Mon, 7 Feb 1994 21:52:25 -0800 (PST)
C: From: Fred Foobar <foobar@Blurdybloop.example.COM>
C: Subject: afternoon meeting
C: To: mooch@owatagu.example.net
C: Message-Id: …
```
> ZCS-10705 - Workaround for android outlook sending 25-character dates

- common/src/java-test/com/zimbra/common/soap/GetInfoResponseSOAP.xml
- soap/src/java-test/com/zimbra/soap/account/GetInfoResponse.json
- soap/src/java-test/com/zimbra/soap/account/GetInfoResponse.xml
- store/conf/attrs/zimbra-attrs.xml
**Problem Statement:** 
Pass attachment restrictions attributes in GetInfoResponse.
**Fix:** 
Added accountInfo tag in the following Zimbra attributes
- zimbraFeatureFileTypeUploadRestrictionsEnabled
- zimbraFileUploadBlockedFileTypes
**Testing:**
Able to get zimbraFeatureFileTypeUploadRestrictionsEnabled, zimbraFileUploadBlockedFileTypes attributes in getInfoResponse
> ZCS-10691: Need attachment restrictions attributes in GetInfoResponse for ZCO client

- store/src/java/com/zimbra/cs/html/owasp/OwaspDefang.java
- store/src/java/com/zimbra/cs/html/owasp/policies/BackgroundPolicy.java
**Problem:**
Problems viewing mail with `owasp_html_sanitizer` enabled.
**[1]** Mime `427353-1804751.msg` attached in [ZBUG-1948](https://jira.corp.synacor.com/browse/ZBUG-1948) causes `java.lang.IndexOutOfBoundsException`
Fix: The root cause of this problem is that the attribute value in itself is `background` instead of attribute itself, so while
`BackgroundPolicy` tries to seek the `attrs.indexOf("background")` resulting in wrong index of the attribute and resulting in the `java.lang.IndexOutOfBoundsException`.
To fix this another condition is implemented which checks for that if the keyword `background` is coming at odd index or not,
if the index of `background` keyword is found at the odd index position then we are ignoring it as we are only interested in the …
> ZBUG-1948: Fix for Problems viewing mail with owasp_html_sanitizer enabled

- store/ivy.xml
Bumped the version of owasp-java-html-sanitizer
**Reference PRs:**
[zm-mailbox](https://github.com/Zimbra/zm-mailbox/pull/1145)
[zm-zcs-lib](https://github.com/Zimbra/zm-zcs-lib/pull/81)
[owasp-java-html-sanitizer](https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/5)
> ZBUG-1948: Bumped the version of owasp-java-html-sanitizer

- common/src/java/com/zimbra/common/soap/AccountConstants.java
- store/src/java/com/zimbra/cs/service/admin/Auth.java
**Problem:** 
- ZMPROV is broken when zimbraFeatureTwoFactorAuthRequired is TRUE
- Throwing nullPointerException when zmprov is called after zimbraFeatureTwoFactorAuthRequired is TRUE
**Fix:** 
- Added check while doing admin auth for account.getServer() null because getServer will be null for zmprov account as it is not a admin created account.
- we don't need to check 2fa for zmprov account.
**Testing to be done by QA:** 
1. Should not throw null pointer exception when the user does any zmprov operation after zimbraFeatureTwoFactorAuthRequired is TRUE
2. Check if auth is working as before.
**Note:**
The whitespaces are unavoidable as they occurred due to the tabSpace added when we create wrapper if loop.
Please use hide whitespace setting from GitHub while reviewing PR.
> ZBUG-2334:- Added code to skip two factor auth check when auth request is coming from ZMPROV

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/ivy.xml
**Fix:**
- Switching from tika-app-1.24.1.jar to tika-core-1.24.jar to fix system failure: native formatter failure while opening doc for editing.
- Making `com.zimbra.cs.convert.TikaExtractionClient` as default attachment extraction client class.
**Note:**
After switching from tika-app-1.24.1.jar to tika-core-1.24.jar the above exception in the description is not reproducible. Following are the observations:
In case of Ubuntu when we use `attachment_extraction_client_class=com.zimbra.cs.convert.LegacyConverterClient`, there are issues while indexing and extraction is getting failed.
```
2021-07-02 09:26:42,714 INFO  [ReIndex-0] [name=akshat@shashi-classic-m1.synacor.tk;mid=2;] index - Re-index start
2021-07-02 09:26:42,715 INFO  [ReIndex-0] …
```
> ZCS-10598: Switching from tika-app-1.24.1.jar to tika-core-1.24.1.jar

- store/ivy.xml
**Problem:**
pdf/doc/docx contents not searchable after switching from tika-app-1.24.1.jar to tika-core-1.24.1.jar
**Fix:**
Added jars which are necessary for the parsing and extraction of the documents which were not working after replacing `tika-app` jar to the `tika-core` jar. Now after adding these required jars like tika-parser and it's dependent jars the content of the search in the e-mail for the documents like `pdf, doc, docx, ppt, pptx, xls, xlsx`.
- Verified on Ubuntu18 build contents of the attachment in e-mail for the above mentioned documents are searchable now.
- Verified on RHEL8 build contents of the attachment in e-mail for the above mentioned documents are searchable now.
**Related PRs:**
[zm-zcs-lib](https://github.com/Zimbra/zm-zcs-lib/pull/82) …
> ZCS-10728: pdf/doc/ppt/xls contents not searchable after switching from tika-app-1.24.1.jar to tika-core-1.24.1.jar

- store/ivy.xml
**Problem:**
Briefcase uploads were not searchable
**Fix:**
While working on this found that while trying to create or edit the presentation following exception were getting observed:
- `java.lang.NoClassDefFoundError: Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader`
- `java.lang.NoClassDefFoundError: com/adobe/internal/xmp/XMPException`
To fix these issues added the following dependencies to create and edit pptx presentation while using `TikaExtractorClient`:
- `metadata-extractor-2.16.0.jar`
- `xmpcore-6.1.11.jar`
- Now, search is working in Briefcase.
- Verified now able to create and edit a presentation.
**Related PRs:**
[zm-zcs-lib](https://github.com/Zimbra/zm-zcs-lib/pull/84)
[zm-convertd-store](https://github.com/Zimbra/zm-convertd-store/pull/1 …
> ZCS-10766: Briefcase contents not searchable

- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
**Issue**
LDAP attr `zimbraMobileBlockedDevices` has `unsetMobileBlockedDevices` method which seems to have been added manually causing below error during compilation.
**Fix**
Remove the method that was added manually and keep the one created from running `ant generate-getters`
`generate-buildinfo:
[mkdir] Created dir: /Users/yogesh.dasi/zimbra/zcs/zm-mailbox/store/build/buildinfo/com/zimbra/cs/util
[javac] Compiling 1 source file to /Users/yogesh.dasi/zimbra/zcs/zm-mailbox/store/build/classes
compile:
[javac] Compiling 2481 source files to /Users/yogesh.dasi/zimbra/zcs/zm-mailbox/store/build/classes
[javac] /Users/yogesh.dasi/zimbra/zcs/zm-mailbox/store/src/java/com/zimbra/cs/account/ZAttrConfig.java:32027: error: method unsetMobileBlockedDevices(Map<String,Object>) is already defined in …
> ZCS-10789: remove duplicate method for zimbraMobileBlockedDevices ldap attr

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
Deprecate **zimbraNetworkModulesNGEnabled** LDAP attr and default its value to false since 9.1.0
> ZCS-10798: deprecate zimbraNetworkModulesNGEnabled ldap attr with default value to false

- store-conf/conf/custom-mimetypes.xml
**Issue**
CalDav configuration fails due to user not found as the xml file mime type is not getting detected as application/xml instead its showing as text/plain
**Fix**
Add support to custom mime types for XML to detect the mime type of xml as application/xml
> ZCS-10801: add custom mime type for xml detection

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/soap/WsdlServlet.java
**Issue**
In ZCS-10403 wsdl behavior was updated to honor `zimbraPublicServiceHostname zimbraPublicServiceProtocol zimbraPublicServicePort zimbraAdminProxyPort ` and use them in wsdl. There is no option to go back to old behavior.
**Fix**
Added LC switch `wsdl_use_public_service_hostname` to toggle this behavior. If its **true** it is using the above global configs to set the hostname, port and so on. If set to **false** it use old default behavior.
> ZBUG-2360: adding LC to toggle the behaviour as earlier that was updated in ZCS-10403

- store/src/java/com/zimbra/cs/mailbox/calendar/ZRecur.java
Problem : When `zimbraCalendarRecurrenceMonthlyMaxMonths` is `3` the instance for the appointment are not created correctly. The last instance is not being genarted.
Reason : The logic to create instances checks for the last instance date till which the appointments can be expanded to. The last instance date calculation was wrong.
Try this:
```
Calendar calendar = Calendar.getInstance();
calendar.setTimeZone(TimeZone.getTimeZone("UTC"));
//        calendar.setTimeZone(TimeZone.getTimeZone("Asia/Tokyo"));
//        calendar.setTime(new Date());
calendar.setTimeInMillis(1638284400000l); //1st dec
//        calendar.setTimeInMillis(1646060400000l);// 1st march 
//        calendar.setTimeInMillis(1638370800000l);//2nd dec 1638370800000 
//        calendar.setTimeInMillis(1646146800000l);// …
```
> ZCS-10805 : Set limit to expansion based on timezone

- store/src/java/com/zimbra/cs/account/Account.java
**Issue**
**zimbraCosId** if not set on account but set on domain as **zimbraDomainDefaultCosId** does not shows for account in `zmprov ga <account> zimbraCosId`
**Fix**
Add the cos Id from domain to list of account defaults in display of the zmprov get account request.
> ZBUG-2026: display cos id from domain if unset on account

- store/src/java/com/zimbra/cs/service/mail/ParseMimeMessage.java
[Problem]
When the message's subject and/or body is written in Japanese and its message structure is plain/text, the S/MIME signed message is corrupted and appeared as "tampered" in the recipient Inbox.
[Root cause]
When the message was a single part message (plain/text), the message was first sent to the MBS in raw UTF-8 characters, then MBS performed the S/MIME-sign operation to that raw UTF-8 email. But after that MBS re-checked the message body and encoded the raw UTF-8 to Quoted printable.  In short, MBS tampered the message.
[Fix]
Before S/MIME-sign operation, MBS encodes the raw UTF-8 message into the Quoted printabble one, then performs S/MIME-sign.
[Manual testing]
(1) Setup the S/MIME configuration for two accounts
(2) Compose a plain/text message with a Japanese subject and …
> ZBUG-2167:S/MIME signature corrupted in single-part Japanese mail

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/localconfig/LC.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
Move LC attribute `zimbra_feature_safe_unsubscribe_folder_enabled` to LDAP `zimbraFeatureSafeUnsubscribeFolderEnabled` for checking creation of unsubscribe folder for 9.1.0
> ZCS-10847: move unsubscribe folder enabled check attribute to LDAP from LC

- store/src/java/com/zimbra/cs/mailbox/calendar/Invite.java
- store/src/java/com/zimbra/cs/mailbox/calendar/Util.java
Problem : When sending meeting invites from MS teams Desktop, ALT-DESC param is not being sent. This causes the DescHTML not to be set while creating the invites. When we use EWS to add an account in Outlook, the meeting urls are removed.
Solution: Check if descHtml is missing and desc is present in the request. Convert the desc as html and add it is descHtml.
Test : 
Sent recurring and normal meetings from MS Teams to verify if the URLs are present or not.
> ZBUG-2316 : Changes to set desc html when missing

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
**Issue**
LC **zimbra_feature_safe_unsubscribe_folder_enabled** when set to false still shows the Unsubscribe folder
**Fix**
Added check to getFolder & IMAP to hide the folder from list if **zimbra_feature_safe_unsubscribe_folder_enabled** is set to false
> ZCS-10870: adding check to display unsubscribe folder on local config

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
**Issue**
Unsubscribe folder display even if the **zimbraFeatureSafeUnsubscribeFolderEnabled** is FALSE
**Fix**
Added check to display Unsubsribe folder if **zimbraFeatureSafeUnsubscribeFolderEnabled** is TRUE for getFolder request & IMAP folder list
> ZCS-10870: adding check for LDAP attr unsubscribe folder enabled to display unsubscribe folder

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/service/account/GetPrefs.java
**Problem:**
Create a boolean local-config for fifteen minutes calendar resolution.
- Added local config `zimbraPrefCalenderScaling` for fifteen minutes calendar resolution.
- Made the LC value available as pref on the front-end side based on the boolean condition of the value of `zimbraPrefCalenderScaling`.
- Verified with the following `GetPrefsRequest` that the local-config value `zimbraPrefCalenderScaling` is now available as `GetPrefsResponse`.
```                                                                                                                                                               
<GetPrefsRequest xmlns="urn:zimbraAccount">
</GetPrefsRequest>
```
```
<GetPrefsResponse xmlns="urn:zimbraAccount">
<pref …
```
> ZCS-10883: Create a boolean local-config for fifteen minutes calendar resolution

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/localconfig/LC.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/service/account/GetPrefs.java
**Problem:**
Introduce calendar resolution preference backed by the LDAP attribute.
**Approach:**
- Introduced a new LDAP attribute `zimbraPrefCalenderScaling` on the `account` and `COS` level to have the calendar resolution preference for `10, 15, 30` minutes keeping the default value as `30 minutes`.
- Reverted the [ZCS-10883](https://jira.corp.synacor.com/browse/ZCS-10883) changes for the temporary boolean `local-config` for `15 minutes` calendar resolution.
- Created a new build with these changes and verified that the newly introduced LDAP attribute `zimbraPrefCalenderScaling`  is available at the `account` and `COS` levels.
- Verified with the following `GetPrefsRequest` that the newly introduced LDAP attribute `zimbraPrefCalenderScaling` is now available as …
> ZCS-10914: Introduce calendar resolution preference backed by LDAP attribute

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/service/mail/SendMsg.java
**Problem:**
Introduce a local config to enable/disable `DSN` with `SendMsgRequest`.
**Approach and Implementation:**
Introduced a new LC `delivery_report_enabled` with default value as `true`.
If the LC value is `true`, then the `SendMsgRequest` with the `DSN` feature is enabled.
If the LC value is `false`, then the `SendMsgRequest` with the `DSN` feature is disabled.
- Set the LC value as `true` with `deliveryReport` attribute of `SendMsgRequest` set as `true` :: **Result**-> Successful Mail Delivery Report.
- Set the LC value as `true` with `deliveryReport` attribute of `SendMsgRequest` set as `false` :: **Result**-> No Mail Delivery Report.
- Set the LC value as `true` with **NO** `deliveryReport` attribute in `SendMsgRequest` :: **Result**-> No Mail Delivery Report. …
> ZCS-10972: Localconfig to enable/disable DSN with SendMsgRequest

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/util/StringUtil.java
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
**Issue**
LDAP attribute added for type enum with values starting with numeric is leading the compilation errors. For e.g. if the enum is set with values 10, 15, 30 here when generate getters is ran there first character from enum gets removed because for Character.isJavaIdentifierStart first character cannot be numeric and this leads duplicate enum values for '0' as from 10 & 30, 1 & 3 gets removed. This leads to below compilation error.
**Fix**
Java identifier check for enum values requires first character to be non numeric and using numeric enum as list for LDAP attrs enums causes duplicate method errors during compliation. As a fix made identifier check to include the numeric character too for maintaining uniqueness.
```
compile:
[javac] Compiling 1 source file to …
```
> ZCS-11066: update java identifier check for LDAP enum values to use the first character too for uniqueness

- store/src/java/com/zimbra/cs/mailbox/CalendarItem.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/Message.java
- store/src/java/com/zimbra/cs/mailbox/calendar/Invite.java
**Issue**
Invite sent from MS Teams does not shows up the links from the invite since it uses x-alt-desc or html description from invite.
**Fix**
Since MS Team sent the invites text part with links enclosed in <> , this content is sent in the EWS response is sent as text type and EWS ignores this link. As a fix the email invite which is received contains html body within the multipart we can send this html content in EWS response so the content type is sent as HTML and the links display fine in the invite, for this storing the text/html description into invite metadata as `xDescH`.
If `xDescH` is missing as fallback sending text/plain description in EWS response with converting the text links to anchor tags.
Verfied by injecting the test MIME can see the links fine in the …
> ZBUG-2316: store text/html from message to calendar invite metadata

- client/src/java/com/zimbra/client/ZGetInfoResult.java
- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- common/src/java/com/zimbra/common/gql/GqlConstants.java
- common/src/java/com/zimbra/common/soap/AccountConstants.java
- soap/src/java/com/zimbra/soap/account/message/GetInfoResponse.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java-test/com/zimbra/cs/service/account/GetInfoTest.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
- store/src/java/com/zimbra/cs/service/account/GetInfo.java
Jira ticket: https://jira.corp.synacor.com/browse/ZBUG-1280
Frontend PR: https://github.com/Zimbra/zm-web-client/pull/659
Retrieving list of urls using zimbraSpellCheckURL attribute and checking if it's empty on the primary server and adding it as a boolean value to the GetInfo response. This value will be used by frontend to display/hide the spell check button on compose page and mandatory spell check.
> Zbug-1280 added isSpellCheckEnabled attribute to the GetInfoResponse

- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
GetAppointmentIdsInRangeRequest  giving error for soap request.
Fixed issue with transaction before read operation
Also fixed failing soap request GetAppointmentIdsSinceRequest in the same ticket
> Bugfix/zcs 11120: GetAppointmentIdsInRangeRequest soap request not working

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/mailbox/calendar/Invite.java
**Issue**
MS Team invites with mime cast secure URL filter applied, mime cast does not add the links to content of text/calendar.
**Fix**
MS Team invites with mime cast secure URL filter when add X-ALT-DESC to MIME don't add the links causing the links the to not show in the outlook calendar items. As fix if the invite is of MS Teams and LC. invite_ignore_x_alt_description is true we update descHTML content in the invite to use xDescH(text/html) description instead of X-ALT-DESC
**Test**
Tested by injecting different MIME having X-ALT-DESC with missing links show the calendar items links fine from text/html
Tested GetAppointmentRequest is getting required descHtml from text/html
Verified its working fine for EWS & ZCO both.
> ZCS-11145: use text/html for appointment description ignoring x-alt-desc for ms team invites

- store/src/java-test/com/zimbra/cs/datasource/imap/RemoteFolderTest.java
- store/src/java/com/zimbra/cs/datasource/imap/RemoteFolder.java
https://jira.corp.synacor.com/browse/ZBUG-2192
Issue:
Renaming a folder structure in a data source in Zimbra via IMAP results in the below error,
Error:
```
Account "imap1" Failed
system failure: Folder sync failed, system failure: Synchronization of folder 'zimbra_test/a' failed, system failure: Unable to rename the remote folder to zimbra_test/a_2, RENAME failed: RENAME failed 
```
Steps to Reproduce the issue:
- add external account as IMAP(I used Zimbra as an external account ).
- create folder structure in this account: zimbra_test/a/b
- Click on the "update" arrow to sync the account to the server.
- right click on "a" > rename folder: a_1
- click on the "update" arrow to sync the account to the server.
- error message comes up:
- system failure: Folder sync failed, system failure: …
> ZBUG-2192: Fixed IMAP rename folder issue

- store/src/java/com/zimbra/cs/account/soap/SoapDistributionList.java
- store/src/java/com/zimbra/cs/account/soap/SoapDynamicGroup.java
- store/src/java/com/zimbra/cs/service/admin/GetAllDistributionLists.java
Problem: 
1. Count and Members format is not getting displayed correctly for Dynamic Distribution List (DDL)
2. zmprov gdl command not getting member list.
Solution:
1. Filling in the memberList class property of SoapDynamicGroup.java instead getting data on the basis of attribute.
2. The above change is common change which will serve correct member information to gdl as well as gadl command.
3. Since, we are getting members list for gadl command by above fix so reverting few changes did in ZBUG-651 as it was impacting the result of gdl command and might impact on performance while getting large data of dynamic distribution list.
Fix Mode:
1. In GetAllDistributionLists.java, created a method encodeMembers(), which is getting members list for Dynamic DL as well as  DL in correct format. …
> ZBUG-2619:Incorrect Member format in Dynamic DL

- common/src/java/com/zimbra/common/localconfig/LC.java
- common/src/java/com/zimbra/common/util/ZimbraCookie.java
Supported SameSite=Strict cookie in ZM_AUTH_TOKEN cookie.
For this added a localconfig varible in LC.java named zimbra_same_site_cookie
By default value will be 'Strict' but user can change it to Lax, None and ""(empty) for existing behavior.
**Testing Instruction:**
**1** - On login in webclient, by default user can see the SameSite=Strict cookie for ZM_AUTH_TOKEN.
http://synscreen.buf.synacor.com/view/a5d6a2.png
**2** - User can control behavior using zmlocalconfig
zmlocalconfig -e zimbra_same_site_cookie="Strict"
User can provide value like Strict, Lax, None or "" (Empty)
**3** - To disable this behavior we can set value of SameSite=""
http://synscreen.buf.synacor.com/view/a7d8d2.png
> ZBUG-2397: Added cookie SameSite=Strict and zmlocalconfig attribute

- store/src/java/com/zimbra/cs/account/ldap/Validators.java
**Problem**
Accounts created by a user for public sharing are being counted toward the account quota for the domain.
**Solution**
Fixed the `com.zimbra.cs.account.ldap.Validators` class where the LDAP database was being queried with the wrong LDAP filter. 
**Fix Mode**
Formerly the `allNonSystemAccounts` LDAP filter was being used, which included both internal and external accounts in the count, but now the `allNonSystemInternalAccounts` filter is being used, so that only internal accounts affect the count for the quota.
**Test Done**
Tested manually with the procedure included in the ticket, plus some extra validations:
1. Created the example.com domain for testing purposes.
2. Set the domain quota to 5 accounts maximum.
3. Created four (1st to 4th) internal accounts.
4. Created one …
> ZBUG-1541: Accounts created by a user for public sharing are being counted toward the account quota for the domain.

- store/build.xml
- store/ivy.xml
- store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
Problem:
When OWASP zimbra_use_owasp_html_sanitizer = true, URL in the HTML message is getting modified. Character &num replace by #_
Issues: ZBUG-1932
Fix:
ZBUG-1932
Issue has been fixed in the original owasp library and zimbra [java-html-sanitizer-release-20190610.1](https://github.com/Zimbra/java-html-sanitizer-release-20190610.1) is rebased with the latest release. These test cases are to make sure the urls are not changed as mentioned in the ticket when html is sanitized with newer jar.
Ref PRs:
[java-html-sanitizer#6](https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/6)
[zm-zcs-lib#89](https://github.com/Zimbra/zm-zcs-lib/pull/89)
> ZBUG-1932: Upgrading owasp-java-html-sanitizer version

- soap/src/java/com/zimbra/soap/mail/message/GetAppointmentIdsSinceResponse.java
- store/src/java/com/zimbra/cs/db/DbMailItem.java
Fixed issue with deleted item ids in GetAppointmentIdsSinceResponse.
It was only returning all modified item ids
> ZCS-11154: GetAppointmentIdsSinceResponse not populating deleted item ids

- common/src/java/com/zimbra/common/mime/MimeConstants.java
[ZBUG-2222](https://jira.corp.synacor.com/browse/ZBUG-2222)
The main code for this PR references in https://github.com/Zimbra/zm-ews-store/pull/43
Basically, a new constant had to be created for `"image/"` and all the constants are placed in` MimeConstants.java` class
> ZBUG-2222: Adding constant for image/ which is referenced from EWS code

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/admin/message/GetAccountRequest.java
- store/src/java/com/zimbra/cs/service/account/GetInfo.java
- store/src/java/com/zimbra/cs/service/admin/GetAccount.java
- store/src/java/com/zimbra/cs/service/admin/ToXML.java
**Problem**
* The value of `zimbraMailQuota` that we return in GetInfo is not the actual value that the server respects when limiting the user if `zimbraMailDomainQuota` contains a lower value than it.
* This behavior is documented.
* This behavior exists in order to support various configuration options on shared environments by admins/domain-admins.
**Solution**
* We can adjust the value of `zimbraMailQuota` that we return in `GetInfo` to respect the effective value (minimum between the relevant properties described above).
* We can also get the value of `zimbraMailQuota` from Admin `GetAccountRequest` so for consistency setting the effective quota value in `zimbraMailQuota` attribute.
**Pros**
* Keeps logic of choosing minimum between the two options in one place (the API).
* No UI or …
> ZBUG-1869: Setting effective quota in zimbraMailQuota

- store/src/java/com/zimbra/cs/service/util/ResetPasswordUtil.java
ZBUG-2599 is about the `RecoverAccountRequest` method of back-end, which under some circumstances could be maliciously invoked to harvest existing account names due to response differences whether the account is fully set up for password recovery. To solve this we have changed the `ResetPasswordUtil` class behavior in such a way that, unless the account is fully set up for password recovery, the response will be generic and equal to that of when the account does not exist.
Being "fully set up for password recovery" means:
- The account name represents an existing account.
- The account has its password recovery feature enabled.
- The account has set a password recovery address.
- The password recovery address has been verified.
**Setup**
1. Create a new test domain
2. Create new test …
> ZBUG-2599: Defining generic error response for "Forgot Password".

- store/src/java/com/zimbra/cs/mailbox/ContactAutoComplete.java
[ZBUG-2588](https://jira.corp.synacor.com/browse/ZBUG-2588)
Problem:
The issue was basically after sharing root folders with another account contacts are not coming in autocomplete .
Exp - user1 and user2 is there. We need to share all root folders of user1 with user2 , automatically contacts has shared . But while we are sending any mail from user2 autocomplete is not working for shared contacts of user1
Solution:
There is one if conditions to check contacts and mount process but in this situation if condition is only checking for contacts , so it is never going to elseif condition that is required for mount process.
Just added one condition as '!(folder instanceof Mountpoint)' because when condition Mountpoint will come it will not skip , it will go inside elseif condition and move …
> ZBUG-2588 : Autocomplete bug with "/" shares

- store/src/java/com/zimbra/cs/datasource/imap/ImapFolderSync.java
- store/src/java/com/zimbra/cs/datasource/imap/MessageChange.java
- store/src/java/com/zimbra/cs/datasource/imap/MessageChanges.java
Issue:
Modified Drafts are not synced to an external IMAP account
Fix:
- The issue was basically the logic was not in place to identify the draft content change when changed locally
- In order to identify the draft change content we have added a logic where we figure out the draft content has been updated
- Next step to query and find the modified items for Draft since previous sync state. This returns the required and expected modified items based on lastChangeID
- lastChangeID remains 0 when the server is restarted and we modify and sync the messages. In this case syncState remains null hence we have to check for all drafts messages and sync them up
- once we have Message changes identified we delete the corresponding message and push the updated new message
Repro:
There are two …
> ZBUG-2361: Modified Draft not synced to external imap account

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/service/account/GetInfo.java
https://jira.corp.synacor.com/browse/ZCS-10678
Feature: Server Side work to Force users not to use username in the password
Problem:
One of the customer (The Open university of Tanzania) is looking for an option in password policy - users should not be able to use their username in the password.
Code fix:
As discussed on the approach, we would be making using of Local config to enable the feature is password can contain the username or not. If the value is set to true then we check in checkPasswordStrength() to check for password containing username and throw a relevant exception
Test:
Through UI and soap UI API calls, the relevant exception is thrown
> ZCS-10678: Server Side work to Force users not to use username in the password

- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
Problem : Emailed contacts are not updating after updated display name from CLI and send email by selecting updated name.
Solution: We are getting results for emailed contacts from mail_item table where each contact is saved once we send email to that particular contact. It does not get updated when we modify displayName from either CLI or admin panel. So, the solution to this problem is to modify metadata/contact index file of that particular record with updated display name.
Code fix:
- Created findContactsInEmailedContacts () to find the list of eligible email Id whose display names have been modified and returning list of InternetAddress (for email ID), display name and contact id. It queries on the basis of email ID, if record is found then it checks if the display name is updated …
> ZBUG-2310:Emailed contacts not updating

- store/src/java/com/zimbra/cs/mailbox/ContactAutoComplete.java
**Solution**
ZBUG-1838 is about the "GAL auto complete" feature. If you have an account with multiple aliases which starts with the same characters, e.g: alias01@domain.com, alias02@domain.com, alias03@domain.com, etc, and you try to send a message to that account typing a few first characteres of its related aliases into "To/Cc/Bcc" fields, e.g: "ali", you only get one alias, e.g: alias01@domain.com instead of all the related aliases. To fix this, we have deleted the lines 739-744 of "addMatchedContacts" function which belongs to "ContactAutoComplete" class. Those lines were the ones that caused to get only the first email address matching and skipped the next ones.
**Notes**
1- The expected behavior on Auto Complete feature into "To/Cc/Bcc" fields after this solution will be this one: …
> ZBUG-1838: Auto complete displaying single email address from matching account

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
[ZBUG-1455](https://jira.corp.synacor.com/browse/ZBUG-1455)
Problem:
AccDescription of the zimbraFeatureMailForwardingInFiltersEnabled need to change . While we are hitting to get descriptions of zimbraFeatureMailForwardingInFiltersEnabled we are getting result as ( enable end-user mail forwarding defined in mail filters features ) but it should be ( enable end-user mail redirecting defined in mail filters features )
Solution:
I have replaced redirecting in the place of forwarding as we are doing operations of redirect on this attribute .
Testing:
Tested on a new build for above changes as for this bug we have changed on zimbra-attrs.xml file . Description is working as expected .
> ZBUG-1455 : zimbraFeatureMailForwardingInFiltersEnabled, Attribute funtionality is wrong

- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrDynamicGroup.java
[ZBUG-1403](https://jira.corp.synacor.com/browse/ZBUG-1403)
Problem: User is Not able to set zimbraDistributionListSendShareMessageToNewMembers on Dynamic Distribution lists promoting error “ERROR: service.FAILURE (system failure: unable to modify attrs: object class violation - unable to modify attributes”, hence also it is not working through admin panel. But for dynamic list it works fine.
Solution: Any changes in LDAP attribute takes place in zimbra-attrs.xml file. Added group in the scope of zimbraDistributionListSendShareMessageToNewMembers and created getters.
Testing:
Did testing on my local system by modifying attribute from CLI as well as from admin panel. Now we are able to modify this attribute's value.
Additionally:
During above fix, 2 more attributes were found to be …
> ZBUG-1403: Not able to set zimbraDistributionListSendShareMessageToNewMembers on Dynamic Distribution lists

- store/src/java/com/zimbra/cs/service/UserServlet.java
ZBUG-2390 is about briefcase content being accessible without two-factor authentication.
As a solution to such issue, the `UserServlet` class has been updated with additional rules that evaluate the following conditions:
- Two-factor authentication is enabled or required for the target account, and
- Authentication to the servlet happened through Basic Authentication and not through Cookie-based Authentication.
If all of the above conditions are true, then content will be denied with HTTP `401 Unauthorized` response status code.
- _Two-Factor Authentication Enabled_ means that two-factor authentication has been set up by the account, whether required or not by the class of service.
- _Two-Factor Authentication Required_ means that two-factor authentication is required by the class of …
> ZBUG-2390: briefcase content accessible without 2FA

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java-test/com/zimbra/cs/service/account/ClientInfoTest.java
- store/src/java/com/zimbra/cs/service/account/ClientInfo.java
Webclient needs the list of SAML extension logout urls to be compared with **zimbraWebClientLogoutURL** during ClientInfoRequest and to decide whether to skip logoff of token de-registration. 
During ClientInfoRequest, backend will read this list from LC **zimbra_web_client_logoff_urls** which will be a space separated list of URLs and compare to **zimbraWebClientLogoutURL** for any match and if present will respond with zimbraWebClientSkipLogoff TRUE else FALSE
* Webclient can use this to end session, then send the user to the logout url to end tokens.
> ZCS-11318 Add zimbraWebClientSkipLogoff to ClientInfo. LC implementation for patch support.

- store/src/java/com/zimbra/cs/service/admin/GetDomainInfo.java
Issue
New attribute added GetDomainInfoResponse in https://github.com/Zimbra/zm-mailbox/pull/1264 was missing the attribute zimbraWebClientSkipLogoff during login when user is not authenticated.
Fix
Included the attribute zimbraWebClientSkipLogoff in GetDomainInfoResponse during login
> ZCS-11372: updating domain info attrs to include zimbraWebClientSkipLogoff during login

- store/conf/unbound.conf.in
**Problem :**  dnscache service does not support DNSSEC validation
**Fix :** This issue is due to anchor key file (/opt/zimbra/conf/root.key) is not present, to fix this need to generate anchor key file and add anchor key file path in /opt/zimbra/conf/unbound.conf.in
**Refer:**  Check the man page of "unbound-anchor" to get more details about the anchor key.
less  /opt/zimbra/common/share/man/man8/unbound-anchor.8
Related PR: https://github.com/Zimbra/packages/pull/154
> ZBUG-2723 : add anchor key file path in unbound.conf.in

- store/src/java/com/zimbra/cs/service/account/ToXML.java
Issue:
zimbraPasswordAllowUsername attribute not added hence result in null value to frontend .
Fix:
Include zimbraPasswordAllowUsername attribute in response and corresponding value
Test:
Manual test, able to see correct and required values for zimbraPasswordAllowUsername attribute in response
> ZCS-11379: Add zimbraPasswordAllowUsername in reset password response

- common/src/java/com/zimbra/common/localconfig/LC.java
**Problem**
From regression testing, we found some login issues in Desktop and Web.
**Solution**
We have decided that we will set default value zimbra_same_site_cookie to Empty.
> ZCS-11344: set default value of SameSite cookie to empty

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/gal/GalSearchControl.java
**Problem:**
Toggle off direct searches for autocomplete and galsync against Zimbra LDAP
**Solution:**
Created a localconfig attribute **zimbra_gal_fallback_ldap_search_enabled** to toggle off/on direct searches for autocomplete and galsync against Zimbra LDAP. 
The default value of this attribute is TRUE.
> ZCS:-11349: Toggle off/on direct searches for autocomplete

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
https://jira.corp.synacor.com/browse/ZCS-11402
Issue:
Null Pointer Exception while creating Account when Local Config allow_username_within_password is set to true
Code fix:
The issue was basically in `checkPasswordStrength()` method the comparison of `password` and `username` was based on the username available from the account object. But while creating an account `acct` object passed was null hence when we try to get the username out of null we would get NPE. To resolve this created an overloaded method that accepts `username` in the parameter and modified the comparison based on the username available or not
Testing:
Creating Account from Admin UI, Terminal. Tested the Restpassword and Changepassword API. Working as expected
> ZCS-11402:Null Pointer Exception while creating Account when Local Config allow_username_within_password is set to true

- store/build.xml
Upgraded CXF jars and dependent Spring Jars
Verified EWS is working.
https://github.com/Zimbra/zm-ews-store/pull/45
https://github.com/Zimbra/zm-zcs-lib/pull/91
> ZCS-11282: updating apache cxf version

- store-conf/conf/log4j.properties.production
- store/build.xml
- store/ivy.xml
Issue1 :- Getting error in zmmailbox.out
2022-05-24 10:17:10,417 threads.csv ERROR Unable to write to stream TCP:zqa-226.eng.zimbra.com:4560 for appender sloggerAppender org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to TCP:zqa-226.eng.zimbra.com:4560: socket not available
at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:214)
at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:190)
Solution:- An upgrade to log42 requires change in the default port of system logger i.e. 514 and protocol needs to be mentioned.
Reference :-
Issue 2:- Getting below in the logs.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation …
> ZCS-11435 : Adding port and protocol in syslogger

- store/src/java/com/zimbra/cs/mailbox/MailSender.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
**Problem:**
Error 502 issue while executing SOAP automation on Zimbra 9 Patch25 and 8815 Patch32 builds
**Impact:** 
During soap automation, QA found 502 and 504 errors.
**Solution:**
For the next release, we are reverting the ZBUG-2310 fix and will work on the new solution.
> Revert "ZBUG-2310:Emailed contacts not updating"

- store/src/java/com/zimbra/cs/mailbox/CalendarItem.java
**Problem:**
Replies from attendee on single instance caused meeting series update.
 
**Fix Made:**
* Added exception creation mechanism for the calendar event on attendee side.
* Every Exception should have a different mailItemId assigned. Handled it by adding an else block in mailbox.
**Use Case Tested - ActiveSync version 16.0:**
1. As n2 user from ZWC, send recurring meeting series invite to n1 user to attendee n1 on device
2. Sync calendar of n1 on device and accept meeting series
3. Modify one of the instance response to Maybe or Decline.
4. Verify that response email is sent to organizer and response is updated on attendee calendar in device and ZWC, organizer ZWC
 
 
**Note:**
This fix is for below tickets:
* https://jira.corp.synacor.com/browse/ZCS-10995
* …
> ZCS-10995: Activesync 16.0 : Changing one of the instance response from device as attendee is not syncing due to NullPointer exception

- common/src/java/com/zimbra/common/soap/AccountConstants.java
- common/src/java/com/zimbra/common/util/ZimbraCookie.java
- soap/src/java/com/zimbra/soap/account/message/AuthRequest.java
- store/src/java/com/zimbra/cs/account/AuthToken.java
- store/src/java/com/zimbra/cs/account/ZimbraAuthToken.java
- store/src/java/com/zimbra/cs/account/ZimbraJWToken.java
- store/src/java/com/zimbra/cs/service/account/Auth.java
**Problem**
User was not able to login in Zimbra Desktop when SameSite=Strict
**Fix**
Added a new boolean param in AuthRequest named ignoreSameSite, By default its value is false.
If it is set to true then SameSite=Strict will not be added in ZM_AUTH_TOKEN cookie.
**Testing**
Verified on local, able to login in zimbra desktop.
> ZCS-11331: Added ignoreSameSite param, if true will not add Same SiteStrict cookie

- common/src/java/com/zimbra/common/localconfig/LC.java
Issue
With JDK 17 update there were issue seen of thread locks in some load tests and some of the features working.
For e.g. Admin console test were having issue waiting for thread locks, 
```
"qtp572191680-2105:https://zqa-234.eng.zimbra.com:7071/service/admin/soap/GetCertRequest" #2105 prio=5 os_prio=0 cpu=22.97ms elapsed=214.24s tid=0x0000559d344e61c0 nid=0x173 waiting for monitor entry  [0x00007f5ae68ef000]
java.lang.Thread.State: BLOCKED (on object monitor)
at sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(java.base@17.0.2/NativePRNG.java:441)
- waiting to lock <0x00000000a4b8d1c8> (a java.lang.Object)
at sun.security.provider.NativePRNG.engineGenerateSeed(java.base@17.0.2/NativePRNG.java:227)
```
```
java.lang.reflect.InaccessibleObjectException: Unable to make protected …
```
> ZCS-11367: adding java options for JDK 17 performance tunning

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
**Problem Statement**
Add LDAP attributes to store S3 configurations
**Solution**
Added New Attributes:
1. zimbraGlobalExternalStoreConfig -> global level
2. zimbraServerExternalStoreConfig -> server level
> ZCS-11425 Configure LDAP attributes for storing S3 configurations

- store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
(https://jira.corp.synacor.com/browse/ZCS-11453)
(https://jira.corp.synacor.com/browse/ZBUG-2547)
Issue:
Email body not showing properly .. Actually inside the mime it has an unbalanced  '<!—' (comment tag) that has never ended . That’s the reason the content after unbalanced comment tag was stripped out during sanitisation .
Code fix:
I have written one method as checkExtraCommentLine() , to check unbalanced comment tag is there or not . If we are getting unbalanced tag so I am skipping the tag and adding the content & if we are not getting any unbalanced tag then I am adding content as it is .
Test:
Test multiple Mimes with this scenario , it's working as expected .
> ZBUG-2547 : removinging unbalanced comment tag

- common/src/java/com/zimbra/common/util/ZimbraLog.java
- store/src/java/com/zimbra/cs/db/DbVolume.java
- store/src/java/com/zimbra/cs/volume/Volume.java
[Reopening with correct destination branch old PR: https://github.com/Zimbra/zm-mailbox/pull/1281]
Problem:
Need provision to access store_type column from volume table.
Solution:
Modified related classes to access store_type column. We will be modifying these classes again for updating to create a query as part of [ZCS-11429](https://jira.corp.synacor.com/browse/ZCS-11428) and [ZCS-11430](https://jira.corp.synacor.com/browse/ZCS-11430)
> Feature/zcs 11429: Accessing store_type column from volume table

- common/src/java/com/zimbra/common/util/ZimbraLog.java
**Issue**
No INFO logs after deploying the zimlets
**Fix**
We were using Configurator.initialize() this was causing issue and have replaced with Configurator.reconfigure().
> ZBUG-2834: Using configure() to configure log4j instead of initialize()

- store-conf/conf/log4j.properties.production
Issue :- Bydefault syslogs where getting enabled as there was no flag to check weather to enable or disable syslogs.
Fix:- Added pre existing flag zimbraLogToSyslog to check either to enable or disable, by default the flag is FALSE.
> ZBUG-2841 : Disable Syslog log submission by default in log4j V2

- store/src/java/com/zimbra/cs/account/Account.java
As per ZCS-11603 ticket requirement, a new method has been added to the `Account `class in order to encapsulate the local config `allow_username_within_password `property, in order to be accessed from Classic UI.
This is a technical requirement from ZCS-11302. Please check ticket for more information.
Please check ticket for more information.
> ZCS-11603: Users should not be allowed to use username in the password (Backend)

- store-conf/conf/log4j.properties.production
Issue :- Bydefault slogger level was set to info which caused unnecessary logs getting filled in /var/log folder.
Fix:- Set  default log level to off
> ZBUG-2849 : Disabling stats logger by default

- store/src/java/com/zimbra/cs/lmtpserver/ZimbraLmtpBackend.java
ZCS-11699 is about improving the performance of a new functionality introduced with ZCS-11096, which is in charge of prepending a "warning" text to the message when it comes from outside of the organization for which the receiving account belongs. With such feature, some parsing routines where introduced and executed even when the feature was disabled, thus causing unnecessary workload in the scenario of having the feature disabled.
For this fix we have added additional logic on the `ZimbraLmtpBackend `class in order to make sure that the relevant message parsing routines get executed only if necessary (i.e. when the warning feature is enabled).
Please consider that there will be extra workload when the feature is actually enabled, but this is an expected trade-off from getting to parse …
> ZCS-11699: adding check to verify zimbra_external_email_warning is enabled before updating the content

- common/src/java/com/zimbra/common/localconfig/LC.java
**Problem:**
new emails are not getting synched for outlook app on device for active-sync
**Fix:**
changed the LC attribute value as zimbra_activesync_heartbeat_interval_min=180
earlier it was 300 but the client send request with value 180, so status 5 is being set and no further emails are getting synched.
**Test-cases:**
Added account on outlook app on device, mails get synched initially, then sent more mails in that account, got expected result. Mails are continuously getting synched.
> ZCS-11731 new emails are not getting synched for outlook app on device for active-sync

- store/src/java/com/zimbra/cs/volume/VolumeCLI.java
Feature/ZCS 11436-new changes in the validation of root path in case of external store type
**Original PR:** https://github.com/Zimbra/zm-mailbox/pull/1305
> Feature/zcs 11436-new changes in validation of root path in case of external store type

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Adding ldap attribute **zimbraActiveSyncVersion** to support user level active sync version along device type check on account, cos, and domain.
https://github.com/Zimbra/zm-sync-store/pull/64
> ZCS-11299: adding ldap attr for user specific active sync protocol version and device type

- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/admin/message/ValidateS3BucketReachableRequest.java
- soap/src/java/com/zimbra/soap/admin/message/ValidateS3BucketReachableResponse.java
creating a new SOAP API to test the S3 configuration which will be accepting the following set of parameters and at the server-side, it will make a test request to the s3 bucket to verify if that bucket is reachable or not.
URL
Bucket Name
Access Key
Secret Key
Region
Created new API
ValidateS3BucketReachableRequest
ValidateS3BucketReachableResponse
Request -
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:zimbra" xmlns:urn1="urn:zimbraAdmin">
soapenv:Header
urn:context
urn:authToken0_6a08477669d3d95ceadf1c38197a64ff47ed542c_69643d33363a31393531643831632d313362372d346139662d386337352d3262306537363963636465363b6578703d31333a313635383236313934343239383b61646d696e3d313a313b747970653d363a7a696d6272613b753d313a613b7469643d393a3937303333343737363b766572 …
> ZCS-11657: Create New SOAP API for testing S3 bucket config

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Issue
LDAP attribute ID's for zimbraFeatureSafeUnsubscribeFolderEnabled, zimbraPrefCalenderScaling, zimbraActiveSyncVersion in conflict zimbrax IDs
Fix
Incremented the IDs for these attributes to not conflict with attribute IDs of zimbrax
> ZCS-11824: updating ldap attribute ids

- store-conf/conf/custom-mimetypes.xml
Issue
Preview for RTF file in email attachment is showing the file code instead of text content as the content type being detected for rtf is text/plain
Fix
Added custom mime type support for detecting the correct mime type for RTF files to show content type as application/rtf
> ZCS-11823: add custom mime type for rtf file detection

- store-conf/conf/custom-mimetypes.xml
Issue
Email message added as attachment to email fails to detect mime type and gives content type as text/plain
Fix
Update Tika message/rfc822 mime type which was failing to detect content type for email message added as attachment to ticket that don't have extension
https://issues.apache.org/jira/browse/TIKA-3106
https://github.com/apache/tika/commit/9e53cec0601d7db7dbc49969a78922c708cdafdf
> ZCS-11445: add fix for detecting message mime type for tika if no extension

- common/src/java/com/zimbra/common/localconfig/LC.java
- store-conf/conf/msgs/ZsMsg.properties
- store/src/java/com/zimbra/cs/store/file/FileBlobStore.java
ZCS-11440 is about adding support for S3-to-S3 movement when it comes to executing the existing HSM policy (i.e. when both primary and secondary volumes are S3 Buckets). The solution works by adding a few new classes and updating existing classes in the `zm-hsm-project`, such as the `ZimbraBlobMoverAdaptor` and `BlobMoverThread` classes respectively.
Now, regarding the `zm-mailbox` project, a new `zimbra_hybrid_blob_mover_enabled` local config property has been added, which default to `false`, for safety purposes (i.e. making easy to handover among the current `BlobMover` and new `ZimbraBlobMoverAdaptor`).
Please go to ticket for further details.
> ZCS-11440: ZimbraBlobMover: add support for blob movement from S3 to S3

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/ivy.xml
- soap/src/java/com/zimbra/soap/admin/type/BaseExternalVolume.java
- soap/src/java/com/zimbra/soap/admin/type/VolumeExternalInfo.java
- soap/src/java/com/zimbra/soap/admin/type/VolumeExternalOpenIOInfo.java
- soap/src/java/com/zimbra/soap/admin/type/VolumeInfo.java
- store/src/java/com/zimbra/cs/service/admin/ModifyVolume.java
- store/src/java/com/zimbra/cs/service/util/VolumeConfigUtil.java
- store/src/java/com/zimbra/util/ExternalVolumeInfoHandler.java
ticket - https://jira.corp.synacor.com/browse/ZCS-11675
Api changes is written to configure OpenIO storage as external volume for primary or secondary storage.
Here is the list of parameters that are required for OpenIO storage.
URL
Account
Namespace
Proxy port
Account port
API:
Following APIs will need to be changed/tested to implement OpenIO support:
CreateVolumeRequest
GetVolumeRequest
GetAllVolumeRequest
ModifyVolumeRequest
DeleteVolumeRequest
added all the request & response details on the ticket
- Fixed formatting comments, added null check for properties, and removed unnecessary boolean validations
- assorted bug fixes
> ZCS-11675 Add support for OpenIO volume configuration.

- store/src/java/com/zimbra/cs/volume/VolumeCLI.java
- store/src/java/com/zimbra/util/ExternalVolumeInfoHandler.java
Problem: 
Enhance zmvolume CLI to support OpenIO volume type
Solution:
Added constants, logic and validation in case user adds OpenIO as storage.
Following attributes are mandatory:
•	URL
•	Account
•	Namespace
•	Proxy port
•	Account port
Fix mode:
Code fix
Test Done:
Manual testing done after creating volumes with the OpenIO mandatory parameters.
Id\f we do not add required parameters then it throws exception message and shows help menu how to use -options.
List(-l) is working fine.
Delete(-d) is working fine.
Edit(-e) is working fine.
Help(-h) is showing description of new added OpenIO attributes.
> ZCS-11785: Enhance zmvolume CLI to support OpenIO volume type

- common/src/java/com/zimbra/common/mailbox/FolderConstants.java
- common/src/java/com/zimbra/common/soap/MailConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/mail/message/FileSharedWithMeRequest.java
- soap/src/java/com/zimbra/soap/mail/message/FileSharedWithMeResponse.java
- store/src/java/com/zimbra/cs/mailbox/Document.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/mailbox/Metadata.java
- store/src/java/com/zimbra/cs/redolog/op/CreateFileSharedWithMe.java
- store/src/java/com/zimbra/cs/service/mail/DelegatableRequest.java
- store/src/java/com/zimbra/cs/service/mail/FileSharedWithMe.java
- store/src/java/com/zimbra/cs/service/mail/MailService.java
- store/src/java/com/zimbra/cs/service/mail/SearchResponse.java
- store/src/java/com/zimbra/cs/service/mail/SendShareNotification.java
- store/src/java/com/zimbra/cs/service/mail/ToXML.java
- store/src/java/com/zimbra/soap/ZimbraSoapContext.java
Problem: As of current when the file is shared i.e. User A shares any file with User B then the file is shared as an accessible link on the mail. So assume when I have to access the file again after a month I receive I'll have to scroll down to check the mail where the link was shared. By any chance, if that mail is deleted from the grantee's side, they won't be able to access it again and have to ask for resharing of the file
Solution: To overcome the above issue we came up with a solution i.e. to create a system folder `File Shared with` Me under the briefcase tab. Now when user A shares the file with User B, the file is accessible via the link, and also file is available under the File Shared with Me folder. This file can be previewed upon clicking, and based on the rights provided …
> ZCS-11694 : File Shared with me implementation

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Issue
LDAP attrs zimbraFeatureZulipChatEnabled, zimbraZulipChatDomainId, zimbraFeatureDocumentEditingEnabled, zimbraDocumentRecentlyViewedEnabled not in sync with zimbra cloud.
Fix 
Update IDs in sync with zimbra cloud
> ZCS-11925: updating ldap attr ids to be in sync with zimbra cloud

- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
**Problem**:
There NPE getting thrown while deleting blobless mail items such as task, tag, etc.
**Solution**:
Recently we introduce multiple StoreManagers for working with multiple volumes of different types and store managers get pulled based on locator values, here we are getting NPE for items that don't have blobs. Added null checks for blob before trying to access its locator. 
1. Tag, Task, contact, and Calender Item Deletion.
2. Delete Contact Group
3. Delete Account and SyncGalAcccountRequest
4. Delete Domain
5. Delete Emails
> ZCS-11938: NPE for tag/contact/appointment delete action

- store/ivy.xml
- store/src/java-test/com/zimbra/cs/db/DbVolumeBlobsTest.java
- store/src/java-test/com/zimbra/cs/imap/MemcachedImapCacheTest.java
- store/src/java-test/com/zimbra/cs/service/mail/GetFolderTest.java
- store/src/java-test/com/zimbra/cs/service/mail/ParseMimeMessageTest.java
- store/src/java-test/com/zimbra/cs/store/MockStoreManager.java
All the errors and failures in tests have been fixed, except by:
- testBugZCS10594 (OwaspHtmlSanitizerTest)
- Contacted Rupesh for possible fixes
- testBug64974 (OwaspHtmlSanitizerTest)
- Contacted Rupesh for possible fixes
The following test failures were present in 9.0.0 builds. They will be fixed in a different ticket:
- testAdditionalQuotaProviderExceedsQuota (MailboxTest)
- testResendRecoveryCodePositiveAndNegativeScenarios (RecoverAccountTest)
- testResetPasswordUtilFeatureDisabled (RecoverAccountTest)
To run the tests locally, run inside zm-mailbox/store: ant clean test
Ticket: https://jira.corp.synacor.com/browse/ZCS-11935
> ZCS-11935: Check and Fix exceptions logged in build logs for test failures

- store/src/java/com/zimbra/cs/service/SharedFileServlet.java
- store/src/java/com/zimbra/cs/service/account/GetInfo.java
- store/src/java/com/zimbra/cs/util/AccountUtil.java
Document editing feature will be enabled iff Document editing server host is set ie value of ldap attribute `zimbraDocumentServerHost` must be set otherwise feature will be disabled even if  it is enabled at account level.
> ZCS-11929: Enabling doument feature is documentServerHost value is set

- store/src/java/com/zimbra/cs/util/AccountUtil.java
This method was removed but when did rebase for ZCS-11929 its inserted back, so removing this.
> ZCS-11929: Removed unnecessary method as it was removed before

- store/src/java/com/zimbra/cs/servlet/ContextPathBasedThreadPoolBalancerFilter.java
Simple change to log thread overload instances as ERROR instead of INFO.
> ZBUG-2511: Log thread overload as ERROR

- store/src/java-test/com/zimbra/cs/zimlet/ProxyServletTest.java
- store/src/java/com/zimbra/cs/zimlet/ProxyServlet.java
**Problem**: https://jira.corp.synacor.com/browse/ZBUG-2914 describes this as a potential issue, but gives no indication of an actual problem in the real world.  So, going by the details and proposed fixes in that description, we want to prevent a proxied request from following any redirect that isn't also on our whitelist.
**Solution**: First, I wrote a custom redirect strategy that checked our whitelist. That should stop us from being redirected while the proxying request is running. Then I needed to re-check any ultimate "Location" header sent to report the proper client error  instead of allowing that header to fall through and (probably) fail due to existing browser CORS restrictions.
**Testing**: I grabbed a small URL-shortening go project to generate redirects and ensured our proxy …
> ZBUG-2914: Proxy servlet SSRF

- store/src/java/com/zimbra/cs/datasource/SyncUtil.java
Issue:- ABQ zmmdmmailschedule not picking up correct admin email account in multinode setup
Solution:- Added null checks and length check for array values and took values from all admin account if no value provided.
> ZCS-12059 : Take all admin accounts if values are not set for email in zmmdmmailschedule utility

- store/src/java/com/zimbra/cs/imap/Literal.java
- store/src/java/com/zimbra/cs/store/file/FileBlobStore.java
**Problem:**
Can not delete emails that got moved to S3 storage from IMAP/POP/EWS account. In the case of IMAP/POP/EWS clients, in delete operations email gets moved to the "trash" folder first basically email gets copied to the trash folder. So here external storage(ExternalBlob) item getting copied to internal storage(VolumeBlob), and in the copy operation, it was failing due to incompatibility of Blobs for identifying source volume id. 
**Solution**
when there are multiple StoreManagers(internal(primary) and external(secondary) volumes configured), make sure we are using the right method to extract source volume.
> ZCS-12058 Can not delete mails which got moved to S3 storage from IMAP/POP/EWS account

- store/src/java/com/zimbra/cs/service/UserServlet.java
- store/src/java/com/zimbra/cs/service/formatter/FormatterFactory.java
**Issue**
On a multinode setup where onlyoffice package is not installed, extension does not gets initialized causing the preview to be used from convertd as the LC **oo_linux_install_path** is not having updated to onlyoffice.
**Fix**
During multionode setup if the mailbox is not having onlyoffice installation and is being installed as standalone, onlyoffice formatter will be registered since the check from formatter registration of onlyoffice will happen at run time during formatter resolving. Extension will get initialzed and formatter will register. 
During the formatter resolving, it will be checked if there is any standalone onlyoffice installation available from **zimbraDocumentServerHost** ldap attr. If the attr is set then the formatter will be resolved to onlyoffice. …
> ZCS-12029: remove LC dependancy of onlyoffice formatter usage with adding check for zimbraDocumentServerHost

- common/src/java/com/zimbra/common/util/ZimbraLog.java
**Problem**
Some log files were failed to initialize only .log extension was supported
**Fix**
Found we were using indexOf() which were really didn't required. So removed and using logfile name as it is.
> ZCS-11798: Removed indexof() method causing issue was not required

- store/src/java/com/zimbra/cs/service/mail/ItemActionHelper.java
- store/src/java/com/zimbra/cs/service/mail/RemoveAttachments.java
- store/src/java/com/zimbra/cs/store/external/ExternalStoreManager.java
**Problem**:
Not able to delete emails from IMPAC client when blobs are moved from External Storage(Primary) to Internal Storage(Secondary).  In the case of IMAP/POP/EWS clients, in delete operations email gets moved to the "trash" folder first basically email gets copied to the trash folder. So here Internal storage(VolumeBlob) item getting copied to External storage(ExternalBlob), and in the copy operation, it was failing due to incompatibility of MailBlobs.
**Solution:**
StoreManagers(External(primary) and Internal(secondary) volumes configured), make sure we are using the right store manager to extract source.
> ZCS-12078 Storage management: Can not delete mail in IMAP clients

- store/src/java/com/zimbra/cs/service/UserServlet.java
**Issue**
Document request from sharing resulting into NPE for getting DocumentServerHost 
`2022-08-28 16:44:22.058:WARN:oejs.HttpChannel:qtp364604394-230: /service/home/pa1@zqa-373.eng.zimbra.com/Briefcase/Sfolder2/bug65079.txt
java.lang.NullPointerException: Cannot invoke "com.zimbra.cs.account.Server.getDocumentServerHost()" because "server" is null
at com.zimbra.cs.service.UserServlet.resolveFormatter(UserServlet.java:910)
at com.zimbra.cs.service.UserServlet.doAuthGet(UserServlet.java:697)
at com.zimbra.cs.service.UserServlet.doGet(UserServlet.java:402)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)`
**Fix**
Added null check for server
> ZCS-12108: add null check for auth account to get server

- store/src/java/com/zimbra/cs/util/AccountUtil.java
**Issue**
The change made in ZCS-11929 to default value zimbraFeatureDocumentEditingEnabled to false if zimbraDocumentServerHost value is not set and feature is not working as expected.
**Fix**
zimbraFeatureDocumentEditingEnabled was not disable with default value of false on missing value of zimbraDocumentServerHost, made default false and it works.
**Test**
Verified by setting empty value to zimbraDocumentServerHost and on ZWC checked the zimbraFeatureDocumentEditingEnabled is getting false.
> ZCS-12110: fixing the default value of zimbraFeatureDocumentEditingEnabled to false if zimbraDocumentServerHost not set

- common/src/java/com/zimbra/common/localconfig/LC.java
Problem:
OpenIO connector using the default timeout value which is -1, this may lead to mailbox lock if the OpenIO server is in hiccups.
Solution:
Adding timeout for all requests.
> ZCS--121118 timeout for OpenIO connector

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/store/CacheEnabledStoreManagerProvider.java
**Problem:** Local config attributes are null by default for Storage Management.
**Solution:** Loaded Storage Management local config.
> ZCS-12111: null valued key 'zimbra_sm_blob_mover_parallelism_level'

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/ivy.xml
- store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
Problem: When zimbra_use_owasp_html_sanitizer=true, then email wasn't showing up in web client
Issue: The issue was because when zimbra_use_owasp_html_sanitizer=true, OWASP sanitizes email i.e. tries to check all the opening comment tags and closing comment tags are closed. If either is being missed then it errors out email isn't formed properly and we don't see email content in ZWC
Solution: After discussion, we came to a point i.e. in HTML if there is any opening tag without a closing tag then we have included 2 local config 
zimbra_strict_unclosed_comment_tag = false
zimbra_skip_tags_unclosed_Cdata = style
If first is set to false, then there won't be strict checking for close tag and also zimbra_skip_tags_unclosed_Cdata is set to style(suspicious tag) we ignore it from rendering it in …
> ZBUG-2547 : Email contents not shown in Webmail

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- soap/src/java/com/zimbra/soap/JaxbUtil.java
- soap/src/java/com/zimbra/soap/admin/message/EditS3BucketConfigRequest.java
- soap/src/java/com/zimbra/soap/admin/message/EditS3BucketConfigResponse.java
Requirement: Provide the ability to edit the existing S3 bucket.
Solution: Added methods to validate new updated credentials and edit S3 bucket for following credentials via SoapUI as well as CLI:
- URL
- Access Key
- Secret key
- Region
Added supported Constants and EditS3BucketConfugRequest/Response files are created in zm-mailbox repo.
Link to another PR : [#37](https://github.com/Zimbra/zm-hsm-store/pull/37)
> ZCS-12030: [Backend] Provide ability to edit the added S3 bucket

- store/src/java/com/zimbra/cs/account/auth/AuthContext.java
- store/src/java/com/zimbra/cs/service/account/Auth.java
ZBUG-2858 add SOAP port to authentication context for use with ZimbraCustomAuth
> ZBUG-2858 add SOAP port to authentication context for use with ZimbraCustomAuth

- store/src/java/com/zimbra/cs/mailbox/Notification.java
- store/src/java/com/zimbra/cs/service/util/SpamHandler.java
Some mails generated by Zimbra lack a Date header, which violates RFC5322 (section 3.6, exactly one Date header is mandatory).
> ZRFE-991: Add a Date header to Zimbra-generated mails.

- common/src/java/com/zimbra/common/localconfig/LC.java
- common/src/java/com/zimbra/common/soap/AdminConstants.java
- common/src/java/com/zimbra/common/soap/SyncConstants.java
- soap/src/java/com/zimbra/soap/admin/message/GetDeviceStatusRequest.java
- soap/src/java/com/zimbra/soap/admin/type/DeviceStatusInfo.java
- store/src/java-test/com/zimbra/cs/datasource/SyncUtilTest.java
- store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java
- store/src/java/com/zimbra/cs/datasource/SyncUtil.java
Issue :- All users configured in devices are not shown on ABQ MDM UI in admin console. Only 1 node users are shown on ABQ MDM UI in admin console. For other node configured users, we need to search that user and then we can see.
Solution:-
Making multi server call and getting data from each server.
Collating limited data from each server to display on UI.
Added getter missing getter methods in DeviceStatusInfo
> ZCS-11957 : Adding getter method for emailAddress and timeStamp

- common/src/java/com/zimbra/common/soap/MailConstants.java
- store/src/java/com/zimbra/cs/service/mail/ToXML.java
Tcket : [ZCS-11802](https://jira.corp.synacor.com/browse/ZCS-11802)
Issue: Deleted/permanently deleted files remains visible in the "Files shared with me" folder
1)Basically when the Owner file is deleted the file remains available at the grantee's end. 
2)The issue also persisted when a folder is shared and the subsequent file is shared with another user, and when the main folder is deleted file would still be present
The PR https://github.com/Zimbra/zm-mailbox/pull/1410 basically solved issue 1 , but during code review we came across 2nd situation
Hence to solve this all at once, we will provide the grantee an option to delete the file from their end 
When the owner deleted the file, the grantee has that file. Grantee tries to view the file, he would get a 404 exception,in this …
> ZCS-11802 : Backend implementation to show exact Item Id in search response

- soap/src/java/com/zimbra/soap/mail/message/FileSharedWithMeRequest.java
- store/src/java/com/zimbra/cs/db/DbMailItem.java
- store/src/java/com/zimbra/cs/mailbox/Mailbox.java
- store/src/java/com/zimbra/cs/service/mail/FileSharedWithMe.java
- store/src/java/com/zimbra/cs/service/mail/ItemAction.java
Ticket: https://jira.corp.synacor.com/browse/ZCS-11801
Issue: Modifying file at grantee side doesn't update file size, time, new name and doesn't convert from .txt to .docx file format
Solution: 
.txt to .docx -> When file is shared, if file is in .txt format we need to convert it to .docx format and share.
Rename -> Update Item action request rename function , i.e. whenever file is renamed ACl object files should also be accordingly renamed
file size and time -> In this scenario whenever file revision is created we need to make sure updated file size and time is also updated at receiver end
> ZCS-11801 : Modifying file at grantee side doesn't update file size, time, new name and doesn't convert from .txt to .docx file format

- common/src/java/com/zimbra/common/localconfig/LC.java
Adding LC config for ClamAV timeout and data chunk size
> ZBUG-3129 - adding LC config for ClamAV timeout and data chunk size

- store/src/java/com/zimbra/cs/service/admin/GetDomainInfo.java
**Problem:**
When accessing login page with the URL specified in zimbraVirtualHostname, zimbraPrefSkin of the domain is not applied on the login page.
For example, set skin and virtualhostname of a domain as follows
```
$ zmprov md domain2.dev.zimbra.com zimbraPrefSkin serenity zimbraVirtualHostname vdomain2.dev.zimbra.com
```
and access `https://vdomain2.dev.zimbra.com`, css or messages of serenity skin is not loaded. Instead, default skin defined in `zimbra.web.xml.in` is loaded.
**Change:**
Adding `zimbraPrefSkin` to `GetDomainInfo`.
> ZCS-12547: added zimbraPrefSkin to GetDomainInfo

- common/src/java/com/zimbra/common/soap/SyncConstants.java
Issue :- MailApp able to send mail after blocking via reply/forward of inbox mail..
Fix :- Added block check while reply/forward and send mail..
https://github.com/Zimbra/zm-sync-store/pull/101
> ZCS-12192 : Added constants for active sync - SendMail, SmartReply, SmartForward

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Requirement of ticket [ZCS-12478](https://jira.corp.synacor.com/browse/ZCS-12478):
- A new Ldap attribute for Modern UI help URL is to be introduced i.e. zimbraHelpModernURL  for Zimbra 11 and cloud.
- Also deprecate zimbraHelpStandardURL for Zimbra 11
Solution:
- New attribute is added and its setters/getters are generated.
- In zimbraHelpStandardURL, depracted tag has been added.
> ZCS-12478 : New Ldap attribute for Modern UI help URL - zimbraHelpModernURL

- store/src/java/com/zimbra/cs/service/account/ClientInfo.java
Requirement of ticket [ZCS-12478](https://jira.corp.synacor.com/browse/ZCS-12478):
Requirement: The values of LDAP attribute zimbraHelpModernURL needs to be fetched in ClientInfo API.
Note: This LDAP attribute was added in PR [#1424](https://github.com/Zimbra/zm-mailbox/pull/1424) and due to frontend requirement of ticket [PSXMAIL-954](https://jira.corp.synacor.com/browse/PSXMAIL-954.), in modern UI the value needs to be fetched from the response of ClientInfo API as getDomainInfo API is not called in Modern UI.
> ZCS-12478: Getting LDAP attr zimbraHelpModernURL in the response of ClientInfo API

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Requirement of ticket  [ZCS-12482](https://jira.corp.synacor.com/browse/ZCS-12482):
> New Ldap attribute to block sending email from external email addresses i.e zimbraBlockEmailSendFromImapPop for Zimbra 11
Solution:
> New attribute is added and its setters/getters are generated.
> ZCS-12482:Adding a new LDAP attribute - zimbraBlockEmailSendFromImapPop

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/service/admin/ComputeAggregateQuotaUsage.java
**Enhancement:**
Add an ability to set domain-specific subject and body in domain aggregate quota warning message.
**Changes:**
* adding new ldap attributes `domainAggrQuotaWarnMsgSubjectKey` and `domainAggrQuotaWarnMsgBodyKey` for a domain
* modifying ComputeAggregateQuotaUsage to use the custom key(s) if it is set.
**Usage:**
1. Add custom keys for subject and body of a domain aggregate quota warning message for a domain. For example,
```
$ diff -c ZsMsg.properties.original ZsMsg.properties
*** ZsMsg.properties.original   2022-12-07 11:20:42.395405534 +0900
--- ZsMsg.properties    2022-12-07 11:21:20.989016621 +0900
***************
*** 333,338 ****
--- 333,340 ----
#
domainAggrQuotaWarnMsgSubject = Domain aggregate quota warning
+ domainAggrQuotaWarnMsgSubjectForDomain1 = Custom Subject …
```
> ZCS-12634: add ability to set domain-specific subject and body in domain aggregate quota warning message

- store/src/java/com/zimbra/cs/extension/ZimbraExtensionNotification.java
- store/src/java/com/zimbra/cs/service/account/Auth.java
- store/src/java/com/zimbra/cs/service/admin/Auth.java
**Enhancement:**
* Add an ability to insert a process into an existing code using extension framework to achieve more flexible customization.
* Add `ZimbraExtensionNotification.notifyExtension` to `Auth.java` (both account and admin) so that a custom validation can be added.
**Approach:**
* add a mechanism to call a extension handler with a notification ID and necessary parameters.
* an extension registers a handler for a notification.
For example,
* `handler1` is registered for `notif-id-A`
* when a process (`process1`) calls `ZimbraExtensionNotification#notifyExtension("notif-ID-A", param1, param2, ..., paramN)`, `handler1#execute` is called. All parameters are passed to `handler1#execute` as `Object[]`.
* In `handler1#execute` process, parameter(s) need to be casted to right class(es). …
> ZCS-12704: adding mechanism to notify extension

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/account/callback/ModernChatVideoEnabled.java
Feature:  New LDAP attributes are required to manage chat and video at the account, cos, and domain level with notification through a callback.
Implementation: 
Added two LDAP attributes zimbraFeatureModernChatEnabled and zimbraFeatureModernVideoEnabled and defined a callback name ModernChatVideoEnabled.
Here, We are using ZimbraExtensionNotification for notifications from https://github.com/Zimbra/zm-mailbox/pull/1431
> ZCS-12779: Add a new LDAP attribute to manage chat and video users

- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrServer.java
This reverts commit a715a0afc7a7590509a9caae9f4e7b306c0c8334.
Currently Backup method is set to auto-grouped. Based on feedback from support as per business requirement, the Backup method should be set to Standard.
> Revert "ZCS-11491 - Changing default backup mode for Backup and Restore"

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
- store/src/java/com/zimbra/cs/service/admin/GetDomainInfo.java
**Enhancement:**
Add attributes for an ability to provide domain-specific login page.
* `zimbraDomainLoginPageEnabled` is a globalConfig to enable/disable the feature. Default value is FALSE for backward compatibility.
* `zimbraDomainLoginPagePath` is a domain config to specify a file path of login page for a domain. 
* `zimbraDomainLoginPageFallbackPath` is a domain config to specify a file path for fallback; if `zimbraDomainLoginPageEnabled` is TRUE and `zimbraDomainLoginPagePath` is empty, `zimbraDomainLoginPageFallbackPath` is used.
* `zimbraDomainLoginPageErrorPath` is a globalConfig to specify a file path in case DomainInfo cannot be fetched in login page for some reason.
The two domain config attributes are added to `GetDomainInfo.bootstrapInfoAttrs` so that they can be fetched on …
> ZCS-12712: added ldap attributes for domain-specific login page

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Renamed the following ldap attributes which have been added on ZCS-12634, PR https://github.com/Zimbra/zm-mailbox/pull/1426
* domainAggrQuotaWarnMsgSubjectKey -> zimbraDomainAggrQuotaWarnMsgSubjectKey
* domainAggrQuotaWarnMsgBodyKey -> zimbraDomainAggrQuotaWarnMsgBodyKey
> ZCS-12778: renamed ldap attributes

- store/src/java/com/zimbra/cs/lmtpserver/ZimbraLmtpBackend.java
**Problem:**
LmtpServer reply message is inaccurate if the value of zimbraDomainAggregateQuota becomes less.
**Approach and Analysis:**
When the zimbraDomainAggregateQuota get exceeded it's limit it throws an inaccurate reply of 554;5.0.0 Permanent message delivery failure where as it should be 552;5.2.2 Over quota if the value of the zimbraLmtpPermanentFailureWhenOverQuotais set to TRUE or the452; 4.2.2 Over quota if the value of the zimbraLmtpPermanentFailureWhenOverQuotais set toFALSE. To fix this condition has been added to handle that if the value of zimbraDomainAggregateQuota` exceeds it's limit then it will throw the appropriate Over quota messages.
Following is my environment and settings:
1. setting  zimbraLmtpPermanentFailureWhenOverQuota TRUE
> …
> ZBUG-1340 Fix for inaccurate LmtpServer reply of zimbraDomainAggregateQuota

- common/src/java/com/zimbra/common/soap/AdminConstants.java
- common/src/java/com/zimbra/common/soap/GlobalExternalStoreConfigConstants.java
- soap/src/java/com/zimbra/soap/admin/type/VolumeExternalInfo.java
- store/src/java-test/com/zimbra/util/ExternalVolumeInfoHandlerTest.java
- store/src/java/com/zimbra/cs/lmtpserver/ZimbraLmtpBackend.java
- store/src/java/com/zimbra/cs/service/admin/CreateVolume.java
- store/src/java/com/zimbra/cs/service/admin/DeleteVolume.java
- store/src/java/com/zimbra/cs/service/util/VolumeConfigUtil.java
- store/src/java/com/zimbra/util/ExternalVolumeInfoHandler.java
This ticket is the solution for [ZCS-12777](https://jira.corp.synacor.com/browse/ZCS-12777)
Requirement: While creating external(S3) Volume two LDAP attribute values which are in JSON format requires some structure modifications. JSON are:
1. zimbraServerExternalStoreConfig: `"unified":"true"` flag should be added. Default value is False.
2. zimbraGlobalExternalStoreConfig: Following structure _server wise_ should be added.
```
"unified/volumes”:{[
"{serverId1}": 
{
"volumeId": 3,
"volumePrefix": "/",
"globalBucketConfigId": "9243fd6d-4a4f-4b58-a695-6aabd726dd73"
}
],
"{serverId2}": []
},
```
Point to consider:
- It is not applicable for OpenIO.
- We cannot edit unified attribute while editing volume.
- Volume API has been modified.
- UI still need to be introduced for unified volume.
- …
> ZCS-12777: CreateVolume SOAP API: Introduce flag for volume for marking volume as unified volume

- soap/src/java/com/zimbra/soap/admin/type/VolumeExternalInfo.java
- store/src/java/com/zimbra/cs/volume/VolumeCLI.java
- store/src/java/com/zimbra/cs/volume/VolumeCLIConstants.java
This ticket is the solution for [ZCS-12787](https://jira.corp.synacor.com/browse/ZCS-12787)
Requirement: While creating external(S3) Volume one new parameter is introduced via CLI i.e. **unified** for supporting unified/centralised storage.
Value accepted for unified is boolean and default value is false. it's value is not editable. 
Solution:
Introduced `-un` option to cater unified parameter, required validation to check value is imposed.
Testing:
Manual testing is done.
Note: This PR is depended on [#1441](https://github.com/Zimbra/zm-mailbox/pull/1441) where the required changes has been made in Create Volume Soap API.
> ZCS-12787:Adding unified volume flag in zmvolume command

- store-conf/conf/log4j.properties.production
Issue :- In a multiserver installation, syslogger does not work if we have a logger server as localhost.
Resolution :- Changing default localhost to zimbraloghostname
> ZBUG-3053 : changing localhost to zimbraloghostname for syslogger

- store/src/java/com/zimbra/cs/zimlet/ZimletUtil.java
**Problem:**
`zmzimletctl deploy zimlet.zip` overwrites all previous zimlet configuration stored in LDAP, back to their defaults.
For example, we had a config change in com_zimbar_url to disable youtubePreview and  this config change had been reverted by deploying the patch.
**Fix:**
Install zimlet config if version updated in latest zimlet config 
Compare latest zimlet config version with zimlet config version stored in LDAP. If latest zimlet config version is higher than the zimlet config version stored in LDAP then install zimlet config, which will override customer's changes and it will loose customer's changes. Customer will take updated zimlet config and apply their customizations and deploy using zmzimletctl.
> ZBUG-2722 : Install zimlet config if version updated in zimlet config

- soap/src/java/com/zimbra/soap/admin/message/SearchDirectoryRequest.java
- store/src/java/com/zimbra/cs/account/SearchDirectoryOptions.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
- store/src/java/com/zimbra/cs/ldap/SearchLdapOptions.java
- store/src/java/com/zimbra/cs/service/admin/SearchDirectory.java
**Problem:**
SearchDirectoryRequest takes a long time on large directory (ISP size).
**Requirements:**
limit parameter is not getting passed to the SearchDirectoryRequest but it should as per it's API document..
If the limit is specified as 0 or if the limit is not specified then it should return everything as per the API document and there should not be any pagination.
If the limit is non-zero and it's specified then it should handle the pagination.
**Analysis and Approach:**
SearchDirectoryRequest takes a long time on large directory which only happens for a large directory sites such as ISP who has +1M accounts because it always sends with paged search options like -E pr=1000 whether limit is specified as limit="0" or not. And as per SearchDirectoryRequest API document maxResults is …
> ZBUG-733 SearchDirectoryRequest takes a long time on large directory (ISP size)

- store/src/java/com/zimbra/cs/filter/jsieve/Discard.java
- store/src/java/com/zimbra/cs/imap/ImapHandler.java
**Requirement:**
1. log event when discard filter action is called.
2. Change the log level of IMAP SEARCH command from info to debug
Created a discard filter with a Subject contains spoof.
Checked from CLI for zimbraMailSieveScript
> zimbra@platform-dev-activesync:~$ zmprov ga admin@platform-dev-activesync.zimbradev.com zimbraMailSieveScript name admin@platform-dev-activesync.zimbradev.com
zimbraMailSieveScript: require ["fileinto", "copy", "reject", "tag", "flag", "variables", "log", "enotify", "envelope", "body", "ereject", "reject", "relational", "comparator-i;ascii-numeric"];
spoof
if allof (header :contains ["subject"] "spoof") {
discard;
stop;
}
Mailbox.log 
`2023-02-06 06:55:09,178 INFO  [LmtpServer-621] [ip=10.0.0.68;] lmtp - Delivering message: size=2613 bytes, …
> ZCS-12876 | ZCS-12878 logging changes for discard filter in mailbox logs & debug level for IMAP SEARCH command

- store/src/java/com/zimbra/cs/account/AccountServiceException.java
- store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
**Issue:**
When LdapException is raised at creating signature, an inappropriate message is shown on web client.
**Fix:**
Changed to throw ServiceException with a signature name.
> ZCS-12748: fixed to throw ServiceException with signature name

- store/src/java/com/zimbra/cs/extension/ZimbraExtensionNotification.java
- store/src/java/com/zimbra/cs/mailbox/MailSender.java
Adding `ZimbraExtensionNotification.notifyExtension` to replace X-Mailer header using an extension.
An extension cannot return any value. Then a reference of string array `String[] customXMailer` is passed to an extension. The extension can set a preferred string for X-Mailer header.
If no extension is called or no value is set by an extension, default string is used.
> ZCS-12826: added a logic to set custom X-Mailer header

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/filter/FilterUtil.java
- store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
- store/src/java/com/zimbra/cs/filter/jsieve/AddHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/DeleteHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/Discard.java
- store/src/java/com/zimbra/cs/filter/jsieve/ReplaceHeader.java
- store/src/java/com/zimbra/cs/filter/jsieve/VariableLog.java
- store/src/java/com/zimbra/cs/lmtpserver/ZimbraLmtpBackend.java
- store/src/java/com/zimbra/cs/mailbox/Message.java
**Fix**: added an LC config: **lmtp_extended_logs_enabled**
when the value of the parameter is True, the extended log with sender and messageId is logged at the "info" level,
when the value is False, the existing logs get printed.
> ZCS-12875: Request to extend LMTP log events for easy and clear confirmation of mail delivery

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/src/java/com/zimbra/cs/service/account/ModifyPrefs.java
**Requirement:** 
Log changes in preference settings
1. After setting prefs_settings_value_logging_enabled=TRUE
> 2023-02-17 10:56:40,193 INFO  [qtp2138564891-20:https://platform-dev-activesync.zimbradev.com/service/soap/ModifyPrefsRequest] [name=admin@platform-dev-activesync.zimbradev.com;mid=2;ip=10.0.0.68;port=43338;ua=ZimbraXWebClient - GC110 (Mac)/9.0.0;soapId=7d69d4d4;] account - Setting Preference attributes : [zimbraPrefMailPollingInterval=360; zimbraPrefMailTrustedSenderList=w@w.co,x@x.co,y@y.co,z@z.co,d@d.co; zimbraPrefMailSendReadReceipts=always] 
2. After setting prefs_settings_value_logging_enabled=FALSE
> 2023-02-17 09:56:59,026 INFO  [qtp2138564891-133:https://platform-dev-activesync.zimbradev.com/service/soap/ModifyPrefsRequest] …
> ZCS-12874 log for modifying Preference settings

- common/src/java/com/zimbra/common/localconfig/LC.java
- store/conf/unbound.conf.in
Recently, we have added DNSSEC validation for DNS cache. Currently, there is no attribute to disable the DNSSEC in Zimbra config.
There should be an attribute to enable/disable DNSSEC because if any DNS server does not support DNSSEC then DNS cache will fail.
Added a boolean value local config `zimbra_enable_dnssec`. Default should be true.
When set to false, the DNSSEC validation should be disabled.
> ZBUG-2929 : adding LC zimbra_enable_dnssec to enable/disable DNSSEC

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
**Problem:**
When millions of accounts exist on the system and CountObjectsRequest with userAccount type is sent from Admin Console to a server, it causes high load on a ldap server.
**Fix:**
Intoduced Ldap attr to enable/disable the counting of userAccount in CountObjectsRequest
**Test-cases:**
1. when zimbraCountObjectsEnabled is TRUE
send CountObjectsRequest with account or userAccount type.
show number of accounts in Home -> Summary -> Accounts and Manage -> left pane -> the number of accounts
2. when zimbraCountObjectsEnabled is FALSE
not to send CountObjectsRequest with account or userAccount type.
show N/A in Home -> Summary -> Accounts and Manage -> left pane -> the number of accounts
> ZCS-12966 Ldap attribute for CountObjectsRequest on admin console changes

- store/src/java/com/zimbra/cs/imap/ImapHandler.java
- store/src/java/com/zimbra/cs/imap/NioImapHandler.java
- store/src/java/com/zimbra/cs/pop3/NioPop3Handler.java
- store/src/java/com/zimbra/cs/pop3/Pop3Handler.java
- store/src/java/com/zimbra/cs/pop3/Pop3Mailbox.java
- store/src/java/com/zimbra/cs/server/NioConnection.java
**Requirements:**
Log session summary of POP3 and IMAP
**POP3**
Mailbox size (byte size) and total number of messages in INBOX at the login, and at the log out
Total read and write data bytes during the session
Session's duration time in milliseconds
The number of executions of the following commands during the session
TOP
RETR
DELE
QUIT
**IMAP**
Mailbox size (byte size) and total number of messages in INBOX and Trash respectively at the login, and at the log out
Total read and write data bytes during the session
Session's duration time in milliseconds
The number of executions of the following commands during the session
FETCH
STORE
EXPUNGE
APPEND
SEARCH
COPY
CREATE
DELETE
LOGOUT
The number of executions of UID FETCH, UID COPY, UID STORE and UID SEARCH are counted as FETCH, COPY, STORE …
> ZCS-12965 added session summary log on POP3 and IMAP

- common/src/java/com/zimbra/common/account/ZAttrProvisioning.java
- store/conf/attrs/zimbra-attrs.xml
- store/src/java/com/zimbra/cs/account/ZAttrAccount.java
- store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- store/src/java/com/zimbra/cs/account/ZAttrCos.java
- store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Requirement of ticket [[ZCS-12471](https://jira.corp.synacor.com/browse/ZCS-12471)]:
- Two new LDAP attributes to control the recall feature in Zimbra to be introduced for three levels  i.e. account, COS and domain  - zimbraFeatureMailRecallEnabled(default value is FALSE), zimbraFeatureMailRecallTime(default value is 30 minutes and time limit is from 1 minute to 30 minutes ).
Solution:
- Two new attributes are added and their setters/getters are generated. 
Testing:
- Testing is done on remote machine by installing custom build for all the three levels and getting expected results.
> ZCS-12471- adding LDAP attribute for mail recall
