Zimbra/zm-mailbox

store/src/java/com/zimbra/cs/util/WebClientServiceUtil.java, store/src/java/com/zimbra/cs/zimlet/ZimletUtil.java
bringing in changes from Stash in a cleaner manner (reordered to make tab cleanup first and squashed minor changes)
=> Bugfix zms 582

store/src/java/com/zimbra/qa/unittest/TestSearchTask.java, store/src/java/com/zimbra/qa/unittest/ZimbraSuite.java
Added TestSearchTask to ZimbraSuite, updated unit test to create/delete user before/after the test.
=> ZMS-589: TestSearchTask unit test fix

client/src/java/com/zimbra/client/ZMailbox.java, store/src/java/com/zimbra/qa/unittest/TestZClient.java
Implemented _ZMailbox::alterTag_ method, with corresponding unit test.
=> ZMS-225: ZMailbox::alterTag implementation

store/build.xml
Fix ant dependency to generate proper BuildInfoGenerated.java
=> ZCS-1195: Fix dependency to generate proper BuildInfoGenerated.java

store/src/java/com/zimbra/cs/imap/ImapListener.java
I ran the imaptest utility that Rohit used to find this bug and I am not seeing any more NPEs, nor any deadlocks. I added plenty more details in Jira.
=> proposed fix for ZMS-315

build.xml
This change needs other changes in build and deployment, which are being worked on in zm-build repository.
=> ZCS-1097 - Make RPM/DEBIAN packages from zm-mailbox

common/ivy.xml, soap/ivy.xml, store/ivy.xml
Upgrading xercesImpl to 2.9.1-patch-01
=> ZCS-984 Upgrading xercesImpl to 2.9.1-patch-01

store/src/java/com/zimbra/qa/unittest/TestScheduledTaskManager.java
```
<RunUnitTestsResponse numFailed="0" numSkipped="0" numExecuted="3" xmlns="urn:zimbraAdmin">
<results>
<completed name="testSingleTask" class="com.zimbra.qa.unittest.TestScheduledTaskManager" execSeconds="4.88"/>
<completed name="testRecurringTask" class="com.zimbra.qa.unittest.TestScheduledTaskManager" execSeconds="1.98"/>
<completed name="testTaskProperties" class="com.zimbra.qa.unittest.TestScheduledTaskManager" execSeconds="0.32"/>
</results>
</RunUnitTestsResponse>
```
=> ZCS-1116 JUnit Updates

build.xml
Adding publish-local-all target for just publishing local jars
=> Adding publish-local-all target for just publishing local jars

store/build.xml
Quick fix to address issue ZMS-660.
=> ZMS-660 Conflicting HTTP libraries in feature/imap build

store/src/java-test/com/zimbra/cs/filter/EnvelopeTest.java, store/src/java-test/com/zimbra/cs/filter/RejectTest.java, store/src/java-test/com/zimbra/cs/index/query/ContactQueryTest.java, store/src/java-test/com/zimbra/cs/server/ServerThrottleTest.java, store/test-ivy.xml
Skipping failing unit test in 
EnvelopeTest.java
RejectTest.java
ContactQueryTest.java
ServerThrottleTest.java
=> ZCS-1708 Skipping failing unit test

store/src/java-test/com/zimbra/cs/mailbox/ContactAutoCompleteTest.java
Test not compiling due to missing import.
=> ZCS-1708:missing import for Ignore

store/src/java/com/zimbra/cs/mailbox/Mailbox.java, store/src/java/com/zimbra/cs/mailbox/Tag.java, store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
This is a copy of https://github.com/Zimbra/zm-mailbox/pull/201, which was inadvertently closed.
=> ZCS-1547: IMAP notifications for unlisted tags

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
Updated descriptions of _zimbraReverseProxyImapStartTlsMode_ and _zimbraReverseProxyPop3StartTlsMode_ with their respective protocols.
=> ZCS-1787: Fixed descriptions of zimbraReverseProxy(Pop3|Imap)StartTlsMode

store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
this PR is for an integration test that shows that tests for the behavior described in the bug. The test currently fails, because the bug still exists.
=> zcs-1781: add test that captures the bug

client/ivy.xml, client/src/java/com/zimbra/client/ZBaseItem.java, client/src/java/com/zimbra/client/ZFolder.java, client/src/java/com/zimbra/client/ZMailbox.java, client/src/java/com/zimbra/client/ZMountpoint.java, common/src/java/com/zimbra/common/mailbox/ItemIdentifier.java, store/src/java/com/zimbra/cs/imap/ImapHandler.java, store/src/java/com/zimbra/cs/imap/ImapPath.java, store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
Fix various problems with selecting sub folders.
Also problems fetching from shared folders (both top level and sub folders)
=> ZCS-1937 shared sub folder support.

build-common.xml, circle.yml, store/ivy.xml, store/src/java-test/com/zimbra/cs/mailbox/MailboxTestUtil.java, store/src/java-test/com/zimbra/cs/redolog/CommitIdTest.java, store/src/java-test/com/zimbra/cs/redolog/RedoLogManagerTest.java, store/src/java-test/com/zimbra/cs/redolog/TransactionIdTest.java, store/src/java-test/com/zimbra/cs/redolog/logger/FileHeaderTest.java, store/src/java-test/com/zimbra/cs/redolog/logger/FileLogReaderTest.java, store/src/java-test/com/zimbra/cs/redolog/logger/FileLogWriterTest.java, store/src/java-test/com/zimbra/cs/redolog/op/AbortTxnTest.java, store/src/java-test/com/zimbra/cs/redolog/op/CheckpointTest.java, store/src/java-test/com/zimbra/cs/redolog/op/CommitTxnTest.java, store/src/java-test/com/zimbra/cs/redolog/op/CreateMessageTest.java, store/src/java-test/com/zimbra/cs/redolog/op/RedoableOpTest.java, store/src/java/com/zimbra/cs/redolog/CommitId.java, store/src/java/com/zimbra/cs/redolog/RedoLogManager.java, store/src/java/com/zimbra/cs/redolog/logger/FileHeader.java, store/src/java/com/zimbra/cs/redolog/logger/FileLogReader.java, store/src/java/com/zimbra/cs/redolog/logger/FileLogWriter.java, store/src/java/com/zimbra/cs/redolog/op/Checkpoint.java, store/src/java/com/zimbra/cs/redolog/op/CommitTxn.java, store/src/java/com/zimbra/cs/redolog/op/ControlOp.java, store/src/java/com/zimbra/cs/redolog/op/CreateMessage.java, store/src/java/com/zimbra/cs/redolog/op/RedoableOp.java, store/src/java/com/zimbra/cs/store/external/SimpleStoreManager.java
OK, this is the pull request that was submitted by F9 with the following modifications:
First, I rebased out this commit:
8b52117 @Ignore failing or flakey tests so that a continuous build can be setup
Second, did a fresh rebase onto the `develop` branch.  The problem area was in `MailboxTestUtil.java`. Both F9 and the platform team had updated the `initProvisioning` method to correct some test issues.  I combined the changes in the manner I judged to be best, retaining what the platform team had done, but adding in some additional code changes from F9.
After that I ran the unit tests in `zm-mailbox/store` and got a clean test run.
@rupalid The unit tests that had been ignored in the commit that I rebased out are documented [here](https://github.com/Zimbra/zm-mailbox/pull/219).
=> feature/f9-teams (modified pull request from F9)

store/src/java/com/zimbra/qa/unittest/TestTags.java
quick fix. similar to the approach we've taken with other SOAP tests. This just got in the way of proving that my changes for zcs-2272 are working.
=> ZCS-2296: replace user1 with generated user name

store/src/java/com/zimbra/cs/service/authenticator/SpnegoAuthenticator.java
This is the same as https://github.com/Zimbra/zm-mailbox/pull/280 with a couple of cleanup additions.
=> ZCS-2345:Typo correction SpengoAuthenticator -> SpnegoAuthenticator

store/src/java/com/zimbra/qa/unittest/TestWaitSet.java
I had to fix this test in order to make sure my changes for zcs-2272 are not breaking it. The changes are minimal and similar to the changes that we made to most other SOAP tests.
=> zcs-2361: switch to junit4 and generate random usernames

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java, store/src/java/com/zimbra/cs/service/admin/GetAdminExtensionZimlets.java
Allow old admin NE and admin NG to coexist until Delegated Admin rights migration is done.
=> [ZCS-1957]  [NG NE] Allow a better transition for Delegated Admin Modules	

soap/src/java/com/zimbra/soap/admin/type/DataSourceType.java, store/src/java-test/com/zimbra/cs/datasource/DataSourceManagerTest.java, store/src/java-test/com/zimbra/cs/mailbox/MailboxTestUtil.java, store/src/java-test/datasource-test.xml, store/src/java/com/zimbra/cs/account/DataSource.java, store/src/java/com/zimbra/cs/datasource/DataSourceManager.java
add support for custom DataImport implementation and also add unit tests for default and new behavior
=> ZCS-2863: add support for custom DataImport implementation

store/conf/attrs/zimbra-attrs.xml
Removing domainAdminModifiable flag
Ref : https://github.com/Zimbra/zm-mailbox/pull/357
=> ZCS-2728 : Add 2 LDAP attributes for Contacts backup functionality

store/src/java/com/zimbra/cs/imap/ImapMailboxStore.java, store/src/java/com/zimbra/cs/imap/ImapPath.java, store/src/java/com/zimbra/cs/imap/LocalImapMailboxStore.java, store/src/java/com/zimbra/cs/imap/RemoteImapMailboxStore.java, store/src/java/com/zimbra/cs/mailbox/Folder.java, store/src/java/com/zimbra/cs/mailbox/Message.java, store/src/java/com/zimbra/qa/unittest/SharedImapTests.java
Changes related to exploring whether we had any remaining issues related to using only ints for folder IDs in IMAP.
=> ZCS-2287 IMAP and folder IDs

store/src/java/com/zimbra/cs/service/PreAuthServlet.java
Provisioing -> Provision  in the log messages
=> Typo correction

store/src/java/com/zimbra/qa/unittest/TestMetadata.java
* Upgraded TestMetadata to junit4 style
* Creates own user at start and deletes it at end
=> ZCS-3348:TestMetadata junit4/own user

.gitignore, common/src/java/com/zimbra/common/mailbox/MailboxLockFactory.java, store/src/java-test/com/zimbra/cs/mailbox/MailboxLockTest.java, store/src/java-test/com/zimbra/cs/service/mail/CalendarRequestTest.java, store/src/java/com/zimbra/cs/mailbox/LocalMailboxLockFactory.java, store/src/java/com/zimbra/cs/mailbox/Mailbox.java, store/src/java/com/zimbra/cs/mailbox/MailboxManager.java
This is the PR of the active work we are doing on the mailbox lock abstraction.
Please do not merge.
=> Lock Abstraction WIP

common/src/java-test/com/zimbra/common/zmime/ZInternetHeaderTest.java, common/src/java/com/zimbra/common/zmime/ZInternetHeader.java
Updated the error handling code.
=> ZCS-3702(3):Some Spaces removed in RFC 2047 encoded subject

store/src/java/com/zimbra/cs/mailbox/MailSender.java
Add the following data to the log event when the message is sent via SMTP:
- Size (if the size info has already calculated): "size="
- Envelope From: "sender="
- Number of envelope to: "nrcpts="
- Envelope To: "to="
This event will be logged by SendMsgRequest (send message from WebClient)
BounceMsgRequest (redirect message from WebClient), and redirecting by
the Sieve redirect filter.
The event text may be long; to restrict the number of characters in one
log event, the administrator can set the max characters from log4j
configuration:
```
log4j.appender.LOGFILE.layout.ConversionPattern=%d %-5p [%t] [%z] %c{1} - %.10000m%n
```
=> ZCS-3887:Enhancement of SMTP log format

client/src/java/com/zimbra/client/ZMailbox.java, client/src/java/com/zimbra/client/ZRemoteQueryHitResults.java, client/src/java/com/zimbra/client/ZSearchParams.java, common/src/java/com/zimbra/common/mailbox/ZimbraSortBy.java, soap/src/java/com/zimbra/soap/admin/message/SearchMultiMailboxRequest.java, soap/src/java/com/zimbra/soap/mail/message/SearchConvResponse.java, soap/src/java/com/zimbra/soap/mail/message/SearchResponse.java, soap/src/java/com/zimbra/soap/mail/type/MailSearchParams.java, soap/src/java/com/zimbra/soap/type/SearchSortBy.java, store/docs/soap.txt, store/src/java/com/zimbra/cs/db/DbSearch.java, store/src/java/com/zimbra/cs/index/DBQueryOperation.java, store/src/java/com/zimbra/cs/index/ProxiedHit.java, store/src/java/com/zimbra/cs/index/SortBy.java, store/src/java/com/zimbra/cs/index/ZimbraHit.java, store/src/java/com/zimbra/cs/index/ZimbraQuery.java, store/src/java/com/zimbra/qa/unittest/SharedImapTests.java, store/src/java/com/zimbra/qa/unittest/TestImapViaEmbeddedRemote.java, store/src/java/com/zimbra/qa/unittest/TestImapViaImapDaemon.java, store/src/java/com/zimbra/qa/unittest/TestResults.java
Also implemented search sorting by ID - likely to be more efficient than sorting by date where there may be more items with the same key.
=> ZCS-3810 imap uid search should return more than 1000 items

store/src/java/com/zimbra/cs/index/solr/SolrIndex.java
The bug was caused by the lack of special character escaping in the `SolrIndex::docFreq` method, which is run to determine whether to execute a query index-first. This breaks IMAP queries that target the `l.field` index field, such as `bcc`, that indexes email headers. The problem occurs because such queries compile to an invalid Solr search string like `l.field:bcc:foo*` (notice the unescaped second colon). This bug can also be reproduced in the web client with the query `#bcc:foo*`.
This doesn't happen with non-wildcard queries because those get expressed as `terms` component filters like `{!terms f=l.field}bcc:foo`
The solution is simply to add character-escaping logic to the `SolrIndex::docFreq` method, similar to how it is handled in the `SolrIndex::search` method.
Additionally, this …
=> ZCS-4249: Fixed Imap Search Bug with Solr

client/src/java/com/zimbra/client/ZMailbox.java, store/src/java/com/zimbra/qa/unittest/TestZClient.java
If set an option to validate the auth token via AuthRequest
in ZMailbox.Options via `setAuthAuthToken` then we ended
up with a context which contains an account specification but
no auth token (it is in the AuthRequest instead)
This causes the soap handler to reject the request as it
requires an auth token if account is specified.
Initially planned to relax the handling server end but I now
think that is tricky and potentially error prone.
This bug was introduced for IMAPD work as part of several
efforts to reduce exceptions when GetInfoRequest was called
before auth to get account details.  With this change which
backs out some of that but not all, none were seen when
running the ImapDaemon developer SOAP tests.
=> ZCS-4341:ZMailbox constructor if setAuthAuthToken

store/src/java-test/com/zimbra/cs/service/UserServletTest.java, store/src/java/com/zimbra/cs/service/UserServlet.java
Added code to return 404 status code when auth is BASIC irrespective of whether the accounts exists or authentication fails.
Added unit test
1285 | 0 | 0 | 10 | 100.00% | 286.098
=> ZCS-3948 Account enumeration

pkg-builder.pl
Reverting zm-native jar to zimbra-native.jar
=> ZCS-4380 Reverting zm-native jar name

common/src/java/com/zimbra/common/util/Log.java
Moving stack trace to debug level
=> ZCS-1695 Moving stack trace to debug level

store/src/java/com/zimbra/cs/mailbox/DistributedMailboxLockFactory.java
* Suspect the code that counted waiters of locks didn't have a good way
of noticing when a waiter was no longer waiting.
* Added some more levels of stack trace as seen some traces where more
might have been useful.
* `releaseReadLocksBeforeWriteLock` now says what it is doing at info
level - at least in the short term.  Would like to know how often we
do this.
=> ZCS-4276:MailboxLock waiters accounting

store/src/java/com/zimbra/cs/index/solr/SolrIndex.java
The Solr backend uses the `edismax` query parser for queries that target multiple index fields, such as regular text searches. It does this by using [local params](https://lucene.apache.org/solr/guide/7_2/local-parameters-in-queries.html) syntax: `{!edismax <parameters>}query string`. In certain cases, however, this does not parse as expected (such as when the first term is a stop word). To get around this, we can use [parameter dereferencing](https://lucene.apache.org/solr/guide/7_2/local-parameters-in-queries.html#parameter-dereferencing) to externalize the query string. This resolves any issues caused by parser ambiguity.
To implement this, a new inner class `ReferencedQueryParams` has been added to `SolrIndex`. This class maintains a map of variable names mapped to search strings they …
=> ZCS-4597: Parameter dereferencing in Solr queries

common/src/java/com/zimbra/common/util/Log.java, store/src/java/com/zimbra/cs/ldap/LdapUsage.java
This is intended for merging Malte's pull request https://github.com/Zimbra/zm-mailbox/pull/595
Also made a few adjustments and added a new warnQuietly/errorQuietly variant.
=> ZCS-4928 Bug 95459: Improve warning "unknown GAL op"

soap/src/java/com/zimbra/soap/mail/message/CreateAppointmentExceptionRequest.java, store/src/java/com/zimbra/cs/mailbox/CalendarItem.java, store/src/java/com/zimbra/cs/mailbox/Mailbox.java, store/src/java/com/zimbra/cs/mailbox/Message.java, store/src/java/com/zimbra/cs/mailbox/calendar/InviteInfo.java, store/src/java/com/zimbra/qa/unittest/TestJaxb.java, store/src/java/com/zimbra/qa/unittest/TestUtil.java
Note that created hotfix/8.8.8.p3 branch where 8.8.8.p1 was.  I assume p3 is the right terminology based on message from Sandesh today (i.e. NOT p2)
Hmm.  Actually 8.8.8 patch 2 has apparently just been release but I'm confused as I can't see any evidence for branches or tags referencing it in zm-mailbox or zm-build???
=> Bugfix/zcs 4847 back port 3055 to 8.8.8.p3

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java
Add new Ldap attributes
zimbraCustomTemplateUserDesignation
zimbraCustomTemplateUserSignature
zimbraCustomTemplateID (user is allowed to have multiple templates so each this attribute should cardinality="multi")
=> NICPS-187: Update templateID cardinality to multi

store/src/java/com/zimbra/cs/service/formatter/MobileConfigFormatter.java
Fixed npe for unauthenticated account.
=> ZCS-4832 : fixed npe for unauthenticated account

store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
1. Recovery Code based Auth will not fail if account is in locked state, it will go on to validate the recovery Code, if code validation is success, account will be unlocked.
2. clear the recoveryCode after successful validation
=> ZCS-4800: recovery Code based Auth

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, common/src/java/com/zimbra/common/localconfig/LC.java, soap/src/java/com/zimbra/soap/admin/message/GetAttributeInfoRequest.java, soap/src/java/com/zimbra/soap/admin/type/DataSourceType.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/AttributeClass.java, store/src/java/com/zimbra/cs/account/AttributeManager.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/java/com/zimbra/cs/service/admin/ModifyDataSource.java
Added ldap attributes for clien_id, client_secret, client_redirect_uri and API scope
Added datasource for oauth social
Added class handler config to LC
=> ZCS-5109 Adding oauth ldap attributes

store/src/java/com/zimbra/cs/filter/ZimbraMailAdapter.java
Change the logic that display the discard message
Verified that all unit test pass
Created a filter with discard action and verified the message is discarded and message is logged.
=> ZCS-5085 Restoring log message

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java
=> ZCS-5109 Modified attrs description

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml
**Problem:** Build failed to install because of ldap changes.
- zimbra-attrs.xml file was rebased in feature/PasswordReset branch from develop.
- and then feature/PasswordReset branch was merged in develop
**Fix:**
- git rebased zimbra-attrs.xml automatically except the conflicts and it broke the attributes
- picked zimbra-attrs.xml before merge and added feature/PasswordReset branch changes manually
- tested build locally. ldap is starting after this changes.
=> Fixing build failure

soap/src/java/com/zimbra/soap/admin/type/DataSourceType.java, store/src/java/com/zimbra/cs/datasource/CalDavDataImport.java, store/src/java/com/zimbra/cs/dav/client/CalDavClient.java, store/src/java/com/zimbra/cs/dav/client/WebDavClient.java
Part of changes required for adding oauth2 authorization header while making dav requests. CalDavDataImport and client class need to be extended to achieve this.
=> ZCS-5305:Google Calendar Sync using caldav with Oauth2 datasource

store/src/java-test/com/zimbra/cs/service/ResetPasswordTest.java, store/src/java/com/zimbra/cs/service/account/ResetPassword.java
**Problem:** Fix failing unit test
**Fix:** Fixed unit test and updated related code.
**Testing done:** Tested unit test on local by running single unit test
=> ZCS-5343 Fix failing unit test on build server

common/src/java/com/zimbra/common/httpclient/HttpClientUtil.java, common/src/java/com/zimbra/common/httpclient/HttpProxyConfig.java, common/src/java/com/zimbra/common/httpclient/InputStreamRequestHttpRetryHandler.java, common/src/java/com/zimbra/common/net/ProtocolSocketFactoryWrapper.java, common/src/java/com/zimbra/common/net/ProxyHostConfiguration.java, common/src/java/com/zimbra/common/net/SecureProtocolSocketFactoryWrapper.java, common/src/java/com/zimbra/common/net/SocketFactories.java, common/src/java/com/zimbra/common/service/RemoteServiceException.java, common/src/java/com/zimbra/common/soap/SoapHttpTransport.java, common/src/java/com/zimbra/common/soap/SoapTestHarness.java, common/src/java/com/zimbra/common/soap/SoapTransport.java, common/src/java/com/zimbra/common/util/BufferStreamRequestEntity.java, common/src/java/com/zimbra/common/util/HttpUtil.java, common/src/java/com/zimbra/common/util/SoapDebugListener.java, common/src/java/com/zimbra/common/util/ZimbraHttpConnectionManager.java, common/src/java/com/zimbra/common/util/ngxlookup/ZimbraNginxLookUpClient.java
Verified that unit test pass. Verified that there are no compilation errors.
Completed sanity test on FOSS Build with new http client library changes.
173 | 0 | 0 | 2 | 100.00% | 8.442
=> ZCS-4845_1 changes in common for httpclient upgrade

client/ivy.xml, client/src/java/com/zimbra/client/GetMethodInputStream.java, client/src/java/com/zimbra/client/ZMailbox.java, client/src/java/com/zimbra/client/ZSoapProvisioning.java
Verified that unit test pass. Verified that there are no compilation errors.
Completed sanity test on FOSS Build with new http client library changes.
90 | 0 | 0 | 1 | 100.00% | 8.998
=> ZCS-4845_2 Changes in client for httpclient jar upgrade

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
- Created new LDAP attribute for storing email template API URL 
- So this will be configurable environment specific
=> NICPS-188: Added new LDAP variable for configuring Email Template Api

store/src/java/com/zimbra/cs/db/DbSearch.java, store/src/java/com/zimbra/cs/mailbox/MailboxIndex.java
Ran unit test and automation both are passing.
=> Fixing issues found in testing

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
New custom LDAP attribute for zimbraSplashScreenTimeOut
=> NICPS-363 : New custom LDAP attribute for zimbraSplashScreenTimeOut

store/build.xml
Add jars required by graphql in service war
=> ZCS-5738 Building zm-gql extension

soap/src/java/com/zimbra/soap/account/message/AuthResponse.java, soap/src/java/com/zimbra/soap/account/type/Attr.java, soap/src/java/com/zimbra/soap/account/type/AuthToken.java, soap/src/java/com/zimbra/soap/account/type/PreAuth.java, soap/src/java/com/zimbra/soap/account/type/Pref.java, soap/src/java/com/zimbra/soap/account/type/Session.java, soap/src/java/com/zimbra/soap/type/AccountBy.java, soap/src/java/com/zimbra/soap/type/AccountSelector.java
Annotations for auth resolver docs/input containers.
See jira ticket and Zimbra/zm-gql#13 for further details. No impact to soap implementation.
*Testing Done*
Manual testing of the ticket's criteria.
*Testing to  be done by QA*
See testrail.
=> ZCS-5606 Annotations for auth resolver.

store/src/java/com/zimbra/cs/service/admin/Auth.java
Hi @zimsuchitgupta, as you are pretty much aware of the context here. Please review this change.
=> NICPS-381: Changes in protocol value being passed to authAccount

common/src/java/com/zimbra/common/soap/AccountConstants.java, soap/src/java/com/zimbra/soap/JaxbUtil.java, soap/src/java/com/zimbra/soap/account/message/GetHABRequest.java, soap/src/java/com/zimbra/soap/account/message/GetHABResponse.java, soap/src/java/com/zimbra/soap/account/message/HABGroup.java, soap/src/java/com/zimbra/soap/account/type/HABGroup.java, store/docs/soap-admin.txt, store/docs/soap.txt, store/src/java-test/com/zimbra/cs/service/util/TestHabGroupSort.java, store/src/java/com/zimbra/cs/account/ProvUtil.java, store/src/java/com/zimbra/cs/account/Provisioning.java, store/src/java/com/zimbra/cs/account/SearchDirectoryOptions.java, store/src/java/com/zimbra/cs/account/ldap/LdapDIT.java, store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java, store/src/java/com/zimbra/cs/ldap/ZLdapFilterFactory.java, store/src/java/com/zimbra/cs/ldap/unboundid/UBIDLdapFilterFactory.java, store/src/java/com/zimbra/cs/service/account/AccountService.java, store/src/java/com/zimbra/cs/service/account/DistributionListDocumentHandler.java, store/src/java/com/zimbra/cs/service/account/GetHAB.java, store/src/java/com/zimbra/cs/service/account/ToXML.java, store/src/java/com/zimbra/cs/service/util/SortBySeniorityIndexThenName.java, store/src/java/com/zimbra/qa/unittest/TestGroups.java
Implemented GetHAB API.
Verified the API by setting up groups with sub groups and validating that the response correctly depicts the parent child relationship.
Verified that groups only under the requested root group are returned
=> ZCS-5397 Implementing GetHAB API

pkg-builder.pl
bump up package version for 8.8.9
=> Feature/nicps 386  bump up package version for 8.8.9

common/src/java/com/zimbra/common/soap/AdminConstants.java, soap/src/java/com/zimbra/soap/JaxbUtil.java, soap/src/java/com/zimbra/soap/admin/message/ModifyHABGroupRequest.java, soap/src/java/com/zimbra/soap/admin/message/ModifyHABGroupResponse.java, soap/src/java/com/zimbra/soap/admin/type/HABGroupOperation.java, store/src/java/com/zimbra/cs/account/ProvUtil.java, store/src/java/com/zimbra/cs/account/Provisioning.java, store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/java/com/zimbra/cs/account/soap/SoapProvisioning.java, store/src/java/com/zimbra/cs/service/admin/AdminService.java, store/src/java/com/zimbra/cs/service/admin/ModifyHABGroup.java
Added Admin API to move a HAB group from one parent to another across OU and domains
Verified the test cases mentioned in test rail are passing.
=> ZCS-5708 Modify HAB group

store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
=> ZCS-5395 correcting typo

common/src/java/com/zimbra/common/service/ServiceException.java, store/src/java/com/zimbra/soap/SoapEngine.java, store/src/java/com/zimbra/soap/ZimbraSoapContext.java
Changed the error message for failure SOAP request
=> NICPS-379: Changed the error message for failure SOAP request

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
Added new LDAP attribute zimbraLoginHistoryApiUrl for login history
Testing Instruction updated in ticket to test ticket.
=> NICPS-295: Added new ldap attribute for login history

common/src/java/com/zimbra/common/gql/GqlConstants.java
Adding constants used for sessions list.
=> ZCS-4905 Add session list constants

store/docs/soap-admin.txt, store/src/java/com/zimbra/cs/gal/GalSearchControl.java
**Problem:** address list should be created even if the gal account is not present
**Fix:**
- changed code to avoid gal account
- updated soap-admin.txt
**Testing done:** Manually tested CreateAddressListRequest
**Testing to be done by QA:** Test CreateAddressListRequest completely.
=> ZCS-5847 Create address list API and store in the ldap

pkg-builder.pl
This reverts commit c777cf8ef0e526234dd672e3cd40660d6aa76507.
=> Revert "NICPS-386: update version to handle zm-patch dependency (#726)"

pkg-builder.pl
This reverts commit 01ccd3ed66c817fe9563bc4454a81edf038acf36.
=> NICPS-386: reverting back the revert made in feature/NICPS-386_1

store/src/java/com/zimbra/cs/gal/GalSearchControl.java
**Problem:** if "searchFilter" is not provided in SearchGalRequest and AutoCompleteRequest, QUERY_PARSE_ERROR exception is thrown.
**Fix:** Corrected "AND" and "()" usage.
- Tested search gal request with and without name
- Tested search gal request with and without searchFilter
- Tested search gal request with and without ref
- Tested search gal request with different "type" values
- All the testing is done from soapui
- Ran the failing automation /opt/qa/soapvalidator/data/soapvalidator/MailClient/GAL/LargeGAL/GALAccount/ExternalLDAP_1000.xml (attached result of the automation below)
[ExternalLDAP_1000.txt](https://github.com/Zimbra/zm-mailbox/files/2424623/ExternalLDAP_1000.txt)
- Test search gal request and auto complete request …
=> ZCS-6016 QUERY_PARSE_ERROR while searching for contacts from webclient

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
3 new LDAP attributes added 
zimbraDynamicBannerEnabled
zimbraDynamicBannerImage
zimbraDynamicBannerInterval
=> NICPS-287: Dynamic Banner After Login: Ldap Attributes

soap/src/java/com/zimbra/soap/admin/message/GetAddressListInfoRequest.java, soap/src/java/com/zimbra/soap/admin/message/GetAddressListInfoResponse.java
* Support domain in address list info response. 
* Move name in request to attribute.
Former tests + additional top level condition negation.
See test rail and soap harness tests + discussion notes from latest meeting.
=> ZCS-6075 Add domain to address list info response.

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java, store/src/java/com/zimbra/cs/lmtpserver/ZimbraLmtpBackend.java, store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java
Added code to send Email as SMS.
Testing Instructions added in ticket to verify changes.
=> NICPS-411: Added Email To SMS Code

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java
Changes for new CR feedback
Removed double semi column and imports
=> NICPS-411: Fixed CR feedback issue

store/docs/soap.txt
* Updated soap.txt for `GetAddressListInfo`.
N/A
N/A
=> ZCS-6075 Update soap.txt for get address list info.

common/src/java/com/zimbra/common/gql/GqlConstants.java, soap/src/java/com/zimbra/soap/type/OpValue.java
* Added annotations for white and black list for zm-gql.
* List style implementation for op values
See associated PR:
Zimbra/zm-gql#37
Fetches and updates - see jira for queries, mutations, and variables.
See testrail/jira.
=> ZCS-6149 Add annotations for white and black list.

common/src/java/com/zimbra/common/gql/GqlConstants.java, soap/src/java/com/zimbra/soap/account/type/NameId.java, soap/src/java/com/zimbra/soap/account/type/Signature.java, soap/src/java/com/zimbra/soap/account/type/SignatureContent.java
* Add annotations for signature resources
See associated PR:
Zimbra/zm-gql#36
Basic signature queries. See jira.
Testrail/Jira
=> ZCS-6139 Add annotations for gql signature resource.

common/src/java/com/zimbra/common/gql/GqlConstants.java, soap/src/java/com/zimbra/soap/account/type/AccountZimletGlobalConfigInfo.java, soap/src/java/com/zimbra/soap/account/type/AccountZimletHostConfigInfo.java, soap/src/java/com/zimbra/soap/account/type/AccountZimletInclude.java, soap/src/java/com/zimbra/soap/account/type/AccountZimletIncludeCSS.java, soap/src/java/com/zimbra/soap/account/type/AccountZimletTarget.java, soap/src/java/com/zimbra/soap/account/type/ZimletServerExtension.java, soap/src/java/com/zimbra/soap/admin/type/AdminZimletProperty.java, soap/src/java/com/zimbra/soap/type/LicenseStatus.java, store/src/java-test/com/zimbra/cs/service/mail/ModifyProfileImageTest.java
**Problem:** Some elements in Zimlet block are missing.
**Fix:** Added annotations for the missing
**Testing done:** Tested GetInfoRequest from graphiql client manually.
**Testing to be done by QA:** Test GetInfoRequest and validate graphql response.
=> ZCS-4586 Added missing license and zimlet elements

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java
Update log message.
Testing Instruction added to verify ticket.
=> NICPS-447: Changes in log and resp code condition

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java
- Fixed duplicate/repeating sms issue
- Fixed long msg issue
- Fixed other language support sms
- Update testing instructions to verify ticket
=> NICPS-471: Fixes for duplicate sms and other language

common/src/java/com/zimbra/common/gql/GqlConstants.java, soap/src/java/com/zimbra/soap/mail/type/AutoCompleteMatch.java, soap/src/java/com/zimbra/soap/type/GalSearchType.java
* Added annotations and constants for auto-complete
See associated PR:
Zimbra/zm-gql#41
N/A for this project. See jira for queries.
N/A for this project. See testrail.
=> ZCS-6137 Add gql annotations and constants for auto-complete API.

store/src/java/com/zimbra/cs/fb/ExchangeEWSFreeBusyProvider.java, store/src/java/com/zimbra/cs/fb/FreeBusy.java, store/src/java/com/zimbra/cs/service/mail/ToXML.java
Used DetailedMerged view instead of Detailed while making the request. Used the merged view to create information about intervals
Iterated over the calendar event array to find matching interval and populate event data
In response only returned all parameters for detailed view for others it is start and end time
Tested by creating users on exchange side with different permission on FB info and requesting free busy for them
=> ZCS-6286 Fixed the code added to populate detailed data

store/src/java/com/zimbra/cs/mailclient/MailOutputStream.java
Verify IDN works with javamail_zsmtp as true
=> NICPS-487: IDN - make it working with javamail_zsmtp as true

common/src/java/com/zimbra/common/gql/GqlConstants.java, soap/src/java/com/zimbra/soap/mail/type/FreeBusySlot.java, soap/src/java/com/zimbra/soap/mail/type/FreeBusyUserInfo.java, soap/src/java/com/zimbra/soap/mail/type/FreeBusyUserSpec.java
* Added graphql annotations for freeBusy
See associated PR:
Zimbra/zm-gql#44
Free busy checks for different users
See jira/testrail.
=> ZCS-6141 Annotations for freeBusy api.

soap/src/java/com/zimbra/soap/mail/type/FreeBusyUserInfo.java
* Use identifier instead of email (better represents the data).
freeBusy fetch by id and name
=> ZCS-6141 Use identifier instead of email for freebusy response.

common/src/java/com/zimbra/common/gql/GqlConstants.java, soap/src/java/com/zimbra/soap/account/message/SearchGalResponse.java, soap/src/java/com/zimbra/soap/account/type/AccountCustomMetadata.java, soap/src/java/com/zimbra/soap/account/type/ContactGroupMember.java, soap/src/java/com/zimbra/soap/account/type/ContactInfo.java, soap/src/java/com/zimbra/soap/account/type/EntrySearchFilterInfo.java, soap/src/java/com/zimbra/soap/account/type/EntrySearchFilterMultiCond.java, soap/src/java/com/zimbra/soap/account/type/EntrySearchFilterSingleCond.java, soap/src/java/com/zimbra/soap/account/type/MemberOfSelector.java
Create Resource and Resolver classes for SearchGal
=> ZCS-6425:Create Resource and Resolver classes for SearchGal

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java
Bugfix for repeating message on same mobile number
Bugfix for repeating message on same mobile number when email id added with mobile number
=> NICPS-525: Fixed multi sms issue

.travis.yml, build-common.xml, common/ivy.xml, common/src/java-test/com/zimbra/common/util/QuotedTextUtilTest.java, common/src/java/com/zimbra/common/net/CustomHostnameVerifier.java, soap/ivy.xml, store/ivy.xml, store/src/java/com/zimbra/cs/service/authenticator/ClientCertAuthenticator.java
Compiled code against JDK 11. 
Fixed failing code
Verified that 'ant publish-local-all' succeeds
Ran unit tests
1266 | 0 | 0 | 10 | 100.00% | 1414.386
Compiled the code against JDK 1.8 and tested on ZCS installation. 
Some unit tests which depend on power mock and mockito have know issues with JDK 11. Excluded them for now. Will fix them in next sprint.
=> ZCS-6513 Compiling zm-mailbox against JDK11

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java, store/src/java/com/zimbra/cs/mailbox/alerts/CalItemEmailReminderTask.java, store/src/java/com/zimbra/cs/mailbox/alerts/CalItemReminderService.java, store/src/java/com/zimbra/cs/mailbox/alerts/CalItemReminderTaskBase.java, store/src/java/com/zimbra/cs/mailbox/alerts/CalItemSmsReminderTask.java, store/src/java/com/zimbra/cs/service/mail/CreateCalendarItem.java, store/src/java/com/zimbra/cs/service/mail/SendInviteReply.java
NICPS-535: Worked on calendar sms part 2
=> NICPS-535: Worked on calendar sms part 2

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java
NICPS-540: Changes in Account Tab from preferences
=> NICPS-540: Changes in Account Tab from preferences

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java
NICPS-566: Email2SMS and Calendar notification proxy work and add keywords in Email2SMS.
=> NICPS-566: Email2SMS and Calendar notification proxy work

store/src/java/com/zimbra/cs/imap/NioImapHandler.java, store/src/java/com/zimbra/cs/imap/TcpImapHandler.java, store/src/java/com/zimbra/cs/service/FileUploadServlet.java
This pull request integrates changes from https://github.com/Zimbra/zm-mailbox/pull/862 and https://github.com/Zimbra/zm-mailbox/pull/830
Thanks to Victor-D
=> ZCS-7158 better imap logging

store/src/java-test/com/zimbra/cs/html/DefangFilterTest.java, store/src/java/com/zimbra/cs/html/owasp/HtmlElementsBuilder.java, store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java, store/src/java/com/zimbra/cs/html/owasp/OwaspPolicy.java, store/src/java/com/zimbra/cs/html/owasp/policies/AElementPolicy.java, store/src/java/com/zimbra/cs/html/owasp/policies/AreaElementPolicy.java, store/src/java/com/zimbra/cs/html/owasp/policies/NoSpaceEncodedCharAttributePolicy.java
Fixed following test cases in OWASP:
testHtmlWithStyleValueContainingMultiLineUrl
testBug46948
testBug11464
testBug98215
testBug105001
testBug82303
Unit tests pass
=> ZCS-6873:Fix test cases with OWASP-1

client/src/java/com/zimbra/client/ZMailbox.java, store/src/java/com/zimbra/cs/dav/service/DavMethod.java
Fixes around the following failing automation.
MailClient/FilterRules/Bugs/bug26422.xml
Dav/CalDav/Protocol/rfc4791/calendar-share.xml
Verified after the fix that the above SOAP automation tests are passing.
Verified Fileupload related test cases are not affected.
=> ZCS-7239 Fixes around failing SOAP automation

store/src/java/com/zimbra/cs/db/Versions.java
Added new migration script migrate20190401-ZimbraChat.pl to fix chat 
https://github.com/Zimbra/zm-db-conf/pull/5
=> Add DB migration version to 110

common/src/java/com/zimbra/common/localconfig/LC.java, store/src/java/com/zimbra/cs/imap/MemcachedImapCache.java, store/src/java/com/zimbra/cs/io/SecureObjectInputStream.java
Made fix for ImapFolder de-serialize exception by adding list of classes for comparing against valid list.
=> ZBUG-977: updating allowed list of classes to deserialize

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java, store/src/java/com/zimbra/cs/service/mail/SendVerificationCode.java
NICPS-609: Issues with Calendar to SMS notification preferences
=> NICPS-609: Issues with Calendar to SMS notification preferences

store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java
NICPS-627: Account Tab preference default value change
=> NICPS-627: Account Tab preference default value change

build.xml, store/build.xml, store/src/java-test/com/zimbra/cs/html/DefangFilterTest.java, store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
OWASP unit test was failing due to owasp and antisamy policy file was not being loaded
=> ZCS-7587:fix failing OWASP unit tests

store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
=> Revert "ZBUG-674 changed to honor zimbraLastLogonTimeStampFrequency even when…"

store/build.xml
Added tika jar to service webapp lib. Correcting other indentations.
=> ZBUG-711:adding dependent jar

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, soap/src/java/com/zimbra/soap/admin/type/CountObjectsType.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java
Migrated license changes from Zimbrax of zcs 7809
PR's
https://github.com/Zimbra/zm-license-tools/pull/13
https://github.com/Zimbra/zm-license-store/pull/7
=> ZCS-7964: migrating license changes from zimbrax of zcs 7809

store/conf/attrs/zimbra-attrs.xml
add value for zimbrax in zimbraPrefClientType to be allowed it to be set as default client
=> ZXL-158: ZX UI on Zimbra 8.8 Commercialization

build-common.xml, store/src/java-test/com/zimbra/cs/mailbox/ContactTest.java, store/src/java/com/zimbra/cs/service/mail/ToXML.java
Fixed a NPE seen when configured with AD and contact group has members with no email.
Added uni test
=> ZBUG-987 Fixing NPE

store/build.xml
upgraded the version for spring-expression to 5.1.10. Missed it in an earlier commit
=> ZCS-8018 Upgrade apache cxf jars

build-ivysettings.xml, client/ivy.xml, common/ivy.xml, soap/ivy.xml, store/ivy.xml
Issue: Third-party vulnerabilities in dom4j
Fix: Upgrade dom4j to the latest version
Related PRs:
zm-network-build/ivysettings-network.xml - https://github.com/Zimbra/zm-network-build/pull/9
zm-zcs/ivysettings.xml - https://github.com/Zimbra/zm-zcs/pull/9
Zimbra/zm-core-utils - https://github.com/Zimbra/zm-core-utils/pull/68
Zimbra/zm-zcs-lib - https://github.com/Zimbra/zm-zcs-lib/pull/62
Zm-mailbox - https://github.com/Zimbra/zm-mailbox/pull/988
zm-xmbxsearch-store - https://github.com/Zimbra/zm-xmbxsearch-store/pull/4
zm-license-store -  https://github.com/Zimbra/zm-license-store/pull/9
zm-ews-common - https://github.com/Zimbra/zm-ews-common/pull/4
zm-hsm-store - https://github.com/Zimbra/zm-hsm-store/pull/4
zm-bulkprovision-store - …
=> ZCS-8014: Third party vulnerabilities in dom4j

build-ivysettings.xml, client/ivy.xml, common/ivy.xml, common/src/java-test/com/zimbra/common/util/MapUtilTest.java, soap/ivy-soapdocs.xml, soap/ivy.xml, store/ivy.xml, store/src/java/com/zimbra/cs/mailbox/ContactAutoComplete.java, store/src/java/com/zimbra/cs/mailclient/smtp/SmtpConnection.java
Issue:
Vulnerabilities in older version 23.0 of Guava.
Fix:
Update version to 28.1-jre
=> ZCS-8017: updating guava version to latest from 23.0

store/src/java/com/zimbra/cs/mailbox/EmailToSMS.java, store/src/java/com/zimbra/cs/mailbox/alerts/CalItemReminderTaskBase.java
Fix subject issue in Task SMS. Added all details in Task Reminder SMS.
=> NICPS-692: Made changes for Task reminder SMS

common/src/java/com/zimbra/common/localconfig/LC.java, soap/src/java/com/zimbra/soap/admin/type/DataSourceType.java
Backporting no-op ds type for ZX-1094 and future use config keys.
=> Backport oauth handlers and no-op ds type.

store/src/java/com/zimbra/cs/service/account/GetInfo.java
Traversing Mail-Alias & encoding the same for Unicode.
=> NICPS-683: Traversing Mail-Alias & encoding the same

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
Run ant generate-getters and pushing updated files
=> ZCS-8290: pushing files after running generate-getters

store/src/java/com/zimbra/cs/mailbox/MailSender.java, store/src/java/com/zimbra/cs/service/mail/ParseMimeMessage.java, store/src/java/com/zimbra/cs/service/mail/SendMsg.java, store/src/java/com/zimbra/cs/service/util/ItemId.java, store/src/java/com/zimbra/soap/SoapEngine.java, store/src/java/com/zimbra/soap/ZimbraSoapContext.java
Issue : After fixing zbug-903 there is some regression which was causing the sendMsgRequest to fail in case of persona. Then after fixing zbug-1292 there are more regressions.
Reverting zbug-903 and zbug-1292 changes.
=> Bugfix/revert : Reverting ZBUG-903 and ZBUG-1292

store/src/java/com/zimbra/cs/imap/ImapHandler.java
**Issue:**
Shared folders in IMAP synchronization are getting wrongly mapped to owners folders and shared ones.
**Fix:**
Separated the list of owner & shared folders and passed the list.
For shared folder list removed the folder mapping.
Shared root folder of account with sharee.
Tested the folders are mapped properly and shared folders show content within them and not the owners ones.
=> ZBUG-1096: fixing IMAP synchronization problem on Mobile App

store/conf/attrs/zimbra-attrs.xml
-Replaced zimbrax with modern.
=> PREAPPS-4182: Change login options available to the user

store/build.xml, store/ivy.xml
Adding jars related to tika extractor in the war
=> ZBUG-148 Adding tika jars

store/build.xml
Added jars required for parsing files mentioned in 8692 by Tika.
Verified by both uploading the attachments to Briefcase and sending them as mail
=> ZCS-8692 Add jars required by Tika for parsing

common/src/java/com/zimbra/common/soap/AdminConstants.java, store/src/db/hsqldb/db.sql
Added enums for required constants.
Made account id nullable
=> ZCS-8730:adding enum

store/src/java/com/zimbra/cs/service/mail/GetOutOfOffice.java
NICPS-749: OOO: Add exception when user is not exist.
=> NICPS-749: OOO: Add exception when user is not exist

store/conf/web.xml.production
Added multipartconfig to ExtensionDispatcherServlet  in order to handle multipart/form-data and file upload
Tested with sample extension and client
=> ZCS-8930 Adding multipartconfig to ExtensionDispatcherServlet

common/src/java/com/zimbra/common/localconfig/LC.java
Reverted to using convertd extraction client.
Made the client class configurable
verified extraction of attachments works with convertd.
verified reindexing and search works
=> ZBUG-1499 Reverting to convertd client

store-conf/conf/globs2, store/build.xml, store/ivy.xml, store/src/java/com/zimbra/cs/service/FileUploadServlet.java
Removed the Usage of Tika in core mailbox.
Reworked fix for ZBUG-711 and verified ZBUG-711 
Verified ZBUG-1499
Imported 1GB mailbox and reindexed, no issues seen
=> ZBUG-148 Fixing Tika extractor

store/src/java/com/zimbra/cs/service/mail/SendMsg.java, store/src/java/com/zimbra/cs/util/AccountUtil.java, store/src/java/com/zimbra/soap/SoapEngine.java, store/src/java/com/zimbra/soap/ZimbraSoapContext.java
Refactored the code for handling  Persona  to be in SendMsg.
Removed previous changes
Also now when delegate owner account is inactive and the mail is being sent as a Persona of the delegate owner account, the mail will be saved to sent folder of delegated account.
verified  ZBUG-1660 ZBUG-1659 ZBUG-1665 ZBUG-1670 ZBUG-903 ZBUG-1209 ZBUG-1292 ZBUG-1334 ZCS-9483 ZCS-9464 and ZBUG-1666
Will add unit test
=> ZCS-1666 1670

store/src/java/com/zimbra/cs/service/mail/SendMsg.java
Added FetchMode.AUTOCREATE,true while fetching mailbox located on another box.
Verified test scenarios of ZBUG-903 and related bugs.
=> ZBUG-1850 SendAs/SOBO regression

store/src/java/com/zimbra/cs/service/mail/SendMsg.java
Reverts Zimbra/zm-mailbox#1086
=> Revert "ZBUG-1850 SendAs/SOBO regression"

store/src/java/com/zimbra/cs/service/mail/SendMsg.java
**Issue:** 
- When sending email using persona in case of multi node setup does not delete draft and fills up the draft folder.
- This issue only occurs when users are on different server.
**Fix:**
- In case of multi node environment, when 2 user are on different server and lets say userA has given delegate right to userB and userB has created a persona for userA using userA email address, the request is getting proxied to the target server to execute the request and response is returned. As draft is always saved in logged in user's draft folder it was not able to delete the item.
- Instead of returning directly after proxying request, capture the request, delete the draft and then return the response.
**Test:**
- Tested on multi node environment that, sending mail using owner's persona …
=> ZBUG-1670: Sending email using owner persona does not delete draft

store/src/java/com/zimbra/cs/service/account/GetInfo.java
Like zimbra-x it is required to identify whether powerpaste is installed and running on the server so that the feature would work on UI. We do not have LDAP attributes for zimbra9 as we have added for zimbra-x.
Added condition to check if powerpaste service is installed and running in the GetInfo Response.
This will be returned as part of GetInfo response
`<powerpasteEnabled>1</powerpasteEnabled>`
1 - for enabled
0 - disabled
=> bugfix/zcs-10142: Send if powerpaste service is enabled and running in GetInfo response

common/src/java/com/zimbra/common/account/ForgetPasswordEnums.java, common/src/java/com/zimbra/common/soap/AccountConstants.java, common/src/java/com/zimbra/common/soap/AdminConstants.java, common/src/java/com/zimbra/common/util/L10nUtil.java, soap/src/java/com/zimbra/soap/JaxbUtil.java, soap/src/java/com/zimbra/soap/admin/message/ResetAccountPasswordRequest.java, soap/src/java/com/zimbra/soap/admin/message/ResetAccountPasswordResponse.java, soap/src/java/com/zimbra/soap/mail/type/RecoverAccountOperation.java, store-conf/conf/msgs/ZsMsg.properties, store/src/java/com/zimbra/cs/account/AccountServiceException.java, store/src/java/com/zimbra/cs/account/AuthToken.java, store/src/java/com/zimbra/cs/account/EmailChannel.java, store/src/java/com/zimbra/cs/account/ldap/LdapProvisioning.java, store/src/java/com/zimbra/cs/service/AuthProvider.java, store/src/java/com/zimbra/cs/service/ExternalUserProvServlet.java, store/src/java/com/zimbra/cs/service/account/Auth.java, store/src/java/com/zimbra/cs/service/account/ResetPassword.java, store/src/java/com/zimbra/cs/service/account/ToXML.java, store/src/java/com/zimbra/cs/service/admin/AdminService.java, store/src/java/com/zimbra/cs/service/admin/ResetAccountPassword.java, store/src/java/com/zimbra/cs/service/mail/RecoverAccount.java, store/src/java/com/zimbra/cs/service/util/ResetPasswordUtil.java, store/src/java/com/zimbra/cs/util/AccountUtil.java
This PR is the combination of ZCS -10191 and ZCS -10146 done in ZimbraX.
=> Feature/ZCS -10191&10146 - Reset Password Link and Forgot Password Changes

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java
changing since version to 9.0.0
=> changing since version of zimbraPasswordBlockCommonEnabled

store/src/java/com/zimbra/cs/util/ProxyConfGen.java
Access Onlyoffice through Zimbra nginx
=> feature/ZCS-10533 : onlyoffice to be accessed by zimbra nginx

common/src/java/com/zimbra/common/localconfig/DebugConfig.java
Disabling JTidy library by default.
=> ZCS-10599: Disabling JTidy library by default.

store/src/java-test/com/zimbra/cs/html/owasp/OwaspHtmlSanitizerTest.java
Adding unit test for media queries not get removed from the style sheet.
**Related PR:**
[Zimbra/antisamy](https://github.com/Zimbra/antisamy/pull/2)
=> ZCS-10594: Adding unit test for media queries not get removed from the style sheet.

store/src/java/com/zimbra/cs/db/Versions.java
Updated DB_Version to sync with zm-db-conf db version.
=> ZCS-10677: EAS16.1 - Merge feature/eas_zx branch to develop on zimbra org

soap/src/java/com/zimbra/soap/account/message/SearchGalRequest.java, store/src/java/com/zimbra/cs/gal/GalSearchControl.java, store/src/java/com/zimbra/cs/gal/GalSearchParams.java, store/src/java/com/zimbra/cs/service/account/SearchGal.java
Added query param in searchGal request to support searching based on queries. This is needed for the organisation chart zimlet.
=> ZCS-10642: SearchGal | add support for query in request

common/src/java/com/zimbra/common/localconfig/LC.java, common/src/java/com/zimbra/common/mailbox/FolderConstants.java, store/src/java/com/zimbra/cs/mailbox/Mailbox.java
Adding new system default folder Unsubsribe
=> ZCS-10780: add unsubscribe default system folder

common/src/java/com/zimbra/common/localconfig/LC.java
Default unsubscribe system folder creation local config attribute to false.
=> ZCS-10780: default unsubscribe system folder creation local config attr to false

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, common/src/java/com/zimbra/common/localconfig/LC.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java
- Introduce LDAP attributes for server and device json of FCM
=> ZCS:10942: introduce LDAP attributes for FCM configs and add LC for FCM threads count

store/src/java/com/zimbra/cs/zimlet/ProxyServlet.java
**Problem**
- Vulnerability while domain match
**Testing**
- Test for the use cases mentioned in ticket.
=> ZBUG-2368: ProxyServlet domain check: substring match vulnerability

store/src/java/com/zimbra/cs/milter/MilterHandler.java
Implement additional rules within the `SMFIC_Rcpt()` method of `MilterHandler` class to reject incoming messages where one or more recipients have set their `zimbraPrefMailForwardingAddress` property value to a distribution list address that they are not permitted to send messages according to the distribution list ACL.
- Messages will be rejected even if there are other compliant recipients on the message, which matches the existing behavior for mail filtering. So, it takes just one recipient that attempts to forward to a non-permitted distribution list for the whole message to be rejected.
- This rules will apply to both:
- Messages that come from the front-end through the back-end and then reach the MTA, and
- Messages that come directly to the MTA from the outside world.
**Setting up …
=> ZBUG-2165: fixes mail filtering not working with forwarding.

common/src/java/com/zimbra/common/util/memcached/ZimbraMemcachedClient.java
**Problem statement**
Create a hash of the key in Nginx instead of raw value
**Solution**
Hashed raw key text using hashing algorithm before putting key-value in cache
=> ZBUG-2738: Create a hash of the key in Nginx instead of raw value

common/src/java-test/com/zimbra/common/soap/ElementTest.java, common/src/java/com/zimbra/common/util/Log.java, soap/soapdocs/src/java-test/com/zimbra/doc/soap/ChangelogTest.java, soap/soapdocs/src/java/com/zimbra/doc/soap/XmlElementDescription.java, soap/src/java-test/com/zimbra/soap/JaxbToJsonTest.java, soap/src/java-test/com/zimbra/soap/admin/DumpSessionsTest.java, soap/src/java-test/com/zimbra/soap/admin/GetAllConfigTest.java, soap/src/java-test/com/zimbra/soap/admin/MailQueueActionTest.java, soap/src/java-test/com/zimbra/soap/mail/SendMsgRequestTest.java, soap/src/java-test/log4j-test.properties, store/src/java-test/log4j-test.properties
Upgraded pending classes syntax for log4j upgrade
=> ZCS-11112 : Upgrading log4j syntax for test classes

store/src/java/com/zimbra/cs/account/callback/AuthMech.java
Problem: Type issue in the error message
Solution: Fix typo invalud to invalid
=> ZCS-11341 : fix typo invalud to invalid

store/src/java/com/zimbra/cs/mailbox/Mountpoint.java
**Problem:** 
For active-sync, when user account is added on device which has shared folder and sub-folder, then sub-folders were not visible on device.
**Fix:**
Created interim mount point for sub-folder shared folder which does not persist on database but a mount point gets created for active-sync devices.
**Testing scenarios:**
Added account on device which has mounted shared folder with sub-folders
- sub-folders are visible
- emails inside sub-folder are getting synched
- All folders email are in sync
=> ZCS-10941: Shared sub folder not visible on device for active-sync

store/src/java/com/zimbra/cs/lmtpserver/ZimbraLmtpBackend.java
The issue described in ZCS-11499 was introduced by the ZCS-11096 implementation for External Email Warning (EEW), so that it would prevent for messages from being saved and rendered correctly under certain character encoding scenarios, even when the EEW feature was turned off. As a solution, further changes have been done on the `ZimbraLmtpBackend `class in order to make it compatible with all charsets described in the `MimeConstants `class rather than expecting a default charset, which was the root cause for the issue.
This issue was first identified from incompatibility the CP932 charset, also known as Windows-31J, and the solution fixes that. However, it also works for other charsets, including:
- us-ascii
- utf-8
- iso-8859-1
- windows-1252
- euc_cn
- gb2312
- gbk
- Windows-31J
- …
=> ZCS-11499: Regression - Message written in CP932 is displayed incorrectly (garbled)

store/src/java/com/zimbra/cs/service/UserServlet.java
This is a revision for previous work done for the ZBUG-2390, which is about certain resources (e.g. Briefcase) being accessible with username and password alone even when two factor authentication was enabled for the account. The previous work passed every test scenario on Patch 23 at the moment, but failed some of them when tested on Patch 25.
Please go to ticket for further details.
=> ZCS-11535: Briefcase content accessible without 2FA

store/src/java/com/zimbra/cs/html/owasp/OwaspHtmlSanitizer.java
Removing unwanted code from OwaspHtmlSanitizer
Related to ZBUG-2547
=> removed unwanted code

common/src/java/com/zimbra/common/soap/BackupConstants.java
Created a license attribute constant for BackupEnabled
=> ZCS-11794: Added a constant for license attribute BackupEnabled

store/src/java/com/zimbra/cs/volume/VolumeCLI.java
**Feature:** We need an option in zmvolume cli to add storeManagerClass
**Solution** We have added an option zmvolume cli to add storeManagerClass
=> ZCS-11828: Add option storeManagerClass in zmvolume cli

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
Updating ldap attribute ids and release version from 9.1.0 to 10.0.0
=> ZCS-11855: updating ldap attribute ids and release version

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, common/src/java/com/zimbra/common/soap/BackupConstants.java, soap/src/java/com/zimbra/soap/admin/message/ScheduleBackupsResponse.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
Feature 10.0.0 into develop branch.
=> Feature 10.0.0 backup and restore changes into develop

store/src/java/com/zimbra/cs/volume/VolumeCLI.java
**Problem Statement**
Error is displaying for OpenIO in zmvolume -l, getAllVolumeRequest is failing for Open IO volumes.
**Solution**
Fixed null issue for external volumes while calling zmvolume -l
=> ZCS-11909 Error is displaying for OpenIO in zmvolume -l

store/src/java/com/zimbra/cs/db/Versions.java
=> ZCS-11940: Update version info

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java
Updated attributes description from HSM to SM
=> ZCS-11975: Updated attributes description from HSM to SM

store/src/java/com/zimbra/cs/service/util/VolumeConfigUtil.java, store/src/java/com/zimbra/cs/volume/VolumeCLI.java
**Problem:** useIntelligentTiering and useInFrequentAccess both can be set as true from zmvolume CLI utility
**Solution:** added support of useIntelligentTiering and useInFrequentAccess to zmvolume CLI utility
=> Bugfix/zcs 12014: useIntelligentTiering and useInFrequentAccess both can be set as true from zmvolume CLI utility

store/src/java/com/zimbra/cs/volume/VolumeCLI.java
=> ZCS-12014 useIntelligentTiering and useInFrequentAccess both can be set as true from zmvolume CLI utility

store/src/java/com/zimbra/cs/service/FileUploadServlet.java
**Issue**
Content type detection is failing on file upload with revert of change for file upload restriction in ZCS-11780
**Fix**
Default the content type detection to tika instead of old mime detect
=> ZCS-12075: defaulting content type detection to tika for file upload

store/src/java/com/zimbra/cs/service/admin/CollectLDAPConfigZimbra.java
Added missing return statement
=> ZCS-11990: Added return statements

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java
Add ldap attributes for upcoming functions. The PR is to reserve attribute IDs.
=> ZCS-12470: added ldap attributes

common/src/java/com/zimbra/common/soap/AdminConstants.java, store/src/java/com/zimbra/cs/volume/VolumeCLI.java, store/src/java/com/zimbra/cs/volume/VolumeCLIConstants.java
+ Creating new PR for old ticket which was not merged earlier
+ Updating details in zmvolume help and correcting indentation
Modified description of zmvolume -h, updated description as per required in 
https://jira.corp.synacor.com/browse/ZCS-12207
Discarded PR (Not merged)
https://github.com/Zimbra/zm-mailbox/pull/1402
New PR (Yet to merge)
https://github.com/Zimbra/zm-mailbox/pull/1428
=> ZCS-12207 zmvolume -h description needs to modified.

common/src/java/com/zimbra/common/soap/SyncConstants.java
=> ZCS-12049 : Adding constant for boxer app

common/src/java/com/zimbra/common/soap/BackupConstants.java, soap/src/java/com/zimbra/soap/admin/type/MoveMailboxInfo.java
ZCS-12984 introducing new params in mailbox move command
=> ZCS-12984 introducing new params in mailboxmove command

store/src/java/com/zimbra/cs/db/Versions.java
Have created a script to update only office database, so updated the version.
=> ZBUG-3263: Updated the version as have updated onlyoffice database

common/src/java/com/zimbra/common/account/ZAttrProvisioning.java, store/conf/attrs/zimbra-attrs.xml, store/src/java/com/zimbra/cs/account/ZAttrAccount.java, store/src/java/com/zimbra/cs/account/ZAttrAlwaysOnCluster.java, store/src/java/com/zimbra/cs/account/ZAttrConfig.java, store/src/java/com/zimbra/cs/account/ZAttrCos.java, store/src/java/com/zimbra/cs/account/ZAttrDomain.java, store/src/java/com/zimbra/cs/account/ZAttrServer.java, store/src/java/com/zimbra/cs/account/callback/EventLoggerCallback.java
* Adding missing attributes from cloud to resolve upgrade conflicts
* Added a dummy EventLoggerCallback class to satisfy attribute requirements.
=> ZCS-12946 Porting cloud attributes
